### ISSUE TITLE
Better Author Resolution

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#10156]
### Proposal

This issue is meant to track and manage our various issues related to improving author resolution.

# Examples of Past Improvements
* #9003

We need to compile:
* [ ] Documentation about how our existing author resolution process works
* [ ] A list of existing issues relate to this topic, see: https://github.com/internetarchive/openlibrary/labels/Module%3A%20Identifier%20Resolution
* [ ] A list of common examples of where author resolution is failing
* [ ] A list of agreed upon improvements we could make (and opinions from stakeholders)
* [ ] Basic tests to know whether regressions are prevented
* [ ] Basic metrics / instrumentation to know how often conflations are occurring per month or per some other volume metric.

### Justification

Authors report that conflations are extremely hard to undo and cause a lot of work for librarians and harm the catalog.

The quantifiable impact, how often this problem occurs needs to be examined so we can know how we're doing.

#### Requirements Checklist

* [ ]

#### Related files

* Resolution: https://github.com/scottbarnes/openlibrary/blob/master/openlibrary/catalog/add_book/load_book.py#L57
* Tests: https://github.com/scottbarnes/openlibrary/blob/master/openlibrary/mocks/tests/test_mock_infobase.py

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by seabelis** [comment]
Here’s the Stephen King example.
The novelist: https://openlibrary.org/authors/OL19981A/Stephen_King
One of the lesser known Stephen Kings: https://openlibrary.org/authors/OL7829294A/Stephen_King. I created this profile in 2020 when I split off one of the incorrectly attributed works. The importer continues to import new novelist titles to this profile. That caused it to be incorrectly merged in 2022, which I reverted, but new titles belonging to the novelist continue to import to this profile. https://openlibrary.org/recentchanges/2022/07/22/merge-authors/95382993 There are some other Stephen Kings, but this is the profile that keeps getting imported to. The history does not capture items that are moved away from an author on the author's profile.

**Comment by hornc** [comment]
An undifferentiated Stephen King without dates is going to match all other undifferentiated Stephen Kings. (If there are more than one undifferentiated _name_ record, the system will pick the first / random one that matches, somewhat non-deterministic)

There needs to be a concrete signal, represented in metadata, for the import system, and anyone else, to know that an author record with only a name has been disambiguated by someone. I see this has a description, which helps human readers, but it is (currently) invisible to the importer. A super basic solution might be to not match undifferentiated author records if the existing record has a description populated?  The problem then will be that otherwise undifferentiated authors with descriptions will _never_ be auto-matched by imports. That may be desirable?

Currently this _can_ be achieved by adding the differentiated authors' dates.

If that is insufficient for some reason, alternatives can be proposed which address the specific usecase (i.e. a correctly disambiguated author for which dates are not available)

A concrete example makes a specific problem clear and points to specific requirements soooo much better than "Make stuff better"

Thank you for the example @seabelis

**Comment by seabelis** [comment]
@hornc In this case and in many others, there are no known dates to add. I can add a question mark in the date fields in such cases if that will help. 

I expect this will also be an issue, https://openlibrary.org/authors/OL14817364A/Ray_Bradbury. This is a common print-on-demand author problem. Famous author names are used precisely so that these works are included among the famous authors' works for visibility reasons.

**Comment by seabelis** [comment]
Here's a case where a new author profile should not have been created. https://openlibrary.org/authors/OL15017680A/Emily_Bront%C3%AB has the same spelling and years as https://openlibrary.org/authors/OL24529A/Emily_Bronte%CC%88, but was created new instead of matched to the existing.
