### ISSUE TITLE
Critical Tasks & Crons should log + alert when interrupted

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#10206]
### Now
- [ ] Monthly data dumps (see #6607 re: #9521)
- [ ] IA imports (e.g. #732, related to #5154)
- [ ] partner monthly dumps (https://github.com/internetarchive/openlibrary/blob/master/scripts/partner_batch_imports.py)
- [ ] promise item imports (https://github.com/internetarchive/openlibrary/blob/master/scripts/promise_batch_imports.py)
- [ ] resolving redirects (https://github.com/internetarchive/openlibrary/blob/master/scripts/update_stale_work_references.py)
- [ ] solr restarter (https://github.com/internetarchive/openlibrary/blob/4bc59c8306a0417218c7516672cd6b50a6277e1f/scripts/solr_restarter/index.js)

### Later

- [ ] web logs
- [ ] cover archival
- [ ] solr updater

### Problem: What problem does this proposal address & for what audience(s)?
Today, when crons or other critical tasks fail, we are often learning about it from patrons rather than workflows.

### Impact: What's the predicted impact, how do we measure, & what does success look like?
Some of our biggest sources of value (bots that clean things up for us, like solr restarter or the bot to fix redirects) potentially don't run for weeks on end if broken.

### Breakdown

- Know that the cron / dump / service started (or was triggered)
- We want to be alerted that cron / dumps failed or succeeded
- Historical view of how often failures occur (stats.inc?)
- Look back at how often restarts attempted / failed

#### Requirements Checklist

* [ ] We should be able to query over time any errors for a cron or service using statsd e.g. https://graphite.us.archive.org/render?
* [ ] We should either be pinged via slack on abc-plus when a cron job fails (or potentially create an issue for us, but let's start with slack)

**Comment by PredictiveManish** [comment]
Is this a bunch of problems together or any big project?

**Comment by mekarpeles** [comment]
Hi @PredictiveManish this is marked as `Needs: Staff/Internal` meaning its for staff and its also marked as `Type: Epic` 

https://github.com/internetarchive/openlibrary/wiki#labeling-issues

**Comment by PredictiveManish** [comment]
> Hi @PredictiveManish this is marked as `Needs: Staff/Internal` meaning its for staff and its also marked as `Type: Epic`
> 
> https://github.com/internetarchive/openlibrary/wiki#labeling-issues

Sorry for disturbance, I was just curious to learn about the Idea.

**Comment by mekarpeles** [comment]
We do seemingly instantiate sentry for `sentry_cron_jobs` (though it doesn't seem as if integration is working) so maybe that's an approach

**Comment by mekarpeles** [comment]
This command on `ol-home0` seems to be doing a good job of detecting errors as we hit them
```
docker logs --tail=20000 openlibrary-cron-jobs-1 2>&1 | grep -iE "traceback|error|exception|raise|infogami|sentry|\^" -B3 -A3 | grep -vE "INFO|DEBUG|openlibrary\.dump"
```

**Comment by mekarpeles** [comment]
I believe this may help fix our resolve redirects cron https://github.com/internetarchive/olsystem/pull/251

**Comment by mekarpeles** [comment]
Can we check whether crons are running **both** from `ol-home0` VM and also on its `openlibrary-cron-jobs-1` container?

**Comment by mekarpeles** [comment]
There are the remaining steps for our `cron_wrapper.py`:

1. dns -> dsn (in the sdk and config)
2. `traces_` plural kwarg for sdk init
3. chmod +x /openlibrary/scripts/update_stale_work_references.py for anything cron_watcher.py runs
4. add `#!/usr/bin/env python3` to such scripts
5. remove cron_watcher actions
6. merge our PR

**Comment by mekarpeles** [comment]
This issue may be closed as @jimchamp implemented the cron wrapper with sentry integration, a huge win. The next step is a followup to get more of our crons wrapped with this class.
