### ISSUE TITLE
Importing Reading Levels (bulk)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#10228]
# Game Plan

This issue is for Jordan who will be leading this effort.

* [x] Identify source(s) of normalized reading levels with good coverage over thousands of books
  - Lexile and Mid-Columbia Libraries
* [x] write a reproducible mechanism to fetch this data and marshal it to some machine readable format like json
* [x] write a reproducible script to overlap this data with records on Open Library (by ISBN)
* [x] reach consensus about a schema for adding grade level to Open Library works
  - historically, we've used subject tags, as these are already in solr)
* [x] create a [batch import](https://openlibrary.org/import/batch/new) with @scottbarnes to augment existing Open Library records w/ reading level data
* [x] @cdrini  to update solr to add reading levels
* [ ] improve the https://openlibrary.org/k-12 page to make use these reading levels

See project specifics:
https://docs.google.com/document/d/1LOvCsEPV4_b1-TUbfYS66AvRwSFhE-WV9GBopPU_hyA/edit?tab=t.0#heading=h.wmyb7lqeujv

### Justification

Today it's difficult to find age/skill appropriate books for k-12 students (and their parents). We have a limited collection of works with associated reading levels. 

k-12 is one of our most popular collection pages on Open Library

**Comment by mekarpeles** [comment]
@cdrini @hornc @scottbarnes @seabelis 

It would be great it y'all could take a very quick look at this and make sure the logic seems okay  https://colab.research.google.com/drive/1c33qKZNPhhtsKHhxO6N5dzGy9Nm_GksE#scrollTo=g8rf1Tsw_Iug

Example import:
https://openlibrary.org/books/OL28811060M.json?v=12

Also, should we put `lexile` reading level on edition and/or work?

**Comment by scottbarnes** [comment]
I think this looks good.

Is there a principle that defines when something should be on a `Work`, and `Edition`, or both?

My initial inclination was that a reading level was some immutable characteristic of the thing-it-is, so that would argue for reading levels going on the `Work`.

But then I thought about abridged works, which we I think we treat as `Editions`, which I imagine could have different reading levels from the original `Work`. If that's correct, maybe the `Edition` is the right place?

A quick search for the word 'abridged' turned up this edition of _Pollyanana_ "abridged for young readers": https://openlibrary.org/works/OL2775807W/Pollyanna?edition=key%3A/books/OL25572601M.

**Comment by mekarpeles** [comment]
After some thought, I think maybe the Edition because each version [e.g. abridgments], as you note, may be quite different.

One can search for works based on lexile scores on their editions so for this reason I think it makes most sense; whereas subjects likely apply to all the editions.

**Comment by mheiman** [comment]
From a librarian point of view, if a text has diverged enough from the original that it has a different reading level, we'd regard that as a different work.  Abridgements, which simply remove some of the text, are different from adaptations, which alter the original author's words.

**Comment by mekarpeles** [comment]
I believe the 11k records finished importing last night 🎉 

At this stage, we don't yet have a way to utilize these reading level values on the platform, other than perhaps to render them on the books page (unless someone wants to download the data dump and then find a way to use the data).

The remaining steps are:
1. Update our search code to index edition `lexile` fields and synthesize a work range
2. Update our k-12 collection to use these lexile ranges in our carousels.

Regarding step 1:
- These items can be iterated from:
https://openlibrary.org/query.json?type=/type/edition&lexile~=*&limit=1000
to https://openlibrary.org/query.json?type=/type/edition&lexile~=*&limit=1000&offset=11000

**Comment by mekarpeles** [comment]
As of #10573, I think we can consider this done -- the next step could be importing covers and reading levels for items w/o `ocaid`.
