### ISSUE TITLE
Manage components CSS in separate style files and remove legacy.less

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1092]
The frontend needs some love and there's a lot of work to do, so I'm looking for helpers with a divide and conquer approach to refactoring (divide master.less into multiple files and then divide those new files up to conquer the problem).

We will start by combing through static/css/master.less and identifying components that will live in the components folder. This will help us defined reuse patterns and redundancy. 

A component for the time being, can be classed as any element which has a class or ID. This is not how we should think of components long term but it's good to use common language and this will hopefully give us some momentum to clean things up!

A component can be considered ported if the following is true:
- [ ] There is a file static/css/components/<name>.less which matches the top level selector that groups all styles relating to a component.
- [ ] Any media queries have either been moved to the static/css/components/desktop/<name>.less or static/css/components/tablet/<name>.less
- [ ] any other media queries should be placed at the bottom of static/css/components/<name>.less
- [ ] Any CSS selectors which contain a tag name and a class and are nested inside a component have been reduced to the class name. e.g. .foo ul.navigation-component becomes .foo .navigation-component, however the unnested ol.form should remain ol.form
- [ ] All CSS in the LESS file is nested under single top level selectors. (see code below)
- [ ] The component is included via relevant  import statements in the master.less file
- [ ] The top of the component file describes the component and provides the path to the template where the style is defined.
- [] The component is listed in https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library

### Acceptance criteria

- [ ] legacy.less is empty or contains CSS styles that we will not need when all pages are ported to v2.

### Post task completion
* We'll setup new tasks relating to further refactoring of individual components. For instance this exercise may generate large component files that themselves contain other components that should not be tied to them (and are possibly overly specific CSS selectors.
* We will be able to identify components that are tied to certain pages. We will aim to load the styles for those components only on the pages they are needed.

**Comment by guyjeangilles** [comment]
It looks like progress on this has slowed/stalled. Is there anything blocking progress?

**Comment by jdlrobson** [comment]
I'll close this and make something more specific. This is an outdated epic.
