### ISSUE TITLE
Replace all mentions of vagrant with docker

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#1134]
Make docker the one and only development option. There should be (virtually) no trace of vagrant left.

< Following added by @jdlrobson >
Files that reference Vagrant:
- [ ] [conf/nginx/sites-available/openlibrary.conf](https://github.com/internetarchive/openlibrary/tree/master/conf/nginx/sites-available/openlibrary.conf)
- [ ] [openlibrary/plugins/upstream/account.py](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/plugins/upstream/account.py)
- [ ] [provisioning/playbook.yml](https://github.com/internetarchive/openlibrary/tree/master/provisioning/playbook.yml)
- [x] (PR: #1803) [conf/init/ol-infobase.service](https://github.com/internetarchive/openlibrary/tree/master/conf/init/ol-infobase.service)
- [x] (PR: #1803) [conf/init/ol-web.service](https://github.com/internetarchive/openlibrary/tree/master/conf/init/ol-web.service)
- [x] (PR: #1803) [conf/init/ol-solr-updater.service](https://github.com/internetarchive/openlibrary/tree/master/conf/init/ol-solr-updater.service)
- [x] (PR: #1803) [scripts/bootstrap.sh](https://github.com/internetarchive/openlibrary/tree/master/scripts/bootstrap.sh)
- [x] (PR: #1803) [scripts/ol-start.sh](https://github.com/internetarchive/openlibrary/tree/master/scripts/ol-start.sh)
- [x] (PR: #1802) [docker/Dockerfile.oldev](https://github.com/internetarchive/openlibrary/tree/master/docker/Dockerfile.oldev)
- [x] (PR: #1751) [docker/README.md](https://github.com/internetarchive/openlibrary/tree/master/docker/README.md)
- [x] (PR: #1802) [scripts/dev-instance/create-dev-db-pgdump.sh](https://github.com/internetarchive/openlibrary/tree/master/scripts/dev-instance/create-dev-db-pgdump.sh)
- [x] (PR: #1802) [scripts/dev-instance/dev_db.pg_dump](https://github.com/internetarchive/openlibrary/tree/master/scripts/dev-instance/dev_db.pg_dump)
- [x] (PR: #1804) [.dockerignore](https://github.com/internetarchive/openlibrary/tree/master/.dockerignore)
- [x] (PR: #1804) [.gitignore](https://github.com/internetarchive/openlibrary/tree/master/.gitignore)

Wiki pages that reference Vagrant:
- [x] [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing)
- [x] [Getting-Started](https://github.com/internetarchive/openlibrary/wiki/Getting-Started)
- [x] [_Sidebar](https://github.com/internetarchive/openlibrary/wiki/_Sidebar)
- [x] ~[Google-Summer-Of-Code-2018(Plan)](https://github.com/internetarchive/openlibrary/wiki/Google-Summer-Of-Code-2018(Plan))~ (no change needed)
- [x] ~[Open-Library-Community-Call-Minutes](https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes)~ (no change needed)
- [x] ~[Google-Summer-of-Code-(2018)](https://github.com/internetarchive/openlibrary/wiki/Google-Summer-of-Code-(2018))~ (no change needed)
- [x] ~[Open-Library-Community-Call-Minutes](https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes)~ (no change needed)

**Comment by tabshaikh** [comment]
@cdrini you sounded like a vagrant killer there 😂

**Comment by jdlrobson** [comment]
This looks resolved to me!

**Comment by jdlrobson** [comment]
@cdrini I've listed all the files above. Don't know enough about the config to know which can be deleted, but openlibrary/plugins/upstream/account.py is a doc change and the lines in gitignore and dockerignore can be removed.

**Comment by cdrini** [comment]
Thanks @jdlrobson ! I converted it to a checklist; we can target chunks of these at a time, and close the ticket once they're all done.

**Comment by tfmorris** [comment]
I think we need to add some wiki pages to the work list here: https://github.com/internetarchive/openlibrary/search?q=vagrant&type=Wikis

The Testing and Getting Started ones are probably most important.

**Comment by cdrini** [comment]
👍 Added to the list.

**Comment by tfmorris** [comment]
Thanks @cdrini ! The sidebar only referenced the switching from Vagrant topic, so I've checked it off the list.

**Comment by tfmorris** [comment]
I've fixed the remaining wiki pages, but the [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing) page seems pretty out of date with our current setup (and assumes things like access to private OL machines), so probably needs more work.

**Comment by mekarpeles** [comment]
Thanks @tfmorris!

**Comment by cdrini** [comment]
There are still some files in the repo that need updating.

**Comment by tfmorris** [comment]
@cdrini Thanks for reopening
@mekarpeles I'll close when the work is complete.

**Comment by mekarpeles** [comment]
#2720 #2721 #2722
