### ISSUE TITLE
Standardize Open Library's buttons

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1184]
According to #1181 we don't style our edit icon.
It should be a https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#buttonbtn rather than rely on the default browser styling.

That aside there is a much larger problem -  we have many ways of rendering a button. They come in all sorts of colors and it's not clear when and where  to use them and in some cases we probably shouldnt use them at all!

## Related efforts
- [ ] #10199
- [ ] #5831

## Sign off checklist
- [x] #9086
- [x] #9238
- [ ] One CSS base class name to rule them all! All buttons should use a class to show they are buttons and should use well documented modifiers to change their color
- [ ] it should be obvious which button to use for a given context.
- [ ] there should be less buttons. The status quo is confusing. Which is the most important button on the page?
- [ ] consider icons rather than colors  - if all buttons were the same color could an icon inside the button convey meaning more strongly?
- [ ] buttons with similar styles should be merged e.g. ButtonBtn, ButtonGeneric and Book "book-cta" as well as ".borrow-btn, .read-btn, .wait-btn, .unwait-btn"

# Impacted buttons (feel free to add others you find)

- [ ] search button on subject page
- [ ] Edit button 
- [ ] Log in button on /account/login page
- [ ] Sign up button on /account/create page
- [ ] "Browse..." button on /account/import page
- [ ] "Save" button on book edit pages
- [ ] "Search" button on /lists page
- [ ] "Search" button on \advancedsearch page
- [ ] "Add" button on /books/add page

**Comment by Num170R** [comment]
I can work on this! Would you mind assigning me?

**Comment by jdlrobson** [comment]
Done!

**Comment by Num170R** [comment]
According to the description and #1158  is that we'd like to achieve?

![edit-btn](https://user-images.githubusercontent.com/9248823/46134588-ea0f3100-c24b-11e8-9aba-47fb1f1aaa35.png)

**Comment by jdlrobson** [comment]
Provided @mekarpeles is okay yes. I think all buttons should be of that style going forward - either blue (primary) or white. Given this is a primary action, blue is appropriate.

sure to remove any other styles the button has that are not related.

**Comment by mekarpeles** [comment]
@jdlrobson @Num170R  `Edit` has traditionally been a `ButtonSearch` as opposed to `ButtonBtn`. 

I'm weary of overloading `ButtonBorrow` / `ButtonBtn` (which should probably be merged) which represents a primary call to action.

I'm not opposed to us changing button colors, especially if we can achieve greater consistency, but as a first pass, I'd prefer us restore previous functionality and then discuss as community call topic.

Is everyone ammenable to that? If so @Num170R, I think "Edit", "Save", "Signup" etc should be the style which is currently called `ButtonSearch` -- maybe it should be called `ButtonSubmit` (other name suggestions welcome)

**Comment by mekarpeles** [comment]
Similarly, and hopefully not overloading this ticket, but I believe `ButtonGeneric` is/was only used for the main website header "Sign Up" button
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#buttongeneric

Again, I'm very open to this button changing, though the current `ButtonBtn` doesn't quite look balanced as is and my preference would be for us to use the original style until we've had a chance to discuss an alternate style on staging :)

**Comment by guyjeangilles** [comment]
Since this issue was retitled, it really should be an epic. Assigning jdlrobson (not tagging as requested) per slack discussions

**Comment by QuangPhung15** [comment]
Hi @mekarpeles. I'm Quang, a member of the Dickinson Seminar Group, which consists of five members. We are interested in contributing to this fellowship issue, as it would help us learn more about OpenLibrary and build a solid foundation to start tackling other issues. However, we're fairly new to this, so could you provide some guidance or suggestions on where we should start? Any specific parts of OpenLibrary that we could focus on to build our knowledge would be very helpful. I'm looking forward to hearing from you soon. Thank you so much!

**Comment by mekarpeles** [comment]
Hi @QuangPhung15! I think the first step would be doing an inventory of the website and seeing where there are buttons that disagree with our provisional button designs here:
https://www.figma.com/design/dYQkIJOJeMo9hx7ewZQH9x/Open-Library%3A-Design-System-%26-Component-Library?node-id=601-199&node-type=frame&t=mFg7L3g8A1LFntIa-0

Jasmine, from our design community, did something similar here: https://arc.net/e/344926EC-4F65-486A-99E9-E1408087E2BA

Going through that enumeration of buttons, you may be able to ask more specific questions or make proposals on how we might continue in order to make the site more consistent.

Here are a few which jump out to me...

The following should all use our secondary button styling, e.g.
<img width="195" alt="Screenshot 2024-11-20 at 12 11 00 AM" src="https://github.com/user-attachments/assets/5f248b8b-9ac9-4fcd-85ac-5607a9c836a9">


* <img width="100" alt="Screenshot 2024-11-20 at 12 08 25 AM" src="https://github.com/user-attachments/assets/91107721-c203-4972-9204-19d7be0fb6fe">
* <img width="100" alt="Screenshot 2024-11-20 at 12 08 36 AM" src="https://github.com/user-attachments/assets/e19be356-1b9a-4100-82a9-ee8733d8c406">
* <img width="100" alt="Screenshot 2024-11-20 at 12 08 59 AM" src="https://github.com/user-attachments/assets/2656145b-e0e0-4bae-8ac4-99da1a21ff78">

**Comment by prasad14070** [comment]
Hello @mekarpeles I am intrested to contribute on this project, i would like to do some value addition , can I work on some issues we can discuss it.

**Comment by mekarpeles** [comment]
I think this issue is too inspecific to be useful and am going to close. We can re-open with a more specific outcome, such as the one detailed here:
https://github.com/internetarchive/openlibrary/issues/1184#issuecomment-2487838528
