### ISSUE TITLE
Get rid of jCarousel and use slick carousel for carousel components

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1192]
We have 2 types of carousel - the [slick carousel](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#carousel) and the [resultsCovers carousel](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#resultcovers) made using jCarousel.

I assume jCarousel predates the slick carousels which are shown on the homepage, and suspect the latter is the preferred type going forward, so let's migrate the other jCarousel components to  use this.

### Blockers
I see references to jCarousel in the following files:
- [ ]  openlibrary/templates/borrow/index.html (#1555)
- [ ]  openlibrary/templates/borrow/read.html (#1555)
- [ ] openlibrary/templates/languages/view.html (#1576)
- [ ]  openlibrary/templates/publishers/view.html (#1554)

### Acceptance criteria
- [ ] All references to jcarousel in templates is gone
- [ ] The resultsCover component is removed
- [ ] References to jcarousel-skin-OL in legacy.less and page-form entry point are removed
- [ ] jcarousel code is removed from vendor folder
- [ ] static/js/vendor.jsh no longer includes the jcarousel code
