### ISSUE TITLE
17 undefined names on Python 2.7

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1684]
This is a continuation of #1508 which was autoclosed by a partial solution.  In our Travis CI builds the __make lint__ command is still finding _undefined names_ https://travis-ci.org/internetarchive/openlibrary/jobs/464190432#L504).  Please see #1508 for best practices to be used when fixing these issues which are often, but not always a sign of dead code, missing imports, typos, or incomplete reactoring.  Please __solve just a few in each pull request__.

Here they are listed (the links might be slightly outdated):

- [ ] [./openlibrary/catalog/get_ia.py:249:17:](../blob/master/openlibrary/catalog/get_ia.py#L249) `rc` in `marc_path = rc.get('marc_path')`
- [ ] [./openlibrary/catalog/ia/scan_img.py:103:9:](../blob/master/openlibrary/catalog/ia/scan_img.py#L103) `bad_hosts` in `bad_hosts.add(ia_host)`
- [ ] [./openlibrary/catalog/ia/scan_img.py:71:9:](../blob/master/openlibrary/catalog/ia/scan_img.py#L71) `bad_hosts` in `bad_hosts.add(ia_host)`
- [ ] [./openlibrary/catalog/importer/load.py:170:17:](../blob/master/openlibrary/catalog/importer/load.py#L170) `get_versions` in `return bool(get_versions({'machine_comment': loc}))`
- [ ] [./openlibrary/catalog/importer/load_scribe.py:300:18:](../blob/master/openlibrary/catalog/importer/load_scribe.py#L300) `state_file` in `start = open(state_file).readline()[:-1]`
- [ ] [./openlibrary/catalog/importer/load_scribe.py:499:42:](../blob/master/openlibrary/catalog/importer/load_scribe.py#L499) `state_file` in `print(row.updated, file=open(state_file, 'w'))`
- [ ] [./openlibrary/catalog/importer/load_scribe.py:508:32:](../blob/master/openlibrary/catalog/importer/load_scribe.py#L508) `state_file` in `print(start, file=open(state_file, 'w'))`
- [ ] [./openlibrary/catalog/load.py:40:12:](../blob/master/openlibrary/catalog/load.py#L40) `east_in_by_statement` in `east = east_in_by_statement(rec)`
- [ ] [./openlibrary/catalog/load.py:46:24:](../blob/master/openlibrary/catalog/load.py#L46) `import_author` in `book[k] = [import_author(v[0], eastern=east)]`
- [ ] [./openlibrary/catalog/load.py:66:18:](../blob/master/openlibrary/catalog/load.py#L66) `site` in `elif not site.things({'key': lang_key, 'type': '/type/language'}):`
- [ ] [./openlibrary/catalog/people/from_works.py:70:13:](../blob/master/openlibrary/catalog/people/from_works.py#L70) `ol` in `w = ol.get(work['key'])`
- [ ] [./openlibrary/catalog/people/from_works.py:96:19:](../blob/master/openlibrary/catalog/people/from_works.py#L96) `ol` in `print(ol.save(full_key.encode('utf-8'), obj_for_db, 'create a new person page'))`
- [ ] [./openlibrary/catalog/people/from_works.py:99:15:](../blob/master/openlibrary/catalog/people/from_works.py#L99) `ol` in `print(ol.save(w['key'], w, 'add links to people that this work is about'))`
- [ ] [./openlibrary/catalog/works/by_author.py:109:12:](../blob/master/openlibrary/catalog/works/by_author.py#L109) `has_dot` in `if has_dot(title):`
- [ ] [./openlibrary/catalog/works/by_author.py:81:24:](../blob/master/openlibrary/catalog/works/by_author.py#L81) `marc` in `if e['key'] not in marc:`
- [ ] [./openlibrary/catalog/works/by_author.py:85:12:](../blob/master/openlibrary/catalog/works/by_author.py#L85) `marc` in `data = marc[e['key']][1]`
- [ ] [./openlibrary/catalog/works/tests.py:129:35:](../blob/master/openlibrary/catalog/works/tests.py#L129) `rev_wt` in `title = freq_dict_top(rev_wt[n])`
- [ ] [./openlibrary/utils/bulkimport.py:133:24:](../blob/master/openlibrary/utils/bulkimport.py#L133) `doc` in `print(repr(doc))` Fixed in #3065.
- [x] [./openlibrary/plugins/search/solr_client.py:207:17:](../blob/master/openlibrary/plugins/search/solr_client.py#L207) `search` in `s = search(self, query, start=loc)` Fixed in #3059.
- [x] [./openlibrary/tests/core/mocklib.py:52:25:](../blob/master/openlibrary/tests/core/mocklib.py#L52) `urllib2` in `monkeypatch.setattr(urllib2, "urlopen", urlopen)` Fixed in #3060.
- [x] [./openlibrary/catalog/marc/db/web_marc_db.py:30:66](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/db/web_marc_db.py:30:66): `get_all_subfield` in `return ''.join("<b>$%s</b>%s" % (esc(k), esc(v)) for k, v in get_all_subfield)`
- [x] [./openlibrary/catalog/marc/db/web_marc_db.py:72:36](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/db/web_marc_db.py:72:36): `rc` in `works = find_others(this_isbn, rc['amazon_other_editions'])`
- [x] [./openlibrary/catalog/marc/db/web_marc_db.py:83:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/db/web_marc_db.py:83:16): `db_isbn` in `locs = db_isbn[isbn].split(' ') if isbn in db_isbn else []`
- [x] [./openlibrary/catalog/marc/db/web_marc_db.py:83:52](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/db/web_marc_db.py:83:52): `db_isbn` in `locs = db_isbn[isbn].split(' ') if isbn in db_isbn else []`
- [x] [./openlibrary/catalog/marc/fast_parse.py:329:17](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py:329:17): `read_short_title` in `'245': (read_short_title, 'title'),`
- [x] [./openlibrary/catalog/marc/fast_parse.py:444:37](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py:444:37): `read_full_title` in `edition['full_title'] = read_full_title(line, is_marc8=is_marc8)`
- [x] [./openlibrary/catalog/marc/tests/test_fast_parse.py:24:14](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/tests/test_fast_parse.py:24:14): `get_all_subfields` in `a = list(get_all_subfields(line))[0][1]`
- [x] [./openlibrary/catalog/wikipedia/process.py:274:14](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/wikipedia/process.py:274:14): `conn` in `id = conn.insert_id()`
- [x] [./openlibrary/catalog/wikipedia/tidy.py:269:14](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/wikipedia/tidy.py:269:14): `conn` in `id = conn.insert_id()`
- [x] [./openlibrary/plugins/oltemplates/olmanage.py:56:57](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py:56:57): `path` in `raise ValueError("Unrecognised path: {}".format(path))`
- [x] [./openlibrary/catalog/people/build_object.py:49:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/people/build_object.py:49:29): `marc` in `p = build_person_object(marc, [])`
- [x] [./openlibrary/catalog/people/build_object.py:53:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/people/build_object.py:53:29): `marc` in `p = build_person_object(marc, [])`
- [x] [./openlibrary/solr/inside/index_gevent.py:245:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/inside/index_gevent.py:245:16): `FindItemError` in `except FindItemError:`
- [x] [./scripts/lc_marc_update.py:46:12](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py:46:12): `no_bucket_error` in `if no_bucket_error not in body and internal_error not in body:`
- [x] [./scripts/lc_marc_update.py:46:44](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py:46:44): `internal_error` in `if no_bucket_error not in body and internal_error not in body:`
- [x] [./openlibrary/catalog/marc/html.py:44:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/html.py:44:16): `html_subfields` in `assert html_subfields(input) == output`
- [x] [./openlibrary/catalog/marc/html.py:55:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/html.py:55:16): `html_line` in `assert html_line(tag, input) == expect`
- [x] [./openlibrary/catalog/marc/marc_binary.py:197:17](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/marc_binary.py:197:17): `re_isbn` in `m = re_isbn.match(f.line[3:-1])`
- [x] [./openlibrary/tests/core/test_sponsors.py:69:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/core/test_sponsors.py:69:16): `mock_site` in `work = mock_site.quicksave("/works/OL1W", "/type/work", title="Foo")`
- [x] [./openlibrary/catalog/lc_updates/update.py:42:12](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/lc_updates/update.py:42:12): `no_bucket_error` in `if no_bucket_error not in body and internal_error not in body:`
- [x] [./openlibrary/catalog/lc_updates/update.py:42:44](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/lc_updates/update.py:42:44): `internal_error` in `if no_bucket_error not in body and internal_error not in body:`
- [x] [./openlibrary/catalog/improve/improve_data.py:17:11](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/improve/improve_data.py:17:11): `author_keys` in `print(author_keys)`
- [x] [./openlibrary/data/dump.py:138:13](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/data/dump.py:138:13): `pool` in `r = pool.map_async(f, tasks, callback=results.append)`
- [x] [./openlibrary/data/dump.py:138:47](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/data/dump.py:138:47): `results` in `r = pool.map_async(f, tasks, callback=results.append)`
- [x] [openlibrary/catalog/get_ia.py:1read73:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/get_ia.py#L173): `fast_parse` in `for data, int_length in fast_parse.read_file(f):`
- [x] [openlibrary/catalog/get_ia.py:230:14](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/get_ia.py#L230): `rc` in `f = open(rc['marc_path'] + '/' + file)`
- [x] [openlibrary/catalog/importer/load.py:168:17](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load.py#L168): `get_versions` in `return bool(get_versions({'machine_comment': loc}))`
- [x] [openlibrary/catalog/marc/fast_parse.py:122:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py#L122): `v` in `if not accept_sound and v.lower().startswith("[sound"):`
- [x] [openlibrary/catalog/marc/fast_parse.py:124:44](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py#L124): `v` in `if v.lower().startswith("[graphic") or v.lower().startswith("[cartographic"):`
- [x] [openlibrary/catalog/marc/fast_parse.py:124:8](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py#L124): `v` in `if v.lower().startswith("[graphic") or v.lower().startswith("[cartographic"):`
- [x] [openlibrary/catalog/merge/merge.py:28:14](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py#L28): `merge` in `amazon = merge.build_titles(full_title(edition))`
- [x] [openlibrary/catalog/merge/merge.py:30:22](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py#L30): `editon` in `amazon['isbn'] = editon['isbn_10']`
- [x] [openlibrary/catalog/merge/merge.py:32:34](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py#L32): `merge` in `amazon['publish_date'] = merge.amazon_year(edition['publish_date'])`
- [x] [openlibrary/coverstore/disk.py:206:20](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/disk.py#L206): `self` in `itemname = self.get_item_name(filename)`
- [x] [openlibrary/coverstore/disk.py:207:15](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/disk.py#L207): `self` in `url = self.item_url(itemname) + '/' + filename`
- [x] [openlibrary/coverstore/tests/test_coverstore.py:22:35](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_coverstore.py#L22): `static_dir` in `yield _test_write_image, 'a', static_dir + '/images/ajaxImage.jpg'`
- [x] [openlibrary/coverstore/tests/test_coverstore.py:23:35](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_coverstore.py#L23): `static_dir` in `yield _test_write_image, 'b', static_dir + '/logos/logo-en.gif'`
- [x] [openlibrary/coverstore/tests/test_coverstore.py:24:35](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_coverstore.py#L24): `static_dir` in `yield _test_write_image, 'c', static_dir + '/logos/logo-en.png'`
- [x] [openlibrary/coverstore/tests/test_coverstore.py:65:12](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_coverstore.py#L65): `static_dir` in `path = static_dir + "/logos/logo-en.png"`
- [x] [openlibrary/coverstore/tests/test_webapp.py:101:58](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L101): `static_dir` in `assert b.open('/b/olid/OL1M.jpg').read() == open(static_dir + '/logos/logo-en.png').read()`
- [x] [openlibrary/coverstore/tests/test_webapp.py:111:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L111): `app` in `assert app.request('/').status == "200 OK"`
- [x] [openlibrary/coverstore/tests/test_webapp.py:116:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L116): `static_dir` in `path = os.path.join(static_dir, 'logos/logo-en.png')`
- [x] [openlibrary/coverstore/tests/test_webapp.py:126:25](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L126): `static_dir` in `filedata = open(static_dir + '/logos/logo-en.png').read()`
- [x] [openlibrary/coverstore/tests/test_webapp.py:178:35](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L178): `static_dir` in `f.path = os.path.join(static_dir, f.filename)`
- [x] [openlibrary/coverstore/tests/test_webapp.py:44:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L44): `db` in `db.delete("log", where="1=1")`
- [x] [openlibrary/coverstore/tests/test_webapp.py:45:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L45): `db` in `db.delete('cover', where='1=1')`
- [x] [openlibrary/coverstore/tests/test_webapp.py:46:24](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L46): `app` in `self.browser = app.browser()`
- [x] [openlibrary/coverstore/tests/test_webapp.py:56:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L56): `static_dir` in `path = os.path.join(static_dir, path)`
- [x] [openlibrary/coverstore/tests/test_webapp.py:71:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L71): `static_dir` in `return os.path.join(static_dir, path)`
- [x] [openlibrary/coverstore/tests/test_webapp.py:76:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L76): `db` in `db.delete('cover', where='1=1')`
- [x] [openlibrary/coverstore/tests/test_webapp.py:79:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L79): `static_dir` in `path = static_dir + "/logos/logo-en.png"`
- [x] [openlibrary/coverstore/tests/test_webapp.py:98:58](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/tests/test_webapp.py#L98): `static_dir` in `assert b.open('/b/olid/OL1M.jpg').read() == open(static_dir + '/logos/logo-it.png').read()`
- [x] [openlibrary/plugins/upstream/acs4.py:176:31](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/acs4.py#L176): `o_to_meta_xml` in `meta_el = o_to_meta_xml(v)`
- [x] [openlibrary/plugins/upstream/acs4.py:561:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/acs4.py#L561): `o_to_meta_xml` in `return o_to_meta_xml(o)`
- [x] [openlibrary/solr/inside/index_all.py:118:50](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/inside/index_all.py#L118): `log` in `print(('thread started', host, ia), file=log)`
- [x] [openlibrary/solr/inside/index_all.py:119:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/inside/index_all.py#L119): `log` in `log.flush()`
- [x] [openlibrary/solr/inside/index_gevent.py:254:31](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/inside/index_gevent.py#L254): `solr_src_host` in `url = 'http://' + solr_src_host + '/solr/inside/select?wt=json&rows=10&q=ia:' + ia`
- [x] [openlibrary/catalog/amazon/read_serp.py:79:34](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/amazon/read_serp.py#L79): `out` in `print(asin, file=out)`f
- [x] [openlibrary/catalog/edition_merge/find_dups.py:15:13](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/find_dups.py#L15): `conn` in `local_cur = conn.cursor()`
- [x] [openlibrary/catalog/edition_merge/find_dups.py:19:15](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/find_dups.py#L19): `conn` in `archive_cur = conn.cursor()`
- [x] [openlibrary/catalog/edition_merge/find_dups.py:31:49](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/find_dups.py#L31): `cur` in `for num, (ia, updated, collection) in enumerate(cur.fetchall()):`
- [x] [openlibrary/catalog/importer/import_marc.py:360:27](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py#L360): `find_title_redirects` in `title_redirects = find_title_redirects(akey)`
- [x] [openlibrary/catalog/importer/import_marc.py:361:17](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py#L361): `find_works` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/import_marc.py:361:34](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py#L361): `get_books` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/import_marc.py:361:50](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py#L361): `books_query` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/import_marc.py:363:19](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py#L363): `update_works` in `updated = update_works(akey, works, do_updates=True)`
- [x] [openlibrary/catalog/importer/load_scribe.py:222:27](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load_scribe.py#L222): `find_title_redirects` in `title_redirects = find_title_redirects(akey)`
- [x] [openlibrary/catalog/importer/load_scribe.py:223:17](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load_scribe.py#L223): `find_works` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/load_scribe.py:223:34](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load_scribe.py#L223): `get_books` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/load_scribe.py:223:50](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load_scribe.py#L223): `books_query` in `works = find_works(akey, get_books(akey, books_query(akey)), existing=title_redirects)`
- [x] [openlibrary/catalog/importer/load_scribe.py:225:19](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load_scribe.py#L225): `update_works` in `updated = update_works(akey, works, do_updates=True)`
- [x] [openlibrary/catalog/marc/fast_parse.py:223:43](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/fast_parse.py#L223): `is_marc8` in `for k, v in get_subfields(line, want, is_marc8):`
- [x] [openlibrary/catalog/marc/marc_binary.py:133:31](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/marc_binary.py#L133): `line` in `m = re_isbn.match(line[3:-1])`
- [x] [openlibrary/catalog/marc/db/web_marc_db.py:69:13](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/db/web_marc_db.py#L69): `find_others` in `works = find_others(this_isbn, rc['amazon_other_editions'])`
- [x] [openlibrary/catalog/merge/merge.py:33:8](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py#L33): `authors` in `if authors:`
- [x] [openlibrary/catalog/merge/merge.py:34:29](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py#L34): `authors` in `amazon['authors'] = authors`
- [x] [openlibrary/catalog/merge/names.py:130:19](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/names.py#L130): `marc1_normalized` in `if m2 and marc1_normalized == normalize(m2.group(1)):`
- [x] [openlibrary/catalog/merge/names.py:135:12](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/names.py#L135): `marc2_normalized` in `if marc2_normalized == normalize(m1.group(1)):`
- [x] [openlibrary/catalog/merge/names.py:139:8](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/names.py#L139): `marc1_normalized` in `if marc1_normalized == normalize(m2.group(2) + ' ' + m2.group(1)) or marc2_normalized == normalize(m1.group(2) + ' ' + m1.group(1)):`
- [x] [openlibrary/catalog/merge/names.py:139:74](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/names.py#L139): `marc2_normalized` in `if marc1_normalized == normalize(m2.group(2) + ' ' + m2.group(1)) or marc2_normalized == normalize(m1.group(2) + ' ' + m1.group(1)):`
- [x] [openlibrary/catalog/scratch/add_source_records.py:39:27](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/scratch/add_source_records.py#L39): `out` in `print((key, sr), file=out)`
- [x] [openlibrary/catalog/works/find_work_for_edition.py:39:31](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/works/find_work_for_edition.py#L39): `e` in `wkey = find_matching_work(e)`
- [x] [openlibrary/core/vendors.py:169:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L169): `result` in `return result`
- [x] [openlibrary/data/sitemap.py:75:10](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/data/sitemap.py#L75): `doc` in `elif doc.type == '/type/author':`
- [x] [openlibrary/data/sitemap.py:79:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/data/sitemap.py#L79): `doc` in `return doc.key`
- [x] [openlibrary/mocks/mock_ol.py:49:28](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/mocks/mock_ol.py#L49): `pytest_funcarg__monkeypatch` in `self.monkeypatch = pytest_funcarg__monkeypatch(request)`
- [x] [openlibrary/mocks/mock_ol.py:50:21](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/mocks/mock_ol.py#L50): `pytest_funcarg__mock_site` in `self.site = pytest_funcarg__mock_site(request)`
- [x] [openlibrary/plugins/ol_infobase.py:355:19](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/ol_infobase.py#L355): `work` in `authors = work.get('authors', [])`
- [x] [openlibrary/plugins/books/tests/test_doctests.py:16:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/books/tests/test_doctests.py#L16): `py` in `py.test.fail("doctest failed: " + test.name)`
- [x] [openlibrary/plugins/oltemplates/olmanage.py:25:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py#L25): `error` in `error`
- [x] [openlibrary/plugins/oltemplates/olmanage.py:41:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py#L41): `error` in `error`
- [x] [openlibrary/plugins/oltemplates/olmanage.py:54:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py#L54): `error` in `error`
- [x] [openlibrary/plugins/oltemplates/olmanage.py:66:13](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py#L66): `error` in `error`
- [x] [openlibrary/plugins/oltemplates/olmanage.py:77:9](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/oltemplates/olmanage.py#L77): `error` in `error`
- [x] [openlibrary/plugins/openlibrary/code.py:401:20](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L401): `ed` in `if ed:`
- [x] [openlibrary/plugins/openlibrary/tests/test_ratingsapi.py:72:25](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/tests/test_ratingsapi.py#L72): `msg` in `assert 'success' in msg`
- [x] [openlibrary/plugins/upstream/utils.py:326:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/utils.py#L326): `get_history_v2` in `return get_history_v2(page)`
- [x] [openlibrary/plugins/upstream/utils.py:328:16](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/utils.py#L328): `get_history_v1` in `return get_history_v1(page)`
- [x] [scripts/lc_marc_update.py:146:23](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py#L146): `BadImport` in `raise BadImport`
- [x] [scripts/lc_marc_update.py:149:23](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py#L149): `BadImport` in `raise BadImport`
- [x] [scripts/lc_marc_update.py:155:27](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py#L155): `BadImport` in `raise BadImport`
- [x] [scripts/lc_marc_update.py:160:16](https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py#L160): `BadImport` in `except BadImport:`
- [x] [scripts/manage-imports.py:95:65](https://github.com/internetarchive/openlibrary/blob/master/scripts/manage-imports.py#L95): `ia_id` in `logger.error("%s is not found in the import queue", ia_id)`

**Comment by cclauss** [comment]
Down to 77: https://travis-ci.org/internetarchive/openlibrary/jobs/465187319#L504

**Comment by cdrini** [comment]
@cclauss put the list in here directly as a checklist so we can see progress. The generation is (annoyingly) manual, but hopefully still useful.

**Comment by cclauss** [comment]
Py more attention to the flake8 results on Python 3 runs than Python 2 runs because they have two different abstract syntax tree so they kick out different undefined names like unicode, basestring, raw_input, etc. on Python 3 runs.  Much but not all of that was cleared up on earlier PRs.

**Comment by cdrini** [comment]
Those will be a superset of the errors listed here, correct?

**Comment by cdrini** [comment]
For simplicity, lets finish with these and keep the others in a separate issues as Python 3 syntax errors.

**Comment by guyjeangilles** [comment]
Assigning @cclauss since he's been doing the PRs

**Comment by cdrini** [comment]
@cclauss Regenerated the list here; it looks like there's been a decent amount of progress! There are only 43 undefined names left.

**Comment by cclauss** [comment]
Yes.  See the single file change in #2929

**Comment by cclauss** [comment]
#3054 makes a huge improvement and would drop us down to just [10 undefined names](https://travis-ci.org/internetarchive/openlibrary/jobs/651842223#L226) which are all covered in other single-file PRs or issues.
