### ISSUE TITLE
Enhancements for Reading Log

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2059]
- [ ] #2016 "Stopped Reading"
- [ ] Add "Finished-Reading" Date
- [ ] Add "Notes" field
- [ ] Add bookmark/page to "Currently Reading" or "stopped reading"

**Comment by ralvessa** [comment]
I'd really like to be able to set the started and finished reading dates for books on my reading log.

**Comment by tfmorris** [comment]
@ralvessa We already had a "Add 'Finished-Reading' date" on the enhancement list, but I've extended it to include started reading as well. I suspect we might have this date stored internally, but we don't expose it. It also might be desirable to allow the user to set it independently from the implicit date of when it was added to the "Currently Reading" list.

**Comment by ralvessa** [comment]
> @ralvessa We already had a "Add 'Finished-Reading' date" on the enhancement list, but I've extended it to include started reading as well. I suspect we might have this date stored internally, but we don't expose it. It also might be desirable to allow the user to set it independently from the implicit date of when it was added to the "Currently Reading" list.

I agree that the user should be able to manually edit the started reading date regardless of whether it is set automatically or not. It could, however, default to the date the book is added to the 'Currently Reading' log.

**Comment by ralvessa** [comment]
We should also consider adding multiple pairs of started-finished dates, as users might re-read the same book. I've started looking into the codebase to see if I can help with this one.

**Comment by guyjeangilles** [comment]
I've updated @mekarpeles breakdown to reflect @ralvessa comment. I'd say things issue is "broken down" and thus I've removed that label

**Comment by ralvessa** [comment]
Thanks, @guyjeangilles. I haven't had any time lately to look into this, but I'd still very much like to help with this one. I'm hoping to find some time at some point this month.

**Comment by guyjeangilles** [comment]
@ralvessa I'll assign you to this issue then
