### ISSUE TITLE
Add [Sponsor this eBook] button 

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2162]
Adding **Sponsor this eBook** button to Books Page, Search Results Page and Works Editions table(where there is no ebook available)

The design to be tried for the button is below:
![Screenshot from 2019-05-31 13-38-50](https://user-images.githubusercontent.com/31198893/58691441-98561200-83a9-11e9-8a41-047ad5a18b4f.png)

**Update**: The design after viewing on dev does not look like a clickable button - @mekarpeles @jdlrobson (would need your feedback on this) 

This involves the following steps:
- [x] Implement the decided designs as shown above. 
- [ ] Testing, getting feedback, merging of pr. 
- [x] Coming up with alternative designs which would be used in A/B testing of these components and getting feedback on these.

**Comment by tabshaikh** [comment]
Some other designs for the Sponsorship button by Jim Shelton
![image](https://user-images.githubusercontent.com/31198893/59853078-c8337c80-938d-11e9-9e30-928b058033be.png)

**Comment by tabshaikh** [comment]
@tabshaikh Adding button is left on search and work editions table
