### ISSUE TITLE
Book Sponsorship Design Flow

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2164]
The modal would open up once the user clicks `Sponsor this eBook` button and would include things like the `cost breakdown`, `terms and conditions`, etc. which needs to be still decided and designed before implementing them.

Items in this page would only be required to redesign and put into the modal:
![Screenshot from 2019-05-31 14-51-57](https://user-images.githubusercontent.com/31198893/58695676-a315a480-83b3-11e9-9897-1a3413326977.png)

Updated modal view: 
![Screenshot from 2019-06-05 22-16-08](https://user-images.githubusercontent.com/31198893/59153387-bd1b4b00-8a75-11e9-8704-53fc58fc87d9.png)

The subtasks which needed to be done are:
- [ ]  Finishing implementation of modal view with available OL modal view.
- [x]  For researching different modal designs and coming up with a design which we are proud of.
- [ ] Implementing the components which we originally thought for archive.org donation page
- [ ]  For testing, getting feedback, merging of pr.

**Comment by tabshaikh** [comment]
@bfalling could you add some more details if i have missed some :)

**Comment by tabshaikh** [comment]
After UX meeting the points decided are:

1. Brown modal too bulky (and should not be brown)
2. “What you’re paying for” itemized list needs to have bullets and be more clear
3. Show the user (somewhere on the modal) where they are in the process
4. Check-box for if the user wants to reserve the 1st borrow
5. Clearer check-box for if they want to sponsor anonymously
6. On modal, “Sponsor Ebook” should be called “Proceed to Checkout” + show payment options in advance (on modal)

**Comment by mekarpeles** [comment]
# Four Flows

## Archive.org Direct
https://www.figma.com/file/Oh1CZQOx5JZSzVIbSigbRy59/Book-Sponsorship-Modal?node-id=80%3A242
This flow adds copy/desc to Open Library editions page describing the program + price alongside the CTA button, which takes the patron directly to archive.org/donate which shows checkout page which prompts for sponsorship message and allows user the select  payment method (then proceeds to usual flow).

## Half-and-Half
https://www.figma.com/file/Oh1CZQOx5JZSzVIbSigbRy59/Book-Sponsorship-Modal?node-id=80%3A514
Patron goes to Open Library edition, clicks CTA1 which brings up a modal explaining program and asking for sponsorship message. User clicks CTA2 which brings patron to archive.org/donate which shows checkout/confirm details + select payment method + sponsorship message for review. User proceeds to usual checkout flow.

## Minimal
https://www.figma.com/file/Oh1CZQOx5JZSzVIbSigbRy59/Book-Sponsorship-Modal?node-id=0%3A1
Patron goes to Open Library edition, clicks CTA1 which brings up a Modal (1) which explains program and prompts for sponsorship message (one version [a] may show payment method while [b] does not). User clicks CTA2 which brings patron directly to a version of archive.org/donate which automatically triggers stripe modal 
- Challenge: In this case, users may be frustrated by the fact that they don’t get to choose their form of payment (many want to use paypal). We can solve this by showing [a] “payment options” in the form above.
 
## OpenLibrary.org Centric
https://www.figma.com/file/Oh1CZQOx5JZSzVIbSigbRy59/Book-Sponsorship-Modal?node-id=87%3A17
Patron goes to Open Library edition, clicks CTA1 which brings up a Modal (1) explaining program and asking for sponsorship message. Patron proceeds by clicks CTA2 which advances patron to OL Modal (2) which has a confirmation / review and offers payment options (stripe, paypal). Clicking CTA3 sends patron directly to a version of archive.org/donate which automatically triggers stripe modal.

**Comment by tabshaikh** [comment]
we have a *winner* for #books-sponsorship-g flow:
- it’s `Archive.org Direct` :tada:  (OpenLibrary.org edition button links direct to archive.org/donate?keys=vals)

The `OpenLibrary.org Minimal` was actually the *crowd favorite* and runner-up — this was an all-inclusive modal on OpenLibrary.org which used an iframe to feature a button directly to Paypal / Card (no Archive.org). It has been eliminated by a non-starter / logistic detail:

*Why can’t we use `Minimal`?*
The decision boiled down to two points:
1) Iframe `stripe` button wasn’t feasible because it invokes a modal popup which is cropped by the iframe (whereas paypal button does a POST / redirect)
2) We considered doing `paypal` *only* (because it does paypal + card) except iframe’d `paypal` actually can’t persist the values we need (sponsor message, isbn, context, transaction-type, first-borrow) across/through checkout… Because Paypal is wired against an immutable callback url (which doesn’t know anything about the values we want to persist — which is incidentally a reason we’re moving from Paypal to Braintree).

*Doesn’t this mean that Paypal is a non-starter for book-sponsorship?*
*Yes*. It does. For now, until braintree is integrated (we’re not going to wait for book-sponsorship pilot) we’ll only be accepting Stripe for our pilot.

**Comment by mekarpeles** [comment]
We've got this nailed down and merged into master-sponsorship!
