### ISSUE TITLE
 Instrument basic analytics tracking

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2165]
We would like to have analytics tracking on our buttons and a campaign/flow so that we can track where there's a drop-off at different parts of the conversion funnel. For instrumentation(ie. log button impressions and button clicking we could use navigator.sendBeacon and google analytics. 
A rough plan would be like:
 - [ ] Determining how we can instrument? We would want to send events somewhere when the button shows and when it's clicked... and various other stages. We would need a database. We can automate the process by using google analytics.  the navigator.sendBeacon is also useful which helps us if the http request to register the event doesn't finish.

Thinking about what we want to do and what success looks like?- That would be the impact of my project. Other questions that pop up are 
How many people click the sponsor book button?
How many of those people actually follow through
Do logged in users sponsor books? …, etc

Using the above questions would help us in determining the data of the instrumentation campaign we can collect and what can we infer from it.

Then
- [ ] Finalizing the campaign plan with the community.
- [ ] Reading about analytics tools such as google analytics, Optimizely, etc and determine the best tool for our purpose. 
- [ ] Implementing button click-tracking and essential data for conversion funnel analysis

**Comment by tabshaikh** [comment]
@mekarpeles After adding tracking on our button what would be the next step in this issue?

**Comment by tabshaikh** [comment]
@mekarpeles after adding tracking to the button do we want to do something more or this issue can be closed?

**Comment by tabshaikh** [comment]
I think this issue can be closed for now
