### ISSUE TITLE
Redirecting the users to archive.org/donate for payment

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2166]
How will we redirect to archive.org for payment? What URL endpoint + parameters?
Patrons are sent (via a `GET` param) to archive.org/donate which only shows checkout flow, giving user option of payment type

How can we tell which Open Library users have sponsored a book?
Presumably a privileged archive.org item with encrypted metadata?

Things needed to be done in this are:
- [x] Integrating the policy check API 
- [x] Research about stripe 
- [x] Payment processing - using stripe as on archive’s donation page
- [x] For testing, getting feedback, merging of pr.

**Comment by tabshaikh** [comment]
This can be close by pr #2221
