### ISSUE TITLE
View My Sponsored Books page

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2168]
## Is your feature request related to a problem? Please describe.

How does a patron keep track of the books they're sponsoring?

## Describe the solution you'd like

https://openlibrary.org/account UI will need to be edited to also show “Your Sponsored Books” *if* the user is in the sponsorship usergroup (edited) 

The URL we’ll probably want is: https://openlibrary.org/account/books/sponsorship
Which will show a list of books the user is sponsoring

## Proposal & Constraints

The results of this page page will need to come from either querying archive.org for a metadata key like `sponsorship` or using privileged access to the user's archive.org item via xauthn + s3. i.e. We'll rely on Archive.org to tell us what books a user have sponsored and then render them on openlibrary.org

# Subtasks
Adding details such as which books the user has sponsored on the accounts page. 
More discussion needs to be done about the contents, etc

- [x]  Propose page design in figma: #2196 
- [x] Change the url/endpoint to account/books/sponsorships: #2197 
- [x]  For testing, getting feedback, merging of pr
- [x] Wire up the modal to GET to account/books/sponsorships #2198
- [ ] Connect to data source. #2199

**Comment by tabshaikh** [comment]
For connecting to data source ie. civi we would need to change the code like the snippet below

e.g.
`core/sponsorships.py`
```import requests
CIVI_SPONSOR_API = 'http://localhost/account/civi'
def get_all_sponsors():
    """
    Query civi for a list of all sponsorships, for all users.
    These results will have to be summed by user for the
    leader-board and then cached
    """
    pass  # todo, later
def get_sponsored_editions(archive_username, limit=50, offset=0):
    """
    Gets a list of books from the civi API which internet archive 
    @archive_username has sponsored
    """
    return requests.get(CIVI_SPONSOR_API + '?username=%s' % archive_username).json()```

 In `plugins/upstream/account.py`
```from openlibrary.core.sponsorship import get_sponsored_editions
class fake_civi(delegate):
    def GET(self):
        i = web.input(username='')
        editions = get_sponsorshed_editions(i.username)
        return delegate.Raw(editions, "content: application/json")```

**Comment by tabshaikh** [comment]
This issue is being closed by pr #2216

**Comment by tabshaikh** [comment]
A different issue relating to connecting `My Sponsored Books` page to civi crm will be opened
