### ISSUE TITLE
Hacktoberfest 2019 Planning

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2411]
Hacktoberfest Project Board
https://github.com/internetarchive/openlibrary/projects/18

- [x] Tag all `first good issues` issues with `Hacktoberfest` label https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22
- [x] Write a small blog post describing where to find issues, what Hacktoberfest is, and where to register
- [x] Tweet out blog post
- [x]  Ask `#openlibrary-g` to help us prioritize Hacktoberfest issues (by theme? python3? modernize OL javascript). @tabshaikh asking @jdlrobson in #openlibrary-g for advice on which modern ol js issues would be good for Hacktoberfest? Improving mobile experience
- [x] Modify iaux repo's code of conduct (for starters) @tabshaikh https://github.com/internetarchive/iaux/blob/master/CODE_OF_CONDUCT.md

**Comment by tabshaikh** [comment]
Closing as Hacktoberfest is over :)
