### ISSUE TITLE
Move JavaScript for list feature into webpack

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2468]
Inline script tags in the following templates relating to "list" feature need to be moved to webpack
- [x] openlibrary/templates/type/user/view.html (#5096)
- [x] openlibrary/templates/type/list/embed.html (#2495)
- [x] openlibrary/templates/type/work/view.html
- [x] openlibrary/templates/lists/widget.html (#6159)
- [ ] openlibrary/templates/type/list/view_body.html
- [ ] openlibrary/templates/lists/lists.html

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by guyjeangilles** [comment]
@jdlrobson Labeling this a work in progress. Let me know your thoughts

**Comment by jdlrobson** [comment]
FYI am not working on this so this is open to anyone who wants an interesting challenge :)

**Comment by kmcgonigle** [comment]
@jdlrobson and @mekarpeles I have opened a PR to address this subtask: `openlibrary/templates/type/list/view_body.html`

I tried to use a strategy similar to the updates I saw in related PR #4661; I can tackle refactoring `openlibrary/templates/lists/lists.html` once my initial PR/approach has been refined. Just let me know any feedback, changes. etc. Thank you!

cc: @DebbieSan

**Comment by jdlrobson** [comment]
Thanks @kmcgonigle this looks great! @mekarpeles I'm not set up with OpenLibrary right now locally, but would you be able to make sure this gets a review?

**Comment by kmcgonigle** [comment]
PR #7765 was merged in this week, resolving the JS refactoring task for this file: `openlibrary/templates/type/list/view_body.html`

I'll pick up the refactoring for this file next: `openlibrary/templates/lists/lists.html`

**Comment by kmcgonigle** [comment]
I just opened a PR to refactor the `lists.html` JS: https://github.com/internetarchive/openlibrary/pull/7888  🎉
