### ISSUE TITLE
Fix Stale Redirects/Backrefs (RedirectBot)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2552]
This spawns from https://github.com/internetarchive/openlibrary/issues/501 and relates to #805

### RedirectBot Phase 1 #2553
1. [x] Find where backrefs to `olid`s occur between types e.g. a list->?(redirect), edition->Work(redirect), edition(orphan)->Authors(redirect).
2. [x] Correct/enforce that there are no chains of redirects (probably unlikely) -- There are chains of redirects

3. [ ] Use dumps to replace any redirect `olid` with its target
     - [ ] Create a table of `[Key, ReferncesThisKey]` eg `[/works/OL1W, /authors/OL1A]`
     - [ ] Intersect that table with a table of all `type:redirect`
     - [ ] Use the resulting table is basically a: On this record, replace all occurrences of `KeyA` with `KeyB`
4. [ ] Fix ReadingLog + Ratings table to resolve redirect works to point to correct `target`
     - [ ] Intersect with table of redirects for work column (can ignored edition column for now)
     - [ ] Iterate through and make edits.

### RedirectBox Phase 3: Live
2. When a redirect is created, we should immediately update ReadingLog + Ratings
1. Whenever an edit results in a type switch to redirect, perform a batch edit (save_many?) to resolve back references

**Comment by hornc** [comment]
This lists part of this epic was raised in #501

**Comment by mekarpeles** [comment]
This should now be resolved.
