### ISSUE TITLE
Phase II of Book Sponsorship Epic: Full Automation & Corrections

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2566]
Followup of #659 

Create issues and a roadmap for the following (and update here)
- [x] Release @brad2014 blog post on OL blog w/ link to sponsorship
- [x] Add sponsorship dedication message to openlibrary edition pages #2567 solved by #2568
- [x] Fix collection strings to match the strings needed by SF Scanning center
- [ ] Implement automatic BWB purchase order; purchase books via partners (via real-time rolling purchase order + monthly invoices)

Third Phase:
- [x] Automate sending thank you emails
- [x] Civi data ferry v2 needs to be launched into production and we need to retroactively run this on our old civi book sponsorship donations
- [x] Send emails when sponsored book available for lending (piggyback waitlist email reminder?)
- [x] Add ocaid to sponsored openlibrary edition (to Open Library)

Punting:
- [ ] Fix ISBN clobbering (use extrameta.xml to ensure MARC fetch does not write back different isbn) -- no longer needed since isbn in identifier
- [ ] Enhance editions page template to save-back edition olid into https://openlibrary.org/sponsorship/books.yml if book eligible for sponsorship
- [ ] Finish sponsorship leader board (show how many books sponsored, show sponsored books) #2292 
- [ ] Email campaign w/ @tquinlan to inform our top 1000 Reading Log patrons
- [ ] Make sponsorship landing page more mobile compatible #2547
- [ ] Make the leaderboard for top sponsors #2169. #2292 is needs wrapping up

**Comment by tquinlan** [comment]
Wrong @tquinlan, I think...
