### ISSUE TITLE
Improving Search (No Dead Ends)

### ISSUE THREAD

**Issue by xayhewalo** [internetarchive/openlibrary#2728]
See previously: https://coda.io/d/Search-Planning-Notes_dO8sGM90quA/Epics-in-Progress_su1I2#_luBNR and now:

- [x] #3317 Upgrade to solr8 
     - [x] #789 Solr updater too slow (will be fixed by solr8 update)
- [ ] Index new fields: Counts (Reading Log, Lists, Stars), List membership, Do-We-Want-It, Partner collections
- [ ] #627, #3288, #3321, #715, #699 Search UI: Search across all types (fulltext, authors, subjects, lists, etc)
- [x] #4111 Case studies: make sure searches for popular things work
- [ ] Maybe: Fix non-English content searches (Might be #900 #2064 #448)

Out of scope for H1:

- [x] #870 #628 Solr-Updater error reporting, exceptions, & latency?
- [x] #487 Basic upkeep (solr errors)
- [ ] #900 #2064 #448 Editions (availability & language: by edition)
- [ ] #1896 #65 Fixing Subject results 
- [x] #178 Fixing Authors results
- [x] #2355 Subtitle search
- [ ] #2723 Improve lists search (ie put lists in solr)

### Stakeholders

@cdrini @mekarpeles

**Comment by mekarpeles** [comment]
I think the spirit of my original statement was, there are literally books that do already exist on Open Library which don't show up under any search results (not: what `types` should be searchable).

That doesn't diminish the usefulness of this issue, just a note.

**Comment by mekarpeles** [comment]
This issue from 2019 is priory 3 & needs breakdown, and doesn't have clear success/close criteria. Is this still a useful issue?

**Comment by mekarpeles** [comment]
closing as duplicate of #6377
