### ISSUE TITLE
Canonical Tags: Subjects to become 1st class objects in metamodel

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2819]
Subjects are currently treated as strings, with light normalization to coalesce similar strings, which limits our flexibility to do things like support aliases, multiple languages, metadata such as descriptions, links to Wikidata, etc.

### Proposal & Constraints

Subjects should be first class objects with a set of attributes including:
* key
* preferred label (one per language)
* description (one per language)
* aliases (multiple per language)
* external identifier(s) - Wikidata to start, perhaps others like FAST

#### Component Updates
* Change importer to look up using subject labels and aliases and return the subject key to be stored.
* Change subject display on works, etc pages to use preferred label in the user's preferred language
* Change subject page to include description and aliases as well as preferred label. Allow editing of these elements.
* Add multilingual label, alias, & description editing (ie for languages other than the current UI language)
* Add subject merge (for the inevitable duplicates which will occur)

### Additional context

Traditionally library cataloging standards have used pre-coordinated subjects like _"U.S. History -- World War II -- 1945"_ (made up, perhaps invalid, example) which we split apart into constituent elements during import, similar to [FAST](https://www.oclc.org/research/themes/data-science/fast.html). The working assumption is that we'll continue to do that, but just making the assumption explicit here.

**Comment by guyjeangilles** [comment]
@hornc I added your personal label as I thought it was relevant.

**Comment by LeadSongDog** [comment]
@tfmorris 
Just spitballing here, but as a transitional step, will we not need to have support for both the existing free-form and whatever structured form is chosen?

**Comment by tfmorris** [comment]
> will we not need to have support for both the existing free-form and whatever structured form is chosen?

No. My expectation is that we'll convert everything to structured form at once, but with perhaps imperfect resolution/merging of duplicates which will improve over time. ie we might have two different subjects with labels of "History" and "Histoire" but over time they'll get consolidated together into a single object (with redirects for the former merged subjects).

**Comment by LeadSongDog** [comment]
So then, what happens in the many cases where there's no structured form clearly equivalent to the old free-form? Do we have a catch-all?

**Comment by tfmorris** [comment]
There's no such case. See "everything" in my previous reply.

**Comment by cclauss** [comment]
Python 3:
```
web_1        | 2020-10-21 17:34:47 [89] [openlibrary.logger] [INFO] solr request: http://ol-solr0:8983/solr/select?wt=json&q=key%3A%22%2Fworks%2FOL81625W%22&start=0&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia
web_1        | Traceback (most recent call last):
web_1        |   File "/openlibrary/infogami/utils/template.py", line 144, in saferender
web_1        |     result = t(*a, **kw)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/template.py", line 969, in __call__
web_1        |     return BaseTemplate.__call__(self, *a, **kw)
web_1        |   File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/template.py", line 880, in __call__
web_1        |     return self.t(*a, **kw)
web_1        |   File "/openlibrary/openlibrary/templates/lists/widget.html", line 79, in __template__
web_1        |     $var page_lists = page_lists
web_1        |   File "/openlibrary/openlibrary/templates/lists/widget.html", line 71, in get_page_lists
web_1        |     $ user_lists = get_user_lists(seed_info)
web_1        |   File "/openlibrary/openlibrary/templates/lists/widget.html", line 71, in <listcomp>
web_1        |     $ user_lists = get_user_lists(seed_info)
web_1        |   File "/openlibrary/openlibrary/templates/lists/widget.html", line 58, in get_list_data
web_1        |     owner = list.get_owner()
web_1        |   File "/openlibrary/openlibrary/core/lists/model.py", line 298, in get_default_cover
web_1        |     cover_id = self._get_default_cover_id()
web_1        |   File "/openlibrary/openlibrary/core/cache.py", line 457, in func
web_1        |     value = f(*args, **kwargs)
web_1        |   File "/openlibrary/openlibrary/core/lists/model.py", line 291, in _get_default_cover_id
web_1        |     for s in self.get_seeds():
web_1        |   File "/openlibrary/openlibrary/core/lists/model.py", line 273, in get_seeds
web_1        |     seeds = [Seed(self, s) for s in self.seeds]
web_1        |   File "/openlibrary/openlibrary/core/lists/model.py", line 273, in <listcomp>
web_1        |     seeds = [Seed(self, s) for s in self.seeds]
web_1        |   File "/openlibrary/openlibrary/core/lists/model.py", line 326, in __init__
web_1        |     self.type = "subject"
web_1        | AttributeError: can't set attribute
```

**Comment by mekarpeles** [comment]
In 2023 our intention is to start the Canonical Tags project whose project kickoff & proposal is outlined here: https://docs.google.com/document/d/1zrZAXgk2GEZRWb0D8tsrgaPzX4KdXHVt1s6ZQ4wUHLI/edit#

## Details

1. At first, works will continue using existing `subjects` field to reference a list of strings of the form `subject_name` or `type:value`.
2. On `/subject` pages, the `subject_name` will be used to fetch a Tag from infobase (if such a tag exists).
3. This rich Tag will provider internationalization, related tags, and additional metadata which can be curated by librarians and used to also enrich the `/subject` page UI. 

I'm aware @tfmorris would prefer us moving directly to a system where, e.g., a work references a list of Tags (as opposed to strings). My interest is risk mitigating and turning this into a small integratable piece (similar to as @LeadSongDog describes) which can be rapidly prototyped and tested. Once we have confidence in the approach and the problem we're solving, we can invest more deeply in reconfiguring solr, updating all the works in infogami, and every piece of template + backend code which touches subjects, and all the additional clean up work which will eventually be required to make this switch. This is the direction I prefer, if I am going to be accountable for us successfully staffing + hitting milestones for this effort. We ultimately want the same outcome (switching from lists of strings to lists of 1st class Tag references). 

## Related issues:

- #7486 & #3233 -- enable bulk subject assignment & cleanup @mheiman 
- #1896 @cdrini 
- #65 -- Fix duplicated subjects @cdrini 
- [ ] Create new 1st class Tag type; e.g. `OL123T` (in prod + local)
- [ ] Formalize a Tag schema which supports i18n to add to our [schemata](https://github.com/internetarchive/openlibrary-client/tree/master/olclient/schemata) 
- [ ] Create mapper to resolve a Work.subject string → Tag document (if one exists)
- [ ] Enhance a subject page to fetch/use auxiliary Tag data (pilot K-12 collection)
- [ ] A human UI for editing Tags @jimchamp 
- [ ] Use subjects/tags to support #7416 @jimchamp

**Comment by tfmorris** [comment]
> I'm aware @tfmorris would prefer us moving directly to a system 

Since this is the first sign of progress I've seen and I wasn't aware that the design was happening in the back rooms, I can't really say. I've added the Google doc with the design/plan to my list to review. 

I will note, however, that a search for the terms MARC, BIBFRAME, FAST, LOD, Linked Data, Linked Open Data all turned up zero hits, so I'm a little concerned about interoperability with the Real World.

**Comment by mekarpeles** [comment]
Plan looks something like:
* [ ] Create new infogami Tag type <OL…T> (in prod + local dev environment) 
* [ ] Formalize schema for Tags
* [ ] Create mapper to resolve a Work.subject string → Tag document (if one exists)
*. [ ] Enhance subject page to use Tag data (pilot K-12 collection)

**Comment by tfmorris** [comment]
Subjects, Collections, Awards, and Censorship Warnings (e.g. NSFW) are all VERY different things. Attempting to smoosh them into a single schema creates unnecessary complexity and makes them more difficult to query.

- Collections are simple sets (unordered) or lists (ordered) which are manually curated or dynamically created using search criteria.
- Awards typically have a sponsoring organization and a date. They may be given to a contributor (author, illustrator, etc) or work.
- Censorship categories depend on the geographical & political regime as well as the age, gender, religion, etc of the viewer. They are probably very difficult to model.
- Subjects are very well developed and known in the library community. They are explicitly assigned by librarians in both MARC and BIBFRAME cataloging formats. Modern catalog records even include URLs for subjects which act as strong identifiers. Subjects are organized into taxonomic hierarchies giving them structure.

There's a vast trove of professionally curated subject assignments in the MARC library records which is currently greatly underutilized (e.g. no import of FAST URLs). The proposal makes no mention of how the MARC importer will be affected or how this interacts with BIBFRAME data which libraries are already trialing in production.

I also see no mention of how the existing subjects will be deduplicated and matched with the new Thing.Tag.Subject subjects. I'm worried that perhaps this is seen as an entirely manual process, which isn't scalable at all.

I expect this is a fait accompli which isn't open for community input, so I'll stop there.

**Comment by mekarpeles** [comment]
@tfmorris why do you presume fait accompli? We've had no less than 3 community calls on this topic + we're open to discussion here as well.

You're right, there are lots of data sources we can use to get data. One thing blocking importing is having a place to put data.

Open Library currently has works, editions, authors, lists, and several other types. These are all APIs to maintain. Today we have a system that works ~well for subjects in that:
* one can edit any work's subjects and it gets indexed in solr
* subjects can be any string
* subject pages are created dynamically based on subject membership

There are also deficiencies:
* a subject is just a string, lots of dupes
* subject pages encode very little data other than a string (and works/authors which subscribe to this string). This leads librarians to hand-code `/collections` pages`.

I feel you're right that collections, subjects, moderation, and subjects all have different schema. They could all be constructed as independent entities with their own functions, APIs, solr integrations, import pipelines, edit + display UIs. This seems like it could be difficult to maintain when really what's important is that each of these types has mutually consistent schema. I'm imagining they all "inherit" from type Tag and share a schema according to their sub `type` (e.g. subject, collection, moderation, award, etc). An important aspect to me, from an engineering & implementation perspective, is that they share the same infogami API and we're not creating more types than we need and creating more exposure than we can cover.

**Comment by mekarpeles** [comment]
Example generic `Tag` document could look something like:

```
{
  key: "/tag/OL1T",
  tag_type: "subject",
  tag_name: "fantasy",
  queries: [{
    "title": {"en": "Recent release"},
    "query": "...&sort=newest",
  }],
  exclusion: "title: ...",
  title: {
    "en": "Fantasy",
    "fr": "Fantaisie"
  },
  description: {
    "en": "..."
  }
  header_img: "https://media.istockphoto.com/id/1070683626/photo/magical-old-book-with-sparkles.jpg",
  children: ["/tag/OL2T", "/tag/OL33T"],
  neighbors: [],
  ... // additional schema related to tag_type
}
```

**Comment by mekarpeles** [comment]
I'll remain the lead for this issue but am going to mark @JaydenTeoh as the assignee as they've been making great progress (keep up the great work!)

**Comment by mekarpeles** [comment]
Related: #65

**Comment by mekarpeles** [comment]
Supplanted by #7904

**Comment by tfmorris** [comment]
In the case of duplicates most projects keep the oldest issue so that provenance, discussion, and age are preserved. This project seems to continually replace old, perfectly valid, with new issues. Why is that? Does someone's bonus depend on how long tickets have been open?

It looks like my assumption of "fait accompli" was accurate. No response to questions about how this relates to BIBFRAME, FAST, LCSH, Wikidata, MARC, or anything else in the real world. No response to comments in design document that was linked above. No attention being paid to centuries of library cataloging practice or the directions that the library community (the only source of high quality metadata for OL) is going.

For the record, my request for Subjects to become first class objects in OpenLibrary was **not** "completed" as the issue status seems to indicate, but instead roundly rejected. "Tags" may become useful some day and it may even be able to build Subjects as first class objects on top of them, but there is no plan or path which shows how (or even if) that is going to happen. I'm very disappointed.

**Comment by jimchamp** [comment]
The insults will surely help your case, Tom.

**Comment by mekarpeles** [comment]
@tfmorris, we simply have 2 issues that were similar, one was closed, one remains open, and both are linked together. Furthermore, a section was explicitly added to the planning doc in response to updates we're planning for October: https://docs.google.com/document/d/1zrZAXgk2GEZRWb0D8tsrgaPzX4KdXHVt1s6ZQ4wUHLI/edit#heading=h.o9utr3tyh8k. Furthermore, we have made progress on several elements of this plan through GSoC this year. As well as anyone who has been involved with the project for several years, you know we're a small team doing the best we can and sometimes an older issue gets closed instead of a newer one and it's not done out of malice but rather an attempt to get things organized so we can make forward progress towards efforts that I know you care about.

In response to your questions about BIBFRAME, FAST, LCSH, Wikidata, MARC -- we continue to import classifications for these sources and also intend to links to sources within Tag documents (e.g. "this Tag is a classification from LCCN and here is its number").

We simply haven't gotten to that step of fully defining what is included in a Tag document because there's a lot of opportunities for integrating pieces we have confidence will be required. Much of the schema we imagine may be impacted by #7833 as we are interviewer 15 learners and educators to understand what types of affordances they may want beyond what we have in our current subject pages.

We've had dozens of calls on this topic, spanning staff, design team, engineering, and librarians, and at least 10 different people have been involved in weighing in, as have you (to the best of my ability) over github. This is one of many issues and it would be nice if it were appreciated that we doing the best we're able, and also that it is hard to fully respond to the feedback folks have over github which is why we do weekly community calls which I've tried hard to include you in.

Yes, I'm not perfect and will continue to make mistakes. I understand how frustrating advising and contributing to Open Library must feel under these constraints. All I can do is continue to be open to collaborating to the best of my ability and it would be nice if we could achieve that with good will and the compassion of two contributors who both care deeply about the project and doing right by our patrons.
