### ISSUE TITLE
Provide beta UI for record merging

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2964]
### Summary of Requirements
- [x] GETing /libtools/merge?olids=OL1W,OL2W displays the beta merging UI
    - Used /works/merge instead
- [ ] UI will not merge works list backreferences (but allow the merge to continue for the other selected items)
- [ ] UI will not merge works if works are on reading logs (but will allow the merge to continue for the other selected items)
- [x] Should only be available to librarians
- [ ] Log to stats.ol.edits.action.merge-works when a merge occurs
- [x] There is a means of selecting items from the search page
- [ ] Batch edit is created for the merge, with action = merge-works
- [x] Pressing "Do merge" does a merge

### Relationships
- Part of #805
- Depends on #2963
