### ISSUE TITLE
Create a rough plan / breakdown for Record Merging

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2965]
### Summary of Requirements
- [x] A planning meeting with community to get feedback on rough approach
   - Notes: https://coda.io/d/Record-Merge_dKeUQC9f-cz/Planning-Notes_suZY7#_luj9l
- [x] A more in depth planning of specific issues, organized into milestones
  - https://coda.io/d/Record-Merge_dKeUQC9f-cz/Tasks_suFWA#Tasks_tuwLY/r5
- [x] Update https://github.com/internetarchive/openlibrary/issues/805 with details of the plan

### Relationships
- Part of #805

**Comment by cdrini** [comment]
Note: Some big questions came up about how undoing might need some thought, or else it will be impossible/difficult to right in a maintainable way, so some of the future phases might change (see the notebook).

**Comment by ollie-iterators** [comment]
I am wondering if this is completed because https://github.com/internetarchive/openlibrary/pull/6665: Librarian Merge Request Table was merged.

**Comment by cdrini** [comment]
This is a residual planning ticket; considering completed after #805.
