### ISSUE TITLE
Issues Related to Performance seen during lighthouse audit

### ISSUE THREAD

**Issue by supercontracts** [internetarchive/openlibrary#3227]
Lighthouse performance audit for different pages: 
Home Page: https://openlibrary.org/
Author Page: https://openlibrary.org/authors/OL18319A/Mark_Twain
Edition Page: https://openlibrary.org/books/OL27459710M/Holding_Up_the_Universe

|  | Desktop | Mobile |
| :---         |     :---:      |          ---: |
| Home page   | 58     | 62    |
| Author Page  | 80     | 87      |
| Edition Page  | 52     | 59      |

#### Homepage Desktop Performance Summary: 
![Screenshot from 2020-03-21 00-43-42](https://user-images.githubusercontent.com/31198893/77198537-281da600-6b0d-11ea-8a45-9c97bf1c6f5b.png)

#### Homepage Mobile Performance Summary: 
![Screenshot from 2020-03-21 00-45-36](https://user-images.githubusercontent.com/31198893/77198612-4edbdc80-6b0d-11ea-90a5-1b1f8b4e28dc.png)

#### Author Page Desktop Performance Summary: 
![author-desktop](https://user-images.githubusercontent.com/31198893/77535198-37f80a00-6ec0-11ea-9c90-39ee14f91ccf.png)

#### Author Page Mobile Performance Summary: 
![author-mobile](https://user-images.githubusercontent.com/31198893/77535133-15fe8780-6ec0-11ea-9f01-d88df52f6d4d.png)

#### Edition Page Desktop Performance Summary: 
![edition-desktop](https://user-images.githubusercontent.com/31198893/77535059-e8b1d980-6ebf-11ea-86f5-41dd3ed0c173.png)

#### Edition Page Mobile Performance Summary: 
![edition-mobile](https://user-images.githubusercontent.com/31198893/77535067-ecddf700-6ebf-11ea-9ab6-f536e6c8786d.png)

#### Issues Common to all pages:
![Screenshot from 2020-03-20 20-20-57](https://user-images.githubusercontent.com/31198893/77175265-576dec00-6ae8-11ea-92ce-d19f86cc64ee.png)

**The Key issues needed to improve Openlibary performance are below(in order of priority) ::**

- [ ] Properly size images #3223 
- [ ] Serve static assets with an efficient cache policy 
- [ ] Twitter preview blocked for IA hosted images #1841
- [ ] Preload key requests #3221 
- [ ] Serve images in next-gen formats #3222 
- [ ] Preconnect to required origins #3224
- [ ] Avoid flash of invisible text #3226
- [ ] Ensure text remains visible during webfont load
- [ ] Minimize main-thread work 
- [ ] Avoid an excessive DOM size 
- [ ] Reduce JavaScript execution time 
- [ ] Avoid chaining critical requests
- [ ] Keep request counts low and transfer sizes small

**Audit Report** can be found here -> [https://archive.org/details/ol-audit](https://archive.org/details/ol-audit)
[desktop-author.pdf](https://github.com/internetarchive/openlibrary/files/4380790/desktop-author.pdf)
[author-mobile.pdf](https://github.com/internetarchive/openlibrary/files/4380791/author-mobile.pdf)
[edition-mobile.pdf](https://github.com/internetarchive/openlibrary/files/4380793/edition-mobile.pdf)
[edition-desktop.pdf](https://github.com/internetarchive/openlibrary/files/4380794/edition-desktop.pdf)

### Stakeholders

@tabshaikh

**Comment by tfmorris** [comment]
I'm getting very different times, perhaps because of network speed differences. We need to find a way to test this reproducibly so that we're not chasing our tails.

We should use HTTPS for all URLs to avoid the initial redirect.
The home page is critical, but other page types are important too, so we should test Author, Work, & Edition.

Here are mobile and desktop scores for various URLs at my home office:
48 73 Work https://openlibrary.org/works/OL85892W/Dracula
95 99 Author https://openlibrary.org/authors/OL31727A/Bram_Stoker
65 98 Homepage https://openlibrary.org

As one would expect with the differing scores, the order and magnitude of the performance improvement suggestions change as well. Below are the ones for the home page:

Mobile - Score 61

Opportunité - Estimation des économies
Différez le chargement des images hors écran - 3 s
Préchargez les demandes clés - 1,17 s
Diffusez des images aux formats nouvelle génération - 0,15 s

Desktop - Score 91

Opportunité - Estimation des économies
Différez le chargement des images hors écran - 0,36 s
Dimensionnez correctement les images - 0,24 s
Préchargez les demandes clés - 0,13 s

**Comment by tabshaikh** [comment]
@tfmorris Yes maybe due to different locations and network speeds the audit would show different results, these issues I created for keeping homepage in mind but I would audit the author and editions page too and update all the issues for author and edition's page too :) Thanks for your feedback

**Comment by mekarpeles** [comment]
https://pagespeed.web.dev/analysis/https-openlibrary-org/415u7hl5ah?form_factor=mobile
