### ISSUE TITLE
2021 Q1 Twitter @borrowbot Pilot

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3255]
## Borrow Bot

Today we have a twitter Open Library `@borrowbot` that lives here:
https://github.com/internetarchive/openlibrary-bots/tree/master/twitter-borrowbot

## How it works

https://github.com/internetarchive/openlibrary-bots/tree/master/twitter-borrowbot#usage

Here's an example of how you'd use `@borrowbot` https://twitter.com/intent/tweet?text=@borrowbot%200393310728 and here's an example reply https://twitter.com/borrowbot/status/1298219991691481088.

## Issues

1. [x] #4221 reinstate affiliate server to enable just-in-time ISBNs  imports (of books not yet in catalog) @mekarpeles 
2. [x] `@borrowbot` should work with ISBNs
3. [x] `@borrowbot` should work with goodreads URLs
4. [x] There is an issue in which we're replying to the same tweets multiple times, possibly related to how we're processing or choosing the `last_seen_id.txt` timestamps -- needs issue
5. [x] People don't really have a way to discover `@borrowbot` yet, so we could create a blog post which explains how to use it (once 1-4 are working)

## Objective

Help more patrons/readers discover opportunities on openlibrary.org.

According to the hashtag analytics audit done on [tweetbinder.com](tweetbinder.com) on hashtags `#books #amazon` using the free version the analytics show that in a 7 day period the number of original tweets(excluding retweets) was approx. 140 with a number impact of 11M. Therefore this is a great **opportunity** for making our bookshelves discoverable. 
![hashtag-audit](https://user-images.githubusercontent.com/31198893/77396234-5e874980-6dc9-11ea-8dc0-a4dab857339e.png)

Whenever a user tweets out a book with the amazon link, the twitter borrow-link bot would retweet the book with the link from Open Library if it is **available**. The book will be tweeted only once. 

The sample would look something like this:
![twitter-borrow-link](https://user-images.githubusercontent.com/31198893/77395902-9772ee80-6dc8-11ea-8a5e-74a41e0c9149.png)

### Stakeholders

@tabshaikh @mekarpeles

**Comment by cdrini** [comment]
@mekarpeles says this is done! He's going to review the blog post today :+1:
