### ISSUE TITLE
Tasks remaining to get to Python 3

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3333]
[Planning Doc](https://docs.google.com/document/d/1VoSiTzsO3r2Qlhs5OoRFfbZR_u1ft8uR-72g_Mz175Y/edit#heading=h.ax5uutuo9m7l)

* [x] Fix tests for sort order differences in Python 3 #3330 
* [x] Coverstore/warc.py py3 again #3331 
* [x] The cmp argument again #3332
* [x] Prevent PRs from breaking Python 3 tests #3345
* [x] Deterministic dicthash() regardless of key order #3348 (or #3347)
* [x] lending.py: Add logging to exceptions #3350
* [x] Log URL generation failures in lending.py #3363
* [x] ~Fix coverstore doctests for WARCRecords on Python 3 #3389~ -> #3422
* [x] Dockerfile.olbase: Add Python 3.8 and pip3 #3411
* [x] Get a Python 3 powered staging.openlibrary.org #3416 
    * [x] Get Python3 installed in the Docker images #3417
    * [x] Create flag to run Docker image using only Python 3 #3418 
    * [x] Removing WARCDisk dead code + tests #3422
    * [x] Created dev1.openlibrary.org #3419
* [x] How do we modernize pytest_funcarg__xyz() tests? #3586 
* [x] Importing render_template is used for its side effects #3590
* [x] Fix absolute import and bytes for Python 3 #3598
* [x] Upgrade select Python dependencies #3619
* [x] Add 2016 LOC MARC dump description to sources #3620
* [x] Python 3: Stats workaround for lang not in web.ctx #3635
* [x] Use list(dict) instead of dict.keys() #3637
* [x] Fix doctests of UnitParser for Python 2 and 3 #3657
* [x] Fix mockcache for Python 3 #3671
* [x] Update and rename test-py3.sh to test_py3.sh #3672
* [x] Enable other doctests?
* [x] Re-enable doctests #3683
* [x] Add openlibrary/tests/core/test_lists_model.py #3691
* [x] [scripts/test_py3.sh](../blob/master/scripts/test_py3.sh#L15-L18) --> [test results](https://travis-ci.org/github/internetarchive/openlibrary/jobs/710504107#L698)
    * [x] python3 -m pytest -v openlibrary/catalog/marc/tests/test_get_subjects.py #3584
    * [x] python3 -m pytest -v openlibrary/catalog/marc/tests/test_parse.py #3584
    * [x] python3 -m pytest -v openlibrary/tests/catalog/test_get_ia.py #3584
    * [x] python3 -m pytest -v openlibrary/plugins/openlibrary/tests/test_home.py #3670
* [x] WIP: MARC Binary is bytes type, clarify code and fix tests #3584 & #3390
* [x] get_sorted_editions() is not working on books/OL42679M #3633
* [x] Python 3: Make document a cached_property #3728
* [x] Fix-pytests-for-openlibrary/records-again #3708
* [x] Ensure that [Infogami](https://github.com/internetarchive/infogami/pulls) is ready for Python 3
    * [x] Travis CI: Test on the current infogami master #3579
    * [x] Test openlibrary in travis for regressions as well internetarchive/infogami#86
    * [x] Achieve Python 3 test parity with Python 2 internetarchive/infogami#87
    * [x] Make LazyObject iterable for Python 3 internetarchive/infogami#88
    * [x] Upgrade web.py to match Open Library internetarchive/infogami#95
    * [x] Add WikiSource().__iter__() and WikiSource().__len__() internetarchive/infogami#96
    * [x] Fix import of keyencode internetarchive/infogami#98
    * [x] Server.py: json.dumps(d, default=str) for datetimes internetarchive/infogami#99
    * [x] Import traceback from the standard library internetarchive/infogami#100
    * [x] Requirements: web.py==0.39; python_version < '3.5' else 0.61 internetarchive/infogami#103
    * [x] Register i18n_loadhook() to initialize web.ctx.lang internetarchive/infogami#105
    * [x] ~A fix for work.get_sorted_editions() on Python 3~ internetarchive/infogami#107
    * [x] Py3: Fix dictionary changed size during iteration internetarchive/infogami#108
    * [x] Thing: old style class -> new style for Python 3 internetarchive/infogami#111
    * [x] Fix Thing.setattr() internetarchive/infogami#112
    * [x] Cannot add a list to a range internetarchive/infogami#116
    * [x] Py3: Fix dictionary changed size during iteration again internetarchive/infogami#117
* [x] pagecount is an int, not a float #3730
* [x] Python3: Sort Publish date unknown #3731
* [x] Add 16 pytests to `make test-py` #3735
* [x] StringIO wants str, not bytes #3752
* [x] fix MARC leader display bug #3779
* [x] Python 3 compatibility for four files in /scripts #3753
* [x] __Fix Python 3: Add Cover Image hangs__ #3733
* [ ] Docker Deployment Strategy for ol-web[1,2] #4017
* [ ] Fix deployment on ol-web1/ol-web2 #3993
* [ ] Retire ol-web3 & ol-web4 #3992
* [x] Saving record with non-Latin characters in title throws Internal Server Error #4092 
* [x] Move ol-covers to Python3 #4054
    * [x] Add Sentry to Coverstore #4055
* [ ] Moving ol-home to python3 node #4060 
    * [x] Create ol-home0 #4058 
    * [ ] Move infobase to ol-home0 #4059 
* [ ] __Test, test, test...__
* [x] _Adding book page has problems with Unicode ÄÖÜäöü or ß_ #3704 
* [ ] _Re-enable the Integration Tests in xfail mode_ #3682
* [ ] _Re-enable dependabot for Python dependencies_ #3580
* [ ] _Modernizing our Python compound sorting_ #3038
* [ ] Update dependencies
* [x] Close #890

__BOLD:__ Pull requests that are ready for review and merge.
_ITALIC:_ Issues and PRs that are optional (nice-to-have).

**Comment by BrittanyBunk** [comment]
One of the issues on the [testing page](https://github.com/internetarchive/openlibrary/wiki/Testing) is that it says "Python", but it's not specific as to which one - 2 or 3. So it seems you're going to make it compatible with both. It's just good to know for the beta test page.

**Comment by tfmorris** [comment]
It seems like Infogami is going to be our biggest hurdle. Do we have a strategy for dealing with that?

**Comment by cclauss** [comment]
Today Infogami appears to be our biggest hurdle but just a few months ago it was not.

Last year I was able to [land many modernizations on Infogami](https://github.com/internetarchive/infogami/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed) so I have a fair understanding of that codebase.  There are no miracles here so it will require effort but given the state of web.py (about to drop support for legacy Python) and OL (six files from pytests being green on Py3) I hope that it will be easier to get reviews on Infogami pull requests than it was at the end of 2019.

**Comment by cclauss** [comment]
Time to close this one! Thanks to everyone for helping to get us to Python 3!!
