### ISSUE TITLE
Get a Python 3 powered staging.openlibrary.org

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3416]
We need a way to test python 3 more readily.

Has these parts:

- [x] #3417 Get Python 3 installed in the docker images
- [x] #3418 Create a flag (or something) to run the service inside docker using only Python 3
    - Depends on #3417
- [x] #3419 Create dev1.openlibrary.org which fully uses docker and a dummy database
- [x] Make dev1.openlibrary.org use python 3
    - Depends on #3418, #3419

### Stakeholders
@cclauss @mekarpeles @paulproteus

**Comment by cclauss** [comment]
Closed in #3419
