### ISSUE TITLE
Create flag to run docker image using only python 3

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3418]
- Subtask of: #3416 
- Depends on: #3417

An environment variable might be a good way to do this; those can be used from the docker-compose file to execute special paths.

### Summary of Requirements

- [x] Way for a developer to `docker-compose up` and get an environment that uses exclusively Python 3 to run everything (infogami, coverstore, solr-updater, etc)
- [x] Way for a developer to `docker-compose up` and get an environment that uses exclusively Python 2 to run everything (infogami, coverstore, solr-updater, etc). This should be the default.
- [x] The website _DOES NOT_ need to work perfectly (maybe at all); but it should be possible to _start_ with everything using python 3

### Stakeholder

@cclauss @paulproteus
