### ISSUE TITLE
Create docker-based dev1.openlibrary.org

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3419]
Subtask of: #3416

### Summary of Requirements

- [x] dev1.openlibrary.org should be running
- [x] `docker-compose up -d` should fully start the service
- [x] It should not be linked to any production data

### Stakeholders

@mekarpeles @paulproteus

**Comment by cclauss** [comment]
What is the status of this one?

**Comment by cclauss** [comment]
@mekarpeles @cdrini Based on today's discussion, let's use my `python3` branches
* internetarchive/infogami#104
* internetarchive/openlibrary#3637
* `docker-compose down ; INFOGAMI=local PYENV_VERSION=3.8.5 docker-compose up -d`

**Comment by cdrini** [comment]
http://staging.openlibrary.org/ is running of current master for both OL and infogami :+1:

**Comment by cclauss** [comment]
Is this running on Python 2 or 3?  Based on LoanStatus, I would say Python 2

Problem URLs...
* http://staging.openlibrary.org/books/OL24197475M/The_complete_works_of_Mark_Twain.?debug=true
* http://staging.openlibrary.org/books/OL42679M/The_wit_and_wisdom_of_Mark_Twain
* http://staging.openlibrary.org/contact
* http://staging.openlibrary.org/contact?path=/help&debug=true
* http://staging.openlibrary.org/people/openlibrary/preferences

scripts/test_common_urls.py
```
#!/usr/bin/env python3

# import requests
import webbrowser
from time import sleep

# http://localhost:8080/#  # will force a logout

ROOT_URL = "http://localhost:8080/"
ROOT_URL = "http://staging.openlibrary.org/"

URLS = """
admin/attach_debugger
account/login
account
account/import
account/loans
account/notifications
account/privacy
advancedsearch
authors
authors/OL18319A
books/add
contact
search
search?q=place%3AItaly
search?place=Italy
search?subject=Adventure
search?q=twain&debug=true -- AttributeError: module 'config' has no attribute 'get'
search?q=twain
search/authors
search/authors?q=twain
type/object
works/OL53924W/The_complete_works_of_Mark_Twain
people/openlibrary/books/already-read/stats
people/openlibrary/books/currently-reading
people/openlibrary/books/want-to-read
people/openlibrary/lists
people/openlibrary/preferences?m=diff&b=3
people/openlibrary/preferences?_compare=Compare&b=3&a=2&m=diff
"""


BAD_URLS = """\
contact?path=/help&debug=true
authors/OL18319A/Mark_Twain?debug=true
books/OL42679M&debug=true  # 1.
works/OL24197475M/The_complete_works_of_Mark_Twain.?debug=true  # 1.
people/openlibrary/books/already-read/stats?debug=true  # 2.
people/openlibrary/books/currently-reading/stats?debug=true  # 2.
people/openlibrary/books/want-to-read/stats?debug=true  # 2.
type/object?m=edit&debug=true  # 2.
"""

for url in (URLS + BAD_URLS).splitlines():
    url = ROOT_URL + url
    print(url)
    url = url.split()[0]
    # print(requests.get(url).text)
    webbrowser.open_new_tab(url)
    sleep(7)
```
