### ISSUE TITLE
Epic: Shelf explorer (aka /browse aka Classifications explorer)

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3576]
A way to explore the books in Open Library's catalogue in more serendipitous, library- or bookstore-like experience.

Most book-related platforms can only really show you manually curated content, or things like "what others are reading". Even our subjects are problematic in that you have to already know a certain subject exists (or know of some of its members books or neighbouring subjects) in order to find it. Library classification systems are powerful in that they try to summarize the whole sum of human knowledge. It's much easier to find classes of books you never knew existed, and to locate related books in a way subjects can't (e.g. 613.1 (Role of the natural environment) and 613.2 (Diet (food hygiene, nutrition, diet, nutritional value of food and beverages)) are next to each other in dewey decimal because they are related under 613 (Personal Health and Safety). There's no notion of "siblings" like this in subjects).

## Requirements/subtasks
- [x] #3575 Mockups/Design explorations for Shelf Explorer
- [x] #3788 Integrated in openlibrary on dev.openlibrary.org
- [x] #3893 Demo Library Explorer for Oct 12 Library Leader's Forum
- [x] #3983 Release v1 to production

## Soft Requirements
- [ ] #3574 Searching should support sorting by classifications

This feature would still work without these, but it would be great if they were done as well.

- [x] #2913 Enable searching for a classification on prod
    - This works on dev.openlibrary.org + ol-solr0; we could have some work-around to expose the experience.

**Comment by LeadSongDog** [comment]
The LC catalogue by way of comparison supports “Browse by shelf order” comme ça: https://catalog.loc.gov/vwebv/holdingsInfo?searchId=9465&recCount=25&recPointer=1&bibId=3920005

**Comment by cdrini** [comment]
Released as MVP at https://openlibrary.org/explore! Also see blog post.
