### ISSUE TITLE
Improving Lists

### ISSUE THREAD

**Issue by spamspambaconspam** [internetarchive/openlibrary#3593]
Improving how the Lists feature works on Open Library:

* [x] #8298
* [x] #7853
* [x] #7812
* [x] #7653
* [x] #6992 
* [x] #6531
* [x] #3070
* [x] #7390 (Duplicate)
* [x] #7613
* [x] #2468 (js cleanup for lists)
* [x] #2609
* [x] #7613
* [x] #6530
* [x] #2468 (js cleanup for lists)
* [x] #2609

See also Reading Log:
* [ ] #2059
* [ ] #6530

See related 2023 proposal here:
https://docs.google.com/document/d/1kThM4RDyLGnYKn2WsorxjiOybTajuHKNJJ5P9SLEvYc/edit

### Describe the problem that you'd like solved

- [x] Seeds API is broken: https://openlibrary.org/people/mekBot/lists/OL115530L/seeds.json
- [ ] Lists embed widget is unusably out of date and should have customizable embed options + styles: https://openlibrary.org/people/mekBot/lists/OL115530L/Staff_Picks/embed
- [ ] Add ability to sort items based on title, author, year, etc.
(Currently, the list is sorted by 'time since last edited'.  Not only is this sort almost useless, but if I edit a record that appears on someone else's list, my edit then modifies the sort of _their_ list.    If I 'fake edit' records to force a specific order on my list, I'm possibly screwing up someone else's previous 'fake edits' they'd painstakingly made to force their own list to be in a specific order.)
- [ ] Add ability to display or hide details of each record, in order to view more records in window.
(Here are some details that take up room but are not considered vital:
    1. Displaying every single author.
    2. Displaying thumbnails
    3. Displaying date of last edit ~instead, the copyright date (for a work) or publication date (for an edition) would be more helpful.)
 
![image](https://user-images.githubusercontent.com/9367321/87798819-7a03dd80-c81a-11ea-9b80-40ee01bcd2ba.png)

**Comment by cdrini** [comment]
This is not likely to be a 2021 goal

**Comment by mekarpeles** [comment]
Hi, I am repurposing this issue slightly to keep track of list improvements as an epic.

- #6992
- #6530
- #6531

**Comment by mekarpeles** [comment]
Now tracked in #7390

**Comment by DebbieSan** [comment]
hi @jimchamp. Hope you are well. I'm just wondering about issue #7853 and if there is anything I can contribute to make that PR better/adding this feature to lists?

Thank you kindly!

**Comment by jimchamp** [comment]
Thank you so much for your patience, @DebbieSan!  I've added some review notes to the PR, and am happy to merge it in once the branch has been updated.
