### ISSUE TITLE
Issues relating to list (post Canonical Books Page launch)

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3607]
Subtask of epic #3561

- [x] (TODO) No reaction from dialog box when creating a new list #3599 

- [ ] (TODO - May show a button to refresh the page) It's necessary to refresh the page to see when user adds a list to a work or edition. A user must already know they have to refresh the page and that the lists are in the middle of the page in order to verify they've added an item successfully. When adding to a list, there's no visual indicator above the fold that it's been added successfully.  **!Important**

- [x] (TODO) [Lists are displayed in disorder when a book is included in several lists ](https://github.com/internetarchive/openlibrary/issues/3561#issuecomment-655726046). Example: [OL8563887M](https://openlibrary.org/books/OL8563887M)

**Comment by cdrini** [comment]
The thing we probably want is to add the user's lists to the sidebar under teh want to read button; that shouldn't be too hard from the template code.

**Comment by mekarpeles** [comment]
@tabshaikh what epic issue is this a subtask of?

**Comment by seabelis** [comment]
There's also no way to tell if a list belongs to the work or edition.
