### ISSUE TITLE
Move ol-covers to Python3

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4054]
- [x] #4053 --> #4055 Add sentry to coverstore so we can see how errors change
- ~Switch to running ol-covers with Python 3 codebase~

Docker-based:
- [x] Create ol-covers0
- [x] Install docker
- [x] Add to pg_hba conf
- [x] Does it need a copy of booklending_utils? Nope.
- [x] Does it need ia keys? (Nope)
- [x] Need to rsync /1 from `ol-covers1` to `ol-covers0`

Tried:
- Get Pyenv-based Py3 working for user `openlibrary` on `ol-covers1` (Py2)
    - Building Python on Ubuntu Trusty required openssl
    - Openssl is only available to user `root` not `openlibrary` -- unstable/unusable
- `ol-covers0` configured to run Python 3
    - Need to git clone in booklending_utils
    - Testing: Moved the wrong image files when creating a test volume `/1` on `ol-covers0`
    - Sentry: Adding dsn #4055 creates security issues (copverstore.yml on olsystem)

Need a unified way to provide secrets to Docker containers without mounting multiple volumes

> I think we want the images (from ol-covers1) which are stored in ol-covers1:/1/var/lib/openlibrary/coverstore/localdisk/
> I think what's supposed to happen is each month localdisk is somehow turned into an item which then should be uploaded to archive.org in the same way our bulk data dumps are.
> scripts/2009/07/tarsplit.py

**Comment by cclauss** [comment]
ol-covers1 (py2)% `du -hs  /1/var/lib/openlibrary/coverstore/localdisk/2020/10/10`
130M

ol-covers0 (py3)% `pwd`
/1/var/lib/openlibrary/coverstore/localdisk/2020/10

ol-covers0 (py3)% `sudo scp -r cclauss@ol-covers1.us.archive.org:/1/var/lib/openlibrary/coverstore/localdisk/2020/10/10 .`

ol-covers0 (py3)% `sudo chown -R openlibrary /1/var/lib/openlibrary`

**Comment by cclauss** [comment]
`docker-compose.yml`
```
  covers:
    image: oldev:latest
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOGAMI=${INFOGAMI:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-covers-start.sh
    ports:
      - 8081:8081
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
      - /1:/1
    networks:
      - webnet
      - dbnet
```

**Comment by cclauss** [comment]
```
sudo docker-compose down
sudo docker-compose up -d --no-deps memcached
sudo SERVICE=covers HOSTNAME=$HOST docker-compose \
    -f docker-compose.yml \
    -f docker-compose.infogami-local.yml \
    -f docker-compose.production.yml \
    up -d --no-deps $SERVICE
sudo docker-compose logs -f --tail=10 $SERVICE
```
`site` is None
