### ISSUE TITLE
Create ol-home0 node

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4058]
Subtask of #4060

- [x] Creating new VM, `ol-home0` with same specs as ol-home, but latest Ubuntu (@mekarpeles : And more RAM)
- [x] Install docker
- [x] Add to pg_hba conf -- Done in internetarchive/olsystem#99
- [ ] Does it need a copy of booklending_utils?
- [ ] Does it need ia keys?

**Comment by cclauss** [comment]
The two unchecked questions should not matter for infobase.
