### ISSUE TITLE
Move infobase to Python 3 ol-home0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4059]
Subtask of: #4060

- [x] #4125 Add logging to `scripts/infobase-server`
- [x] Need a `/1` volume mount
- [x] #4061 Add sentry to infobase
- [x] internetarchive/olsystem#100 Prepare rapid infobase switch from Py2 to Py3
- [x] #4130 / #4140 Create an nginx service that will run in a separate Docker container
- [ ] Trial deploy to production (stop py2 infobase, start py3 infobase to collect errors)
- [ ] Switch back to py2 and fix any bugs discovered during trial deploy
- [ ] Deploy infobase py3

Switch plan:

Assumption: Can't have two infobase instances running at same time?

1. Update olsystem/etc/openlibrary to point to new infobase + deploy olsystem
2. Take down ol-home1's infobase
3. Start up ol-home0's infobase
4. Restart ol-web[1-2]
