### ISSUE TITLE
Librarian Merge Queue: Propose/Flag Dupes

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4071]
**Adapt Integrated Librarian Environment (ILE) bar to propose Merge Requests**

mek  2:22 PM
We very briefly talked about how community might safely flag merge requests
@seabelis led us to a great idea, which is -- if not librarian, have same UI as if admin/librarian. Let people select items. Instead of showing "Merge Works" show "Merge Request"
Normally what happens is we send Lisa to /works/merge?works=...
Instead, clicking this link would take this URL and (instead of redirecting) just submit that URL to a review list, to lisa (edited) 

cdrini  2:24 PM
:plus1: That would be hugly wonderful/impactful, and not a ton of work! 

mek  2:24 PM
A bit messy and it's not something we should tackle this month given the inf. is in flux
But implementation wise, I think it's a good approach and simple to implement assuming everything is merged upstream

cdrini  2:24 PM
But I think we need to figure out the lists issue; otherwise Lisa will end up having queues of merges that she can't do

mek  2:25 PM
That's fine too, that's a different problem.
We just provide a sort or something. Or add another flag to e.g. "resolve" as unactionable. Or we compute that ahead of time and annotate the link accordingly. In any event, baby steps towards streamlining is better that what's happening today.

cdrini  2:26 PM
I don't think fixing the lists issue would be a ton of work, but it just needs to happen. After that, merges can happen at the speed of discovery :slightly_smiling_face:

**Comment by mekarpeles** [comment]
Also, @RayBB's tool is a great compliment to the Librarian Merge Queue
https://raybb.github.io/onepagers/sites/ol-author-similarity

**Comment by jimman2003** [comment]
+1 on the proposal,but I believe the queue should be accesible by all librarians not in training

**Comment by mekarpeles** [comment]
# Merge Queue

## Goal

Instead of using `#openlibrary-merges-g` slack channel, any librarian can go to use ILE toolbar, click books, click a new merge request button which submits and entry to the merge table. A super-librarian can click on a MR and approve or reject a merge which updates the table.

## Benefits:
* We'll be able to see how many merges are being done (hard on slack)
* More people will be able to participate in MRs
* Better / streamlined interface for submitting MRs

## What's done:
* [x] ILE is merged #3408
* [x] MR table + schema exists #6051
* [x] API exists for MR table CRUD actions #6051
* [x] UI exists for showing MRs #6051

## What's remaining:
* Create new button for librarians to submit MR using ILE
* Passing MR id to merge UI so it can be used to update table
* Updating MR table based on approve/reject MR (after review)
* Claiming / assigning librarians to a MR
