### ISSUE TITLE
Tracking issue: Top five most frequent issues in Sentry

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4091]
Reduce the clutter in Sentry by fixing the most frequent errors...
https://sentry.archive.org/sentry/ol-web/?query=runtime%3A%22CPython+3.8.6%22&sort=freq
* [ ] 834k times: openlibrary.core.lending ___compose_ia_url failed___ OL-WEB-3C
* [ ] 529k times: openlibrary.core.lending ___get_available() failed___ OL-WEB-3D
* [ ] 290k times: openlibrary.plugins.importapi.code ___BookImportError('no-marc-record')___ OL-WEB-3J
* [x] 157k times: openlibrary.plugins.importapi.code ___BookImportError('no-imagecount')___ OL-WEB-3F
* [ ] 45k times: openlibrary.utils.solr in select at line 95 ___JSONDecodeError()___ OL-WEB-8B

**Comment by hornc** [comment]
@cclauss what does the check mark against  OL-WEB-3F signify? Those two book import errors look ok to me, the exceptions are being raised, and handled, to be passed back to what ever client made the request to indicate that the import could not be completed for the reason stated, by design.

**Comment by mekarpeles** [comment]
It looks like most of these have since been resolved, we updated sentry to re-alert us if any of these occur more than 100 times. Closing for now w/ @cclauss's consent
