### ISSUE TITLE
Update olsystem ol-covers1 → ol-covers0 (all mentions)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4203]
Before we can decomission ol-covers1, we need to make sure:

- [x] #4206 coverstore golive mods 
- [x] all necessary data is moved from `/1` covers1 -> covers0
- [ ] internetarchive/olsystem#104 all scripts/mentions in olsystem either use covers.openlibrary.org or ol-covers0 (and not ol-covers1); especially olsystem cron jobs living on ol-home
- [ ] #4197 Preserve exception info in covers.upload2
