### ISSUE TITLE
Replace ol-www1 with docker-based ol-www0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4252]
ol-www1 hosts static files as well as the nginx that serves the main site.

Related:
* #4775
* #5144
* #5757
* #6000
* #6001

---
* [x] #6000
* [x] #6001
---
* [x] #4252
    * [x] #7544
    * [x] Fix IP anonymization [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-854050184) 
    * [x] Fix log rotation [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-854050184)
    * [x] #5144
    * [x] #7622
    * [x] Fix monthly sitemap rsync [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-920238877) --> #7781

---
- [x] Provision the server
     - [x] @mekarpeles to ask for an replacement server to be provisioned for `ol-www1` called `ol-www0`
    - [x] Install Docker and create `docker` group w/ `nagios,cclauss,drini,mek` as members  (run `scripts/setup_olserver.sh`)
        - [x] olsystem, openlibrary, infogami is to be synced
        - [x] #4719 openlibrary will live inside the Docker container - Need to update the static stuff (as a part of volume mounts)
        - [x] #4719 Might need i18n, etc. if we do not have volume mounts.
    - [x] Provision to have docker/etc
        - [x] Add HTTPS certs for openlibrary.org
---
- [x] #4725 **Create docker images/docker-compose services**
    - [x] #4566 Create `web_nginx` service in `docker-compose.production.yml`
        - [x] Copy nginx confs from olsystem into openlibrary
    - [x] #4566 Create `web_haproxy` service in `docker-compose.production.yml`
        - [x] Copy haproxy confs from olsystem into openlibrary
    - [x] Launch on ol-www0
    - [x]  Create a Dockerfile for `ol-www1` which includes services for `nginx`
    - [x] Switch covers to use the IA-specific nginx
    - [x] @cdrini Add www0 to deploy.sh/friends #5954
---

- [x] #6000

---

- [x] #6001

---

To Investigate:
- ol-www1 crons: Sitemaps, ipstats
- ol-www1 has some relation to sitemaps; make sure they're still generated. Might need to copy them over.
- ol-www1's nginx logs are read to determine some of the openlibrary.org/stats . Confirm they all still work.
- ipstats crons jobs
- Log strategy: log rotation, where to store; need them to live a long time.

### Considerations
If/when we remove volume mounts, our cron jobs may need to be re-architected for commands which ssh to hosts (as the code will now be inside docker and we'll need some way to trigger these commands in docker from ol-home0 + ssh)

**Comment by cclauss** [comment]
What is the upside of doing all this work?  What will www0 give us that www1 does not currently deliver?

**Comment by cdrini** [comment]
@mekarpeles Note: Logs might need to be longer-lived on www1, and regularly uploaded to IA.

**Comment by cdrini** [comment]
@cclauss One purpose is being able to build static files _at all_ :) Currently we have to build the static files on ol-home outside of docker; this is going to be deprecated as we work towards #4060 . 

Another important purpose is that we make our nginx confs available to the community, so they can make changes which would currently be impossible for them to do (e.g. add HTTP/2 support).

**Comment by cdrini** [comment]
Note: Might need GeoMind on this :/

**Comment by mekarpeles** [comment]
@cclauss please check-in with @cdrini first to coordinate but I see this as a potential opportunity for you to help out with the initial step of provisioning ol-www0 like we we have some of the other VMs (e.g. to get Docker installed, etc)

**Comment by cclauss** [comment]
- [x] Install Docker and create `docker` group w/ `nagios,cclauss,drini,mek` as members  (run `scripts/setup_olserver.sh`)

ol-www0% `docker version`
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```
ol-www0% `cat /etc/group | grep docker`
```
docker:x:116:nagios,cclauss,drini,me
```

**Comment by cclauss** [comment]
Q: Which repos (olsystem, openlibrary, infogami, etc.) need to be installed on `ol-www0`?  I assume we want a minimal set.

**Comment by cdrini** [comment]
Here's @traceypooh nginx binary: https://archive.org/serve/nginx

**Comment by cdrini** [comment]
Potential problems:

- ol-www1 crons: Sitemaps, ipstats
- Log strategy: log rotation, where to store; need them to live a long time.
- Messy rebase

**Comment by mekarpeles** [comment]
What we learned today...

## Log Rotation

In order for **anonymized** log rotation and backups to occur, we rely on a petabox script called `/opt/petabox/sw/bin//archive-weblogs.py`.

Some notes, (yikes): 
1. ol-www1's version of petabox is from 2014 and not version controlled
2. `archive-weblogs.py` has since been migrated to python3 in petabox
3.`ol-www0` will need this script **and** `ol-www1`'s log rotation + upload cron: `/etc/cron.d/archive-webserver-logs` + the latest `archive-weblogs.py` (which we should add to `olsystem`)

**Comment by cdrini** [comment]
Note: not uploaded to https://archive.org/download/ia_webserverlogs_20210609/openlibrary/ :/

**Comment by mekarpeles** [comment]
re: sitemaps, be warned, ol-www1 is still (to this day) trying to pull from **ol-home** in allnodes and so I wouldn't be surprised if this is completely borked and we have no sitemaps rolling through. This code should almost certainly be pulling from ol-home0 and also, be added to ol-www0's cron (accordingly)

```0 20 1 * * openlibrary /olsystem/bin/verify-node.sh ol-www1 && mkdir -p /1/var/lib/openlibrary/sitemaps && rsync -av --delete rsync://ol-home/var_1/tmp/sitemaps/sitemaps /1/var/lib/openlibrary/sitemaps/
```

**Comment by cclauss** [comment]
#6000 [Complete ol-www1 → ol-www0](https://github.com/internetarchive/openlibrary/issues/6000)
* [ ] #4252
    * [ ] #7544
    * [ ] Fix IP anonymization [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-854050184) 
    * [ ] Fix log rotation [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-854050184)
    * Fix monthly sitemap rsync [#4252 (comment)](https://github.com/internetarchive/openlibrary/issues/4252#issuecomment-920238877) 
    * #5144
