### ISSUE TITLE
Progressive Web App (PWA): Enabling offline functionalties and push notification

### ISSUE THREAD

**Issue by codetochangeMinds** [internetarchive/openlibrary#4257]
### Describe the problem that you'd like solved

Currently OL does not have support for offline functionalities. There needs a brainstorming about the features that needs to be supported while the user is offline. Customized push notifications are a great way to interact with the users actively and they definitely enhance user experience. The feature of push notification needs to be enabled in order to improve on the engagement with the mobile user of Open Library. 

### Proposal & Constraints

The proposed solution is to enable [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) and use [workbox library](https://developers.google.com/web/tools/workbox/) to support offline functionalities. For push messaging  we can make use of [push api](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) which can help to interact effectively with OL mobile users. The push notification can add value to user experience if done in right way and not just spam user! for e.g we can notify the user as soon as the book is available for lending. PWA has many [success stories](https://developers.google.com/web/showcase).

First we need to talk to OL mobile users and extract the requirements about the offline functionalties and push notifications. Once requirements are extracted we need to brainstorm and look like how we can support these features. Workbox, service worker api, notification api and push api can be used to implement the above listed features. 

### Subtasks

- [x] @shrey27tri01 #4444
- [x] @cdrini  #5423
- [x] @Yashs911 #5430 
- [x] @Yashs911 #5286 Create PWA with offline functionality
- [x] @Yashs911 #5579 Create + Upload Google play assets to repo
- [x] @cdrini Create Google Play email includelist beta
- [x] @mekarpeles #5828
- [x] #6375
- [ ] @Yashs911 #5829

### Stakeholders
@Yashs911

**Comment by jdlrobson** [comment]
@mekarpeles I'll be honest with you - this sounds overly ambitious for 2021 IMO and very risky for future maintenance.

FWIW we have been trying to do this on Wikipedia since 2016 where we suffer from similar legacy issues with our frontend and backend and are nowhere near there with many more staff and contributors.

If you are using service workers your frontend really should be solid and we are a long way from there.

To work towards this I'd recommend the following steps in the right direction:

1) to move all our inline scripts into webpack #4485 
2) Reducing the amount of dependencies
3) Porting code to a modern framework like Vue

>  Customized push notifications are a great way to interact with the users actively and they definitely enhance user experience.

**Comment by cdrini** [comment]
Notes from a chate with Mek on PWAs:

- This PR is probably a good base: https://github.com/internetarchive/openlibrary/pull/3817
- Need to read best practices (LINK)
- Phase 0:
    - Create service Worker for basic things like the logo, CSS, yadda yadda (maybe entire homepage?)
    - Might need to make some small design tweaks; like making header sticky (or other improvements)
    - Trusted Web Activity: Ability to include a PWA inside the play store
        - This is the main end goal for this phase
        - https://testing.openlibrary.org/manifest.json
    - Will need some sort of offline experience. This means we'll need to cache somethings offline.
        - Show active loans
        - Cache Reading Log; that will likely need something like IndexDB? Look at best practices
            - Disable actions when offline
- Phase 1:
    - Reading offline (at least public domain!)
- Questions:
    - Currently eg reading log is rendered server side; will this need to be done client side?
- Lower-level dream factory:
    - Cache reading log actions? Moving a book between shelves
    - Cache user lists? Use last-modified date to avoid fetching to frequently
- Dream Factory:
    - Offline reading 😭

**Comment by RayBB** [comment]
It looks to me like this is all done so I'm gonna close it :)
