### ISSUE TITLE
Improve docker-based environment/deployment

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4382]
- [x] #4276 Default to Python 3.8.6
- [x] #4391 Remove `/openlibrary` volume mount from docker-compose.production.yml
 - [x] #4375 Add vim and emacs to Dockerfile.olbase
 - [ ] #4395 Scripts for production deployments

[Deployment Scratchpad](https://github.com/internetarchive/openlibrary/wiki/Deployment-Scratchpad)

**Comment by cclauss** [comment]
Closing in favor of #4423 because we have too many tracking issues.
