### ISSUE TITLE
2021 Q1 Provisioning & Deployment Plan

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4423]
This is a planning epic (and doesn't require direct attention -- to be closed when underlying issues are resolved)

- [ ] automated deploys (4h -> 15min)
- [ ] solr updater (prod)
- [ ] rm volume mounts (for deloys)
- [ ] import bot
- [ ] cron jobs will live in a service on ol-home0 (testing) @clauss
- [ ] ol-www1 `epic` (edge cases: logs, ssl-termination, sitemaps) @cdrini
- [ ] need ol-www0
- [ ] deploy strategy needs to address ol-www0, solr updater, import bot, cron service + volume_mounts
- [ ] eventual ol-home deprecation
-- [ ] remove ol-home proxypass to ol-home0 for infobase + update config
-- [ ] can we dump stats-solr and move from ol-home to ol-home0, reclaim 4gb of ram
- [ ] ol-db[1,2] and ol-backup?

**Comment by cclauss** [comment]
```
* dumps are generated at /1/var/tmp/dumps
/olsystem/bin/uploaditem.py:222: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  p.readfp(f)
uploading with parameters: {'item_identifier': 'ol_dump_2021-02-26', 'from_url': 'rsync://ol-home0.us.archive.org/var_1/tmp/dumps/ol_dump_2021-02-26', 'submitter': 'openlibrary@archive.org'}
  Submitted.
/olsystem/bin/uploaditem.py:222: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  p.readfp(f)
uploading with parameters: {'item_identifier': 'ol_cdump_2021-02-26', 'from_url': 'rsync://ol-home0.us.archive.org/var_1/tmp/dumps/ol_cdump_2021-02-26', 'submitter': 'openlibrary@archive.org'}
  Submitted.
```
