### ISSUE TITLE
Migrate ol-www1 to ol-www0

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4424]
### Describe the problem that you'd like solved

- [x] @mekarpeles to ask for an replacement server to be provisioned for `ol-www1` called `ol-www0`
- [x] #4725 Create a Dockerfile for `ol-www1` which includes services for `nginx`
     - [x] Switch covers to use the IA-specific nginx
- [x] @cdrini Add www0 to deploy.sh/friends
- [ ] Do a deploy 2021-12-09 so openlibrary/olbase is updated to latest configs
    - [ ] Confirm new nginx/haproxy on ol-www0 running (Update /etc/hosts locally, and change server_name to `x-*` on www0)
4. @cclauss Fix/confirm the following:
     - [ ] sitemaps are being copied to www0
     - [ ] nginx logs being uploaded to IA
5. Retire ol-www1?

### Considerations
Note re: (3) If we remove volume mounts, our cron jobs may need to be re-architected for commands which ssh to hosts (as the code will now be inside docker and we'll need some way to trigger these commands in docker from ol-home0 + ssh)

### Stakeholders

@cdrini @cclauss

**Comment by mekarpeles** [comment]
Duplicate of #4252

**Comment by cdrini** [comment]
Ooops, was updating the wrong issue ; moved all data over to https://github.com/internetarchive/openlibrary/issues/4252
