### ISSUE TITLE
Investigate if we can remove stats_solr

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4426]
Subtask of #4060

There is a solr instance running on ol-home called stats_solr. We're not sure if this is still in use, how its being used, or if we might be able to deprecate it in favour of a something else.

Note: At the very least there is historical value to the data there, so we need to make sure to create a data dump if we do find it's no longer being used in production.

- [x] Identify what solr data + indices/cores exist on ol-home
- [ ] Create a backup of the solr data -- CRITICAL!!
- [x] Investigate whether the solr instance is still used & needed
    - ~If so, add to ol-home0 docker + wire up 🙁~

`http://localhost:8983/solr/admin/cores?action=STATUS&wt=json | grep core`
    
`<lst name="params"><str name="q">*:*</str></lst></lst><result name="response" numFound="22188421" start="0">`
    
```
<doc>
	<arr name="author_keys_id">
		<str>/authors/OL19043A</str>
	</arr>
	<str name="book_key_s">/books/OL23243566M</str>
	<str name="contributor_s">Internet Archive</str>
	<int name="duration_hours_i">120</int>
	<arr name="ia">
		<str>killinggame00joha</str>
	</arr>
	<arr name="ia_collections_id">
		<str>printdisabled</str>
		<str>inlibrary</str>
		<str>browserlending</str>
		<str>internetarchivebooks</str>
		<str>americana</str>
	</arr>
	<str name="key">loans/XXX</str>
	<date name="last_updated_dt">2014-11-10T15:38:33.529Z</date>
	<arr name="publish_year">
		<int>1999</int>
	</arr>
	<str name="resource_type_s">bookreader</str>
	<str name="sponsor_s">Internet Archive</str>
	<str name="start_day_s">2014-11-05</str>
	<date name="start_time_dt">2014-11-05T15:15:47.357Z</date>
	<str name="stats_type_s">loan</str>
	<arr name="text">
		<str>loans/XXX</str>
		<str>The killing game</str>
		<str>killinggame00joha</str>
	</arr>
	<str name="title">The killing game</str>
	<str name="title_suggest">The killing game</str>
	<str name="type">stats</str>
</doc>
```

**Comment by cdrini** [comment]
@mekarpeles Says these might be being used by the stats pages openlibrary.org/stats and the stats on the homepage. Investigation needed.

**Comment by cdrini** [comment]
Ok, looking at occurences of `stats_solr` in openlibrary,

This solr instance is written to in:
1) `openlibrary/solr/process_stats.py`
     - triggered via cron regularly
     - Only ever called with the options `--load-from-db` and `--day`
     - Reads from a table called `stats` in the db, and writes the rows from there into `stats_solr`

Here's sample data from `stats`:

|           key          | json|
------------------|----
 loans/loan-2781002057 | {"book": "/books/OL22449759M", "identifier": "isbn_9780224023481", "resource_type": "bookreader", "t_start": "2023-04-20T00:00:06", "t_end": "2023-04-20T00:00:07.464837", "status": "completed"}
 loans/loan-2781006773 | {"book": "/books/OL18626907M", "identifier": "mathewschineseen0000math_j6d7", "resource_type": "bookreader", "t_start": "2023-04-20T00:00:08", "t_end": "2023-04-20T00:00:09.224188", "status": "completed"}
 loans/loan-2781009720 | {"book": "/books/OL6225509M", "identifier": "fairoaksnovel00yerb", "resource_type": "bookreader", "t_start": "2023-04-20T00:00:09", "t_end": "2023-04-20T00:00:10.710054", "status": "completed"}
 loans/loan-2781003700 | {"book": "/books/OL26992991M", "identifier": "courtofmistfury0000maas_c3x6", "resource_type": "bookreader", "t_start": "2023-04-20T00:00:11", "t_end": "2023-04-20T00:00:12.280708", "status": "completed"}


It is read from:
1) `openlibrary/solr/process_stats.py`, which reads the last modified datetime as a marker when called with `--load-from-db`.


So it is only read in service to being written to. Ergo: It is effectively write-only, and serving no useful purpose. And because it is acting just as an index of the existing `stats` db, it houses no original information. But a backup would be good just in case in case it has been used in the past.

Recommended next steps:

1) Stop the writing scripts from running on the old ol-home
2) Backup the contents of the solr as a JSON dump
3) Turn off the solr to see if it is being used by anyone else

All done!
