### ISSUE TITLE
2021 Q1 Community Book Notes

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4453]
This is the `epic` and roadmap for Open Library's Community Book Notes project, inspired by [Storygraph](https://www.thestorygraph.com):

**Issues:**
https://docs.google.com/document/d/19rEj3Dy2yIzlZQBPPf9R-99N1htGwOrBOltJhH2tdh4/edit#heading=h.t2y0k830qbxu

**Proposal:**
https://docs.google.com/document/d/13Qrxfnd7BbSoMyRIAMM1wekr78sOVbaZpaOfH03tHe0/edit#

## Subtasks

- [x] https://github.com/internetarchive/openlibrary/pull/3912
- [x] https://github.com/internetarchive/openlibrary/pull/4135
- [x] https://github.com/internetarchive/openlibrary/pull/4443
- [x] https://github.com/internetarchive/openlibrary/issues/4294
- [x] Create new reader observation tables, and configure observations (#4801)
- [x] Complete basic CRUD functionality for book notes modal (#4802)
- [x] Improve book notes modal UI (#4781)
- [x] Create aggregate observation statistics component for book pages (#4867)
- [x] Create page where all of a patron's book notes are listed (#4868)

**Comment by BrittanyBunk** [comment]
Really cool idea, the book notes.

**Comment by jamesachamp** [comment]
I've updated the sub-tasks to better reflect the proposed features.  I'll update the new tasks with links to the issues as I open them.

**Comment by cdrini** [comment]
Woohoo! https://blog.openlibrary.org/2021/08/20/introducing-community-reviews/
