### ISSUE TITLE
Site Performance

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4485]
Epic to supplant #3793 w/ actionable subtasks

See Game Plan: https://docs.google.com/document/d/1UVpfdt-1W7OimAEa1gHGF-xTqaQVuimzUPL6tQaSeCU/edit

Before starting this epic (or specific issues), we should collect baseline metrics so we know if/how we're improving.

## Approved

* All Pages
    * [x] #7714
    * [ ] #7710
    * [x] #7450 
    * [x] #7453
    * [x] #7591
* Lending
    * [ ] #7726
* Registration
    * [x] #7674
* Book Page(s)
    * [ ] #7451 
    * [x] #7452
* Search
    * [x] #7673 -- Solr resourcing (fix queries, decrease 500s, support new use cases) 
    * [x] #7713
    * [x] #7712
        
## Ideas

* All Pages
    * #3223
    * #1367
    * #3227 + anonymized [Core Web Vitals](https://web.dev/vitals)
    * Reducing unused js + css dependencies (& what's loaded per page)
* Solr
    * Separate isolated solr for APIs
* Database
    * [ ] Upgrade postgres? 9.3 -> 13
* Python (Experimental)
    * [ ] cythonizing Python code
    * [ ] replacing CPython with Pypy

### Stakeholders

@SouthGoingZax, @cdrini, @cclauss, @jdlrobson

**Comment by jdlrobson** [comment]
I think the best place to start here would be to set some benchmarks and set a goal e.g. "Site renders in under 3 seconds and fully loads in under 15 seconds on a 3G connection"

I'm actually attending a workshop around performance first week of February as a refresher, so if this can hold out until then, I can go through that with this in mind.
