### ISSUE TITLE
Cleaning up Python 2

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4776]
Continuation of #4384
- [x] Infogami
    - [x] Add mypy to Continuous Integration using `setup.cfg` to log exclusions internetarchive/infogami#155
    - [x] Get GitHub Actions to pass all tests that Travis CI passed internetarchive/infogami#154
    - [x] Remove Travis-CI internetarchive/infogami#158
    - [x] Add more [flake8 tests](https://github.com/internetarchive/infogami/blob/master/.github/workflows/python_tests.yml#L41) internetarchive/infogami#155
    - [x] Remove testing on 2.7 in the Infogami repo internetarchive/infogami#154
    - [x] Run `black --skip-string-normalization .` internetarchive/infogami#162
    - [x] Add more flake8 tests internetarchive/infogami#178
    - [x] _make a production deployment of `psf/black` changes before proceeding_
    - [x] Run pyupgrade -- Removes Python 2 refs in the codebase internetarchive/infogami#192
    - [x] Run `isort --profile black .` codebase internetarchive/infogami#196
    - [ ] _make a production deployment of `isort` changes before proceeding_
- [ ] Open Library
    - [x]  Remove Python 2 from Continuous Integration #4385
    - [x] Remove 2.7.6 install from Docker olbase #4386
    - [x] Remove uses of six.PY2 and six.PY3 #4769
    - [x] Add mypy to Continuous Integration #4988
    - [x] Run `black --skip-string-normalization .`
        - [x] #5839
        - [x] `/tests` #5338
        - [x] `/scripts` #5841
        - [x] #5836
        - [x] #5855
        - [x] #6594
        - [x] #6725
        - [x] #6726
        - [x] #6731 
        - [x] #6734 
        - [x] #6747 
        - [x] #6749 
        - [x] #6751 
        - [x] #6753
        - [x] #6754
    - [x] #5835
    - [x] #6567 
    - [ ] Drop [--skip-string-normalization](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings) in `pyproject.toml` to allow black to favor double-quoted strings
    - [x] Run `isort --profile black .` ___ON HOLD!___ (see #5836)
    - [ ] _make a production deployment of `isort` changes before proceeding_
    - [x] Add more flake8 tests
- [ ] OLSystem
    - [ ] Continue to fix Python 3 compatibilities
