### ISSUE TITLE
Ensure hyphenated ISBNs are imported properly

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#49]
User report:

http://openlibrary.org/admin/support/74

The LC Bot can't read "human" ISBN. A human, correct ISBN: 978-3-938690-92-5 http://openlibrary.org/works/OL15388738W A machine ISBN: 9783938690925 http://openlibrary.org/books/OL24803001M Same number but the LC Bot can't find it. 

LC Bot should have an enforced step of normalizing ISBN. We now have 2 records with the same ISBN, one hyphenated, one not.

**Comment by LeadSongDog** [comment]
Hey Edward, any headway on this? Wouldn't want to hit the five-year mark...

**Comment by salman-bhai** [comment]
@LeadSongDog is it okay that we close this Issue since it's #609 says that it's a duplicate of it?

**Comment by salman-bhai** [comment]
@mekarpeles what do you think if we should close this since it looks like the Issue is related or at max duplicated?

**Comment by tfmorris** [comment]
@salman-bhai The last comment on #609 says that they're not duplicates. If you disagree with that comment, why don't you go there and post your rationale for disagreeing.

Being old isn't sufficient justification to close issues. Yes, it's embarrassing that there are known bugs which have gone unaddressed for most of the decade, but the solution to that is to fix the bugs, not to remove evidence that they've been open for a long time. That will just mean that we have to rediscover them later and recreate all the history associated with them.

**Comment by salman-bhai** [comment]
My apologies I hadn't seen that comment. I probably didn't get a notification to that as well

**Comment by brad2014** [comment]
(Recommend marking this a duplicate of retitled #609)

**Comment by tfmorris** [comment]
@brad2014 Did you see my Apr 2018 comment?

I'm not sure whether advocating only for normalization in the search index and not on import or something else.

**Comment by hornc** [comment]
The code for LC Bot looks to be https://github.com/internetarchive/openlibrary/blob/master/scripts/lc_marc_update.py

which uses the `/api/import` import endpoint.

The import API endpoints should be able to handle various forms for ISBN, this should be tested and confirmed.

In general, LC Bot should be deprecated (I don't believe it has been used for a long time). 

1) Any updates to this bot should take advantage of the existing OpenLibrary client to handle logins etc
2) the importing MARC from archive.org items, which the bot seems to do, is handled by the newer `/api/import/ia` endpoint.

**TODO:** 
- [ ] Confirm `/api/import/ia` endpoint correctly handles hyphenated ISBNs in source MARC records
- [ ] Confirm `/api/import` endpoint correctly handles hyphenated ISBNs
- [ ] Review existing archive.org LC data items, is there any importing work left?

The source data for this bot was https://archive.org/details/marc_loc_updates which looks like it has been fully imported by https://openlibrary.org/people/LCImportBot and also some by ImportBot: https://openlibrary.org/books/OL27873M/ash-Shafi%CA%BBi's_Risalah_basic_ideas.?m=history from the same data source.

**Comment by guyjeangilles** [comment]
LCbot hasn't done anything since 2012. Renaming this issue.
