### ISSUE TITLE
ol-home cleanup: todo create separate issues

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5066]
The remaining issues are as follows, which are being moved to a followup issue:
- [ ] Remove infobase ol-home:7000 -> ol-home0:7000 reverse proxy
    - [ ] remove ol-home proxypass to ol-home0 for infobase + update config
- [ ] Can we dump stats-solr and move from ol-home to ol-home0?
    - [ ] #4426 Can we remove it?
- [ ] can we reclaim 4gb of RAM from ol-home (until we can decommission)
- [ ] INCOMPLETE; anything else?
- [ ] Remove ol-home

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/4060#issuecomment-822757721_

**Comment by cdrini** [comment]
Closing in favour of #5143 and #4426.
