### ISSUE TITLE
LoanStatus Hotfixes

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5142]
This small epic should update LoanStatus to solve the following 4 problems:

1. [x] The #4716 PR logic now needs to be updated so we can search inside restricted books w/o forcing us to borrow the book `macros.BookSearchInside`; i.e. should behave differently for Readable v. Restricted materials
2. [ ] Show Donate Button on eligible titles (investigate why more books show `Not In Library`)
3. [ ] Prevent `community texts` form appearing as `Read`able
4. [x] #4379 Don't show `Not In Library` if **not** (3) **and** we have the book! (why is this happening? investigate)

### Stakeholders

@bfalling, @seabelis, @cdrini

**Comment by chaos300** [comment]
> 

- [ ] 

1. ### 

- **__**

**Comment by mekarpeles** [comment]
Stale: I think this can be closed, the problems today are different than when we opened the issue
