### ISSUE TITLE
Update production postgres from 9.3 -> 18

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5675]
# Current State

Postgres is currently at 9.3 which is ancient. This has performance ramifications, support ramifications, and complicated moving off trusty on our remaining legacy machines.

See also (internal):
https://docs.google.com/document/d/1ZOFi8EIOUTsFJwz9xpee9RG7jael1qX_J4E1CZbGiBc/edit?tab=t.0

# Next Steps

See breakdown here: https://docs.google.com/document/d/1ZOFi8EIOUTsFJwz9xpee9RG7jael1qX_J4E1CZbGiBc/edit

- [ ] Test 16.2 locally using built in db subset #5686
    - [ ] Attempt to upgrade the postgres version and catalog what breaks
- [x] Provision ol-db0 and ol-backup1
  - [x] #9153
  - [x] #9154
  - [x] #9155

## Questions
- How do we keep ol-db0 in sync

## Step 2: Test Prod Data
* Option 1: Test with psql dump + reload
    * Create ol-db3 with latest Ubuntu + postgres, and try loading a backup in it
    * Try running an open library off ol-db3 (NOT PUBLIC) ensure everything works; connect to mek.openlibrary.org
* Option 2: Clone ol-db1 to new server + update ubuntu/postgres
* Option 3: Create new server with latest ubuntu/postgres + copy filesystem

## Step 3: Prod Migration
* Option 1: 
    * Turn off open library
    * Dump prod DB
    * Load DB into ol-db3
    * Set-up ol-db4 to replicate ol-db3
    * Connect web heads to ol-db3
    * Turn OL back on
* Option 2: Update ubuntu/postgres on prod server on both db servers
* Option 3: Same as testing step

**Comment by jimman2003** [comment]
can we get the psql dump? currently expementing with postgres

**Comment by cclauss** [comment]
https://www.postgresql.org  Current version is v15.2.

**Comment by mekarpeles** [comment]
## Objective

Migrate from psql 9.3 to latest 18.

## Justification

* `ol-db1` on ancient trusty vm
* Unable to grow HDD space more (~160gb remaining, ~1tb db size)
* Slower performance security considerations of 9.3
* Limited features; e.g. streaming (no logical) replication, no async, no json

## Players

* `ol-db1` is our **production** psql service on 9.3
* `ol-db2` is our **secondary** psql service (replica) on 9.3
* `ol-db0` is our **staging** psql server

## Considerations

Open Library is a small team staffed by 3 engineers, so the solution needs to be implementable quickly, we need to be able to recover if something goes wrong, minimize downtime, and reduce/limit uncertainty that we're not prepared for.

## Approaches

### Dump 9.3, Load 18

The _simplest_ path would be:
1. setup `ol-db0` (staging) as psql 18 
2. Set `ol-db1` to read-only (or take offline)
3. From `ol-db0` take a psql 18 dump of `ol-db1` ~3h  and then load the dump ~8h (~11h total)

**But**, this results in nearly 12 hours of downtime and if something goes wrong, we have to incur this cost again.

### Replicate 9.3, Upgrade in Place

It's material that we are currently replicated `ol-db1` to `ol-db2` -- it means that `ol-db1` is setup to replicate to (and **only** to) another psql 9.3 machine (psql 9.3 only has **streaming replication** -- i.e. between the same major version -- logical replication between major versions is introduced in 9.4).

An upgrade **in place** (i.e. on an existing psql instance) is significantly faster and is supported [since 9.2.X `pg_upgrade` is designed to upgrade to latest version of psql](https://www.postgresql.org/docs/18/pgupgrade.html#:~:text=pg_upgrade%20supports%20upgrades%20from%209.2.X%20and%20later%20to%20the%20current%20major%20release%20of%20PostgreSQL%2C%20including%20snapshot%20and%20beta%20releases.)

Therefore, we can leverage the fact that `ol-db1` is already configured to replicate by **also** setting up `ol-db0` as a 9.3 replica and leveraging `pg_upgrade` to upgrade in-place to 18 (latest).

Typically this process is considerably faster than "Dump & Load" because `ol-db0` would already be fully up to parity with `ol-db1` via replication and not require going offline for this portion.

The only downtime entails (a) putting `ol-db1` is read-only mode, (b) stopping replication on `ol-db0`, (c) performing a nearly instant backup, and (d) performing the upgrade.

Because we (c) have a backup and (a) `ol-db1` is not involved in this process, we can freely perform (d) the upgrade **in-place** using `--link`. Usually, a `pg_upgrade` copies the files over from the old version to the new version to aid in recovery, but since we (c) we have a backup, we can "YOLO" upgrade by directly modifying the ol-db0 9.3 `main/` cluster. If the upgrade fails, `ol-db1` is fine, and the `ol-db0` 9.3 backup lets us try again or cut our losses and try again another day with sub-1-hour down time / read-only mode time.

### Bucardo

There's a 3rd party tool `bucardo` which allows you to implement "logical replication" by instrumenting tables with primary keys and triggers. It simultaneously has the capability to achieve a migration with nearly 0 downtime but introduces complexity and questions, potentially creates situations we're not prepared to predict or recover from, and is more difficult to monitory. For these reasons, our leaning is "Replicate 9.3 and Upgrade In-Place". 

## Replicate, Upgrade In-Place

1. Setup
2. Benchmark -- validate assumption that upgrade-in-place is fast
3. Production Cutover

### Setup

Install psql 9.3 and 18 on `ol-db0`:

```
sudo apt-get install postgresql-9.3 postgresql-client-9.3
sudo apt-get install postgresql-18 postgresql-client-18
```

Setup `/etc/postgresql/9.3/main/pg_hba.conf` in `ol-db1` to enable replication to `ol-db0`:
```
host    replication     replicator      207.241.237.186/32      trust # <-- must be above 207.241.224.0/20
host    replication     replicator      207.241.224.0/20        md5
```
And then: `sudo pg_ctlcluster 9.3 main reload`

Setup 9.3 cluster on `ol-db0` **staging**:
> [!IMPORTANT]
> Urgent that you don't touch `ol-db1`
```
# ssh ol-db0.us.archive.org
sudo pg_createcluster 9.3 main --datadir=/2/postgresql/9.3/main
pg_lsclusters
```

Next, create an empty 18 cluster on `ol-db0`:
```
sudo pg_createcluster 18 main --datadir=/2/postgresql/18/main -- --no-data-checksums
pg_lsclusters
```

Next ensure `replicator` can connect and check the size of db1 prior to running the initial basedump:
```
psql -U replicator -h ol-db1 -d postgres -c "SELECT 1;" 2>&1
----------
        1
psql -U postgres -h ol-db1 -d postgres -c "SELECT pg_size_pretty(pg_database_size('openlibrary'));"
pg_size_pretty 
----------------
 884 GB
(1 row)
```

#### 9.3 Fresh Slate 

Here's where we ensure a **fresh slate** for psql 9.3:

Stop the new 9.3 cluster and clear out the ol-db0 psql 9.3 we just created and then run the backup. NB: You will need to uncomment the `rm` command after making darn well sure you're on the right machine otherwise probably need to find another job:
```
sudo pg_ctlcluster 9.3 main stop
# sudo rm -rf /2/postgresql/9.3/main/*
sudo chown -R postgres:postgres /2/postgresql/9.3/
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_basebackup -h ol-db1 -U replicator -D /2/postgresql/9.3/main --progress --verbose
```

Check to confirm we have a basebackup from `ol-db1` (9.3) → `ol-db0` (9.3):
```
du -sh /2/postgresql/9.3/main/
```

First, add configs needed by `pg_upgrade`:
```
# pg9.3 configs
sudo -u postgres mkdir -p /2/postgresql/9.3/main/conf.d
sudo -u postgres cp /etc/postgresql/9.3/main/postgresql.conf /2/postgresql/9.3/main/postgresql.conf
sudo -u postgres cp /etc/postgresql/9.3/main/pg_hba.conf /2/postgresql/9.3/main/pg_hba.conf
sudo -u postgres cp /etc/postgresql/9.3/main/pg_ident.conf /2/postgresql/9.3/main/pg_ident.conf
sudo -u postgres sed -i "s|hba_file = '/etc/postgresql/9.3/main/pg_hba.conf'|hba_file = '/2/postgresql/9.3/main/pg_hba.conf'|" /2/postgresql/9.3/main/postgresql.conf
sudo -u postgres sed -i "s|ident_file = '/etc/postgresql/9.3/main/pg_ident.conf'|ident_file = '/2/postgresql/9.3/main/pg_ident.conf'|" /2/postgresql/9.3/main/postgresql.conf

# pg18 configs
sudo -u postgres mkdir -p /2/postgresql/18/main/conf.d
sudo -u postgres cp /etc/postgresql/18/main/postgresql.conf /2/postgresql/18/main/postgresql.conf
sudo -u postgres cp /etc/postgresql/18/main/pg_hba.conf /2/postgresql/18/main/pg_hba.conf
sudo -u postgres cp /etc/postgresql/18/main/pg_ident.conf /2/postgresql/18/main/pg_ident.conf
sudo -u postgres sed -i "s|hba_file = '/etc/postgresql/18/main/pg_hba.conf'|hba_file = '/2/postgresql/18/main/pg_hba.conf'|" /2/postgresql/18/main/postgresql.conf
sudo -u postgres sed -i "s|ident_file = '/etc/postgresql/18/main/pg_ident.conf'|ident_file = '/2/postgresql/18/main/pg_ident.conf'|" /2/postgresql/18/main/postgresql.conf
```

This 9.3 is configured for replication so trying to start it will error:
```
sudo chown -R postgres:postgres /2/postgresql/9.3/main
sudo chmod 700 /2/postgresql/9.3/main
sudo pg_ctlcluster 9.3 main start
sudo tail -30 /var/log/postgresql/postgresql-9.3-main.log
```

At this point we have a 9.3 that's ready for either benchmarking or replication... 

## Benchmark / Trial-run

Now that we are setup we can benchmark `pg_upgrade --link` from 9.3 → 18

We will perform `pg_upgrade` directly on our basedump in 9.3 `/main`, making it unusable as a replica (as we'll need to destroy the `backup_label` and the data will be destroyed in the `--link` upgrade process)
> [!IMPORTANT]
> Once you remove the `backup_label`, this data won't be usable for replication and you'll have to repeat the **fresh slate** instructions above and resync the basedump from ol-db1.
```
sudo -u postgres rm /2/postgresql/9.3/main/backup_label
sudo pg_ctlcluster 9.3 main start
pg_lsclusters
```

If things do not start up cleanly, you may need to force a new WAL checkpoint.
> [!IMPORTANT] 
> On a production database this would be dangerous (potential data loss), but for benchmarking purposes it's fine — we just need the data to be accessible enough for pg_upgrade to work with it.
```
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_resetxlog -f /2/postgresql/9.3/main
sudo pg_ctlcluster 9.3 main start
```

Verify the data is accessible:
```
sudo -u postgres psql -p 5433 -d openlibrary -c "SELECT count(*) FROM pg_tables;"
```

Stop both 9.3 and 18 clusters (both must be stopped for pg_upgrade):
```
sudo pg_ctlcluster 9.3 main stop
sudo pg_ctlcluster 18 main stop
```

Move a directory not owned by postgres
```
cd /tmp
```

Run the pre-flight check first — this validates compatibility without touching any data:
```
sudo -u postgres /usr/lib/postgresql/18/bin/pg_upgrade \
  --old-bindir=/usr/lib/postgresql/9.3/bin \
  --new-bindir=/usr/lib/postgresql/18/bin \
  --old-datadir=/2/postgresql/9.3/main \
  --new-datadir=/2/postgresql/18/main \
  --link \
  --check
```

If --check passes, run the real upgrade and time it:
```
time sudo -u postgres /usr/lib/postgresql/18/bin/pg_upgrade \
  --old-bindir=/usr/lib/postgresql/9.3/bin \
  --new-bindir=/usr/lib/postgresql/18/bin \
  --old-datadir=/2/postgresql/9.3/main \
  --new-datadir=/2/postgresql/18/main \
  --link
```

Our test run results:
```
Upgrade Complete                                                                                                                                 
----------------                                                                                                                                 
Some statistics are not transferred by pg_upgrade.                                                                                               
Once you start the new server, consider running these two commands:                                                                              
    /usr/lib/postgresql/18/bin/vacuumdb --all --analyze-in-stages --missing-stats-only                                  
    /usr/lib/postgresql/18/bin/vacuumdb --all --analyze-only                                                                                     
Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh

real    0m9.214s
user    0m0.642s
sys     0m1.333s
```

Start the 18 cluster and verify:
```
sudo pg_ctlcluster 18 main start
psql -p 5434 -U postgres -d openlibrary -c "SELECT version();"
psql -p 5434 -U postgres -d openlibrary -c "SELECT count(*) FROM pg_tables;"
```

### Run Upkeep Tasks

These can be done once the db is back up (though some indices (like store) may need to be rebuilt before going live.

Run vacuum + analyze
```
time sudo -u postgres /usr/lib/postgresql/18/bin/vacuumdb --all --analyze-in-stages -p 5434
```

```
vacuumdb: processing database "coverstore": Generating minimal optimizer statistics (1 target)
vacuumdb: processing database "openlibrary": Generating minimal optimizer statistics (1 target)
vacuumdb: processing database "postgres": Generating minimal optimizer statistics (1 target)
vacuumdb: processing database "template1": Generating minimal optimizer statistics (1 target)
vacuumdb: processing database "coverstore": Generating medium optimizer statistics (10 targets)
vacuumdb: processing database "openlibrary": Generating medium optimizer statistics (10 targets)
vacuumdb: processing database "postgres": Generating medium optimizer statistics (10 targets)
vacuumdb: processing database "template1": Generating medium optimizer statistics (10 targets)
vacuumdb: processing database "coverstore": Generating default (full) optimizer statistics
vacuumdb: processing database "openlibrary": Generating default (full) optimizer statistics
vacuumdb: processing database "postgres": Generating default (full) optimizer statistics
vacuumdb: processing database "template1": Generating default (full) optimizer statistics

real    1m22.844s
```

When running a query against store, we found that at least one index `store_index` had to be rebuilt..
```
# Running a re-index on at least `store_index` was necessary and took ~40min (can be done online)
# time sudo -u postgres psql -p 5434 -d openlibrary -c "REINDEX TABLE store_index;"
# REINDEX
# real    39m30.654s
# To rebuild all indices:
time sudo -u postgres psql -p 5434 -d openlibrary -c "REINDEX (CONCURRENTLY) DATABASE openlibrary;"
```

Make sure 18 is running and set to read-only for testing against `ol-db0`:
```
sudo -u postgres psql -p 5434 -c "SELECT version();"
```

Output:
```
version                                                           
------------------------------------------
PostgreSQL 18.3 (Debian 18.3-1.pgdg12+1) ...
(1 row)
```

```
sudo -u postgres psql -p 5434 -c "ALTER SYSTEM SET default_transaction_read_only = on;"
sudo -u postgres psql -p 5434 -c "SELECT pg_reload_conf();"
```

Output:
```
ALTER SYSTEM
 pg_reload_conf 
----------------
 t
(1 row)
```

### Phase 2: Production cutover

If you just ran benchmark upgrade, our 9.3 should be trashed. We are going to revisit the **Clean Slate** protocol:
```
# Stop 9.3
sudo pg_ctlcluster 9.3 main stop 2>/dev/null

# Delete the data for 9.3 and ensure permissions are OK
sudo rm -rf /2/postgresql/9.3/main
sudo mkdir /2/postgresql/9.3/main
sudo chown postgres:postgres /2/postgresql/9.3/main
sudo chmod 700 /2/postgresql/9.3/main
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_basebackup -h ol-db1 -U replicator -D /2/postgresql/9.3/main --progress --verbose

# Refetch basebackup and set permissions
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_basebackup -h ol-db1 -U replicator -D /2/postgresql/9.3/main --progress --verbose
sudo chmod 700 /2/postgresql/9.3/main
```

Next, complete setting up ol-db0 as a streaming replica of ol-db1 (9.3 → 9.3) and let it sync fully:
```
sudo -u postgres sed -i "s/#hot_standby = off/hot_standby = on/" /etc/postgresql/9.3/main/postgresql.conf
sudo -u postgres sed -i "s/max_connections = 100/max_connections = 500/" /etc/postgresql/9.3/main/postgresql.conf
sudo -u postgres tee /2/postgresql/9.3/main/recovery.conf > /dev/null <<EOF
standby_mode = on
primary_conninfo = 'host=ol-db1 port=5432 user=replicator'
EOF
sudo pg_ctlcluster 9.3 main start
sudo tail -10 /var/log/postgresql/postgresql-9.3-main.log
```

Verify ol-db0 9.3 is setup as a replica in ol-db1:
```
psql -U postgres -h ol-db1 -d postgres -c "SELECT client_addr, state FROM pg_stat_replication;"
```

Output:
```
   client_addr   |   state   | sent_location | replay_location 
-----------------+-----------+---------------+-----------------
 207.241.229.140 | streaming | 1CE6/9307D050 | 1CE6/93076958
 207.241.237.186 | streaming | 1CE6/9307D050 | 1CE6/93076958 <-- that's ol-db0 9.3
(2 rows)
```

TODO:
- Schedule maintenance window
- Put ol-db1 in read-only mode (default_transaction_read_only = on, reload)
- Wait for ol-db0 to catch up completely (replay lag = 0)
- Stop replication on ol-db0, promote to standalone
- Stop the 9.3 cluster on ol-db0
- Create a backup via `cp -al /2/postgresql/9.3/main /2/postgresql/9.3/main-backup`
- Run pg_upgrade --link from 9.3 → 18 (should take the time you measured in Phase 1)
- Start the 18 cluster on ol-db0
- Run analyze_new_cluster.sh
- Consider performing bigint and bigserial upgrades
- Smoke test the database
- Point the app at ol-db0

**Comment by mekarpeles** [comment]
Updates:
- we decided on an approach: replicate ol-db1 9.3 to ol-db0 9.3 and then upgrade in place
- we ran a benchmark test of this approach
  - created a basedump from ol-db1 9.3 to ol-db0 9.3 -- not full replication
  - ran in-place (`--link`) pg_upgrade (which took ~10 second) from 9.3 to 18
  - there were some index issues (e.g. store table)
     - unsure if because of basedump approach or upgrade -- but this can be fixed post-upgrade while online
  - running vacuums / analyze after migration (while online) took ~2 min
- We now have a working ol-db0 18 that is only a few days old; @cdrini to setup ol-dev1 for testing
- We have since blown away the now broken ol-db0 9.3 basedump (that we used to upgrade to ol-db0 18) and have re-done the basedump and set up actual replication (from ol-db1 9.3 -> ol-db0 9.3) that will be used in the production cutover run
- We have about 90gb of space left on disk (should be fine once we delete benchmark/testing ol-db0 pg 18)

**Comment by mekarpeles** [comment]
Also related: github.com/internetarchive/olsystem/pull/318

We'll need ferm rules to allow test ports for pg18

**Comment by mekarpeles** [comment]
# PostgreSQL 9.3 → 18 Production Cutover Playbook

## Prep
- [x] ol-db1 `pg_hba.conf` allows replication trust entry for ol-db0 (`207.241.237.186/32`)
- [x] Make sure 9.3 `/etc/postgresql/9.3/main/postgresql.conf` has `hot_standby = on` and `max_connections = 500` @cdrini 
- [x] Run autovacuum on 18 to clean up space (for 9.3) @mekarpeles 
- [x] Update 18 `/etc/postgresql/18/main/pg_hba.conf` has ol-dev1 + ol-web* + ol-home0 `trust` @cdrini 
- [x] Update ol-db0 ferm rules for cluster access @cdrini 
- [x] Check-in code that allows `port` to be specified in infobase.yml @cdrini -- link to PR


## Monday: Reset 9.3 As Replica (from basebackup)

```sh
# Clean Slate  9.3:
sudo pg_ctlcluster 9.3 main stop 2>/dev/null
sudo rm -rf /2/postgresql/9.3/main
sudo mkdir /2/postgresql/9.3/main
sudo chown postgres:postgres /2/postgresql/9.3/main
sudo chmod 700 /2/postgresql/9.3/main

# Kick off basebackup
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_basebackup -h ol-db1 -U replicator -D /2/postgresql/9.3/main --progress --verbose
sudo chmod 700 /2/postgresql/9.3/main

# Setup replication
sudo -u postgres tee /2/postgresql/9.3/main/recovery.conf > /dev/null <<EOF
standby_mode = on
primary_conninfo = 'host=ol-db1 port=5432 user=replicator'
EOF
sudo pg_ctlcluster 9.3 main start

# Verify replication is streaming:
sudo -u postgres /usr/lib/postgresql/18/bin/psql -h ol-db1 -d postgres -c "SELECT client_addr, state, sent_location, replay_location FROM pg_stat_replication;"

# Copy 9.3 configs for upgrade
sudo -u postgres cp /etc/postgresql/9.3/main/postgresql.conf /2/postgresql/9.3/main/postgresql.conf
sudo -u postgres cp /etc/postgresql/9.3/main/pg_hba.conf /2/postgresql/9.3/main/pg_hba.conf
sudo -u postgres cp /etc/postgresql/9.3/main/pg_ident.conf /2/postgresql/9.3/main/pg_ident.conf
sudo -u postgres sed -i "s|hba_file = '/etc/postgresql/9.3/main/pg_hba.conf'|hba_file = '/2/postgresql/9.3/main/pg_hba.conf'|" /2/postgresql/9.3/main/postgresql.conf
sudo -u postgres sed -i "s|ident_file = '/etc/postgresql/9.3/main/pg_ident.conf'|ident_file = '/2/postgresql/9.3/main/pg_ident.conf'|" /2/postgresql/9.3/main/postgresql.conf
sudo -u postgres mkdir -p /2/postgresql/9.3/main/conf.d
```

- [x] Setup staging 9.3 w/ replication; confirm ol-db0 (`207.241.237.186`) shows state = `streaming`.

## Wednesday: Reset 18 From Clean Slate
 
```sh
# Clean Slate 18
sudo pg_ctlcluster 18 main stop
sudo pg_dropcluster 18 main --stop
sudo rm -rf /2/postgresql/18/main
sudo mkdir -p /2/postgresql/18/main
sudo chown postgres:postgres /2/postgresql/18/main
sudo chmod 700 /2/postgresql/18/main

# Recreate 18 Cluster
sudo pg_createcluster 18 main --datadir=/2/postgresql/18/main -- --no-data-checksums

# Seed configs into new cluster
sudo -u postgres cp /etc/postgresql/18/main/postgresql.conf /2/postgresql/18/main/
sudo -u postgres cp /etc/postgresql/18/main/pg_hba.conf /2/postgresql/18/main/
sudo -u postgres cp /etc/postgresql/18/main/pg_ident.conf /2/postgresql/18/main/
sudo -u postgres sed -i "s|hba_file = '/etc/postgresql/18/main/pg_hba.conf'|hba_file = '/2/postgresql/18/main/pg_hba.conf'|" /2/postgresql/18/main/postgresql.conf
sudo -u postgres sed -i "s|ident_file = '/etc/postgresql/18/main/pg_ident.conf'|ident_file = '/2/postgresql/18/main/pg_ident.conf'|" /2/postgresql/18/main/postgresql.conf
sudo -u postgres mkdir -p /2/postgresql/18/main/conf.d
```

## Thursday: Phase 2: Production Cutover

Expectations:
- staging 9.3 is an up-to-date replica with prod
- staging 18 has been wiped
- staging 9.3 + 18 have configs primed for upgrade

> **Estimated downtime: ~15-30 minutes** (based on 9-second benchmark upgrade time, plus promotion, verification, and app switchover)

### Add maintenance banner to openlibrary.org

Coordinate with team. Announce maintenance window.

### 2.1 Put ol-db1 in read-only mode

On ol-db1:
```
sudo -u postgres psql -c "ALTER SYSTEM SET default_transaction_read_only = on;"
sudo -u postgres psql -c "SELECT pg_reload_conf();"
```

Verify:
```
sudo -u postgres psql -d openlibrary -c "CREATE TEMP TABLE test_readonly (id int);"
-- Should fail with: ERROR: cannot execute CREATE TABLE in a read-only transaction
```

### Wait for ol-db0 replica to fully catch up

On ol-db1:
```
psql -U postgres -h ol-db1 -d postgres -c "SELECT client_addr, state, sent_location, replay_location FROM pg_stat_replication WHERE client_addr = '207.241.237.186';"
```

Wait until `sent_location` equals `replay_location`. This should be near-instant since ol-db1 is read-only.

### Promote ol-db0 9.3 to standalone

```sh
sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_ctl promote -D /2/postgresql/9.3/main

# Wait for promotion to complete:
sleep 5
sudo ls /2/postgresql/9.3/main/recovery.done
# Should exist — confirms promotion succeeded
sudo tail -5 /var/log/postgresql/postgresql-9.3-main.log
```

- [x] Verify promotion in logs and then restart

```sh
# Remove recovery.done
sudo pg_ctlcluster 9.3 main stop
sudo -u postgres rm -f /2/postgresql/9.3/main/recovery.done
```

### Run pg_upgrade (w/ pre-flight check)

```
pg_lsclusters
# Both 9.3 and 18 should show "down"

cd /tmp
sudo -u postgres /usr/lib/postgresql/18/bin/pg_upgrade \
  --old-bindir=/usr/lib/postgresql/9.3/bin \
  --new-bindir=/usr/lib/postgresql/18/bin \
  --old-datadir=/2/postgresql/9.3/main \
  --new-datadir=/2/postgresql/18/main \
  --link \
  --check
```

> **If check fails:** Do NOT proceed. Investigate. ol-db1 is still available in read-only mode. Worst case: turn ol-db1 read-write again, redo basebackup, try again another day.

```
cd /tmp
time sudo -u postgres /usr/lib/postgresql/18/bin/pg_upgrade \
  --old-bindir=/usr/lib/postgresql/9.3/bin \
  --new-bindir=/usr/lib/postgresql/18/bin \
  --old-datadir=/2/postgresql/9.3/main \
  --new-datadir=/2/postgresql/18/main \
  --link
```

Expected time: ~10 seconds based on benchmark.

### Start PostgreSQL 18 & read-only

```
sudo pg_ctlcluster 18 main start
# Make read-only
sudo -u postgres psql -p 5432 -c "ALTER SYSTEM SET default_transaction_read_only = on;"
sudo -u postgres psql -p 5432 -c "SELECT pg_reload_conf();"
```

### 2.9 Smoke test

```
sudo -u postgres psql -p 5432 -d openlibrary -c "SELECT version();"
sudo -u postgres psql -p 5432 -d openlibrary -c "SELECT count(*) FROM pg_tables;"
sudo -u postgres psql -p 5432 -d openlibrary -c "SELECT count(*) FROM thing;"
```

Test from ol-dev1:
```
psql -h ol-db0.us.archive.org -p 5432 -U openlibrary openlibrary -c "SELECT version();"
```

### Point application to ol-db0

Update application config / DNS / connection strings to point at ol-db0 instead of ol-db1.

### Remove maintenance banner

### Turn off read-only on ol-db0 18 (if it was set)

```
sudo -u postgres psql -p 5432 -c "ALTER SYSTEM SET default_transaction_read_only = off;"
sudo -u postgres psql -p 5432 -c "SELECT pg_reload_conf();"
```

---

## Phase 3: Post-cutover housekeeping (database online, no downtime)

### Rebuild optimizer statistics

The upgrade should recommend tasks to run

```
sudo -u postgres /usr/lib/postgresql/18/bin/vacuumdb --all --analyze-in-stages -p 5432
```

### Reindex concurrently

```
sudo -u postgres psql -p 5432 -d openlibrary -c "REINDEX (CONCURRENTLY) DATABASE openlibrary;"
```

### Enable data checksums (optional, requires brief stop)

```
sudo pg_ctlcluster 18 main stop
sudo -u postgres /usr/lib/postgresql/18/bin/pg_checksums --enable -D /2/postgresql/18/main
sudo pg_ctlcluster 18 main start
```

### Clean up old data

Only after everything is verified working:
```
sudo rm -rf /2/postgresql/9.3/main
sudo apt-get remove postgresql-9.3 postgresql-client-9.3
```

---

## Rollback Plan

At any point before step 2.10 (pointing app at ol-db0):

1. Stop 18 on ol-db0: `sudo pg_ctlcluster 18 main stop`
2. Turn ol-db1 read-write:
   ```
   # On ol-db1:
   sudo -u postgres psql -c "ALTER SYSTEM SET default_transaction_read_only = off;"
   sudo -u postgres psql -c "SELECT pg_reload_conf();"
   ```
3. ol-db1 is back as production. Investigate what went wrong.
4. When ready to try again: redo basebackup on ol-db0, set up replication, repeat Phase 2.

After step 2.10: application is already pointing at ol-db0. Rollback requires pointing the app back at ol-db1 and accepting any writes made to ol-db0 18 are lost. Minimize this risk by thorough smoke testing before 2.10.

**Comment by mekarpeles** [comment]
Open Library production is now running Postgres 18
- Total prep time 30 min
- Total upgrade time 10 min
- Total testing time 5 minutes
- Total downtime ~5 minutes (restarting docker)
Total Time in read only: ~45 min

We now have 500gb of free space on our db server (instead of ~100gb)

**Comment by mekarpeles** [comment]
## Next Steps

1. We still have indices we may want to change (e.g. int -> bigint) #10921 #12009 
2. We need to now setup ol-db3 as replica
3. We need to update our cron jobs to move backups to *not* ol-backup0??? (which means we need an ol-backup1?)
4. Some plan for decomissioning ol-db1 + ol-db2; cc @abezella

**Comment by cclauss** [comment]
Awesome!!!
