### ISSUE TITLE
Provisioning & Deployment Plan

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#5757]
Like #4423 
### Todo:
* [x] #5402 Again!
    * [x] Fixed in #6163
* [x] #3386
* [x] #5474 
* [x] #6000 
* [x] #5843
* [ ] #5910
* [ ] #4275
---
### Done
1. #5418 `covers_nginx` and `web_nginx`
    * [x] internetarchive/olsystem#137
    * [x] Not needed... #5840
    * [x] ~#5789~ --> #5854
    * [x] #4725
    * [x] Replace ~internetarchive/olsystem#139~ which __was reverted__.
2. #2036 for mem0, mem1, mem2
    * [x] internetarchive/olsystem#138
    * [x] Sanity check by running ol-mem0 WITHOUT ol-mem3 and ol-mem4
    * [x] internetarchive/olsystem#144
    * [x] internetarchive/olsystem#145
3. Data dumps and sitemaps cron jobs running on Docker-based `ol-home0`
    * [Data dump issues](https://github.com/internetarchive/openlibrary/search?q=data+dump&type=issues)
        * [x] #5402
        * [x] #5909
        * [x] #5931
    * [Sitemap issues](https://github.com/internetarchive/openlibrary/search?q=sitemap&type=issues)
        * [x] #5674 
        * [x] internetarchive/olsystem#143
        * [x] #5720
        * [ ] OK, Now do the same for `ol-www0` instead of `ol-www1`.  Should it be push or pull?
4. #4252  <-- ___current focus___
    * [x] #4723
5. #5474 
6. #4275
7. #5843
8. #5898
    * [x] internetarchive/infogami#187
    * [x] Deploy with #5952
    * [ ] #5910
* [x] #3215 
* [x] #5823
* [x] #5938

---

* [x] memcache let's just manually add mem0 to the pool and ensure it fills up (and then we can do the same for the others)
* [x] manually running data dump + look for errors (helps ensure we have the right working command) -- assuming `2.` works, we'll have a good data dump on disk
     * `ls /home/cclauss/test_dumps` --> ol_dump_ratings_2021-11-10.txt.gz  ol_dump_reading-log_2021-11-10.txt.gz
* [x] following `2.`, let's not do the data dump removal (even though we do want this in the final solution) & attempt to run the same command via cron (but preferably disabling the most expensive parts of `oldump.sh` -- i.e. data dump -- which should already be done from `2.` if we don't see errors, then rerun `3.` with the correct `2>&1` (or whatever it calls for). I was hitting a "no package web"
    * `ModuleNotFoundError: No module named 'web'` was from running the job outside of Docker.
* [x] we're done when we have an end-to-end successful data dump generation from `crontab` which includes the (a) `+x` (b) `rm dir` (which we'll add back after `3.`), (c) and the resulting files upload to the archive.org item
* [x] we should save the data dumps from `2.` and the changes to `oldump.sh` from `3.` because both will make our life much easier for `sitemaps` (which happens at the bottom of that script)

**Comment by cclauss** [comment]
8 dec 2021 -- Action Items:
- [ ] Drini: Ping network magicians for our nginx config -- We had to remove some things from our `public` nginx conf ; confirm with Tracey, Mek, Andy.
    - Why is nginx complaining?!?
    - Is having the public_nginx.conf setup kosher?
    - How do we have two services on 80?
- [ ] Drini: Add www0 to deploy.sh
- [ ] Kick off deploy with new olbase image
- [ ] Chris: Sitemaps/logs testing with www0
- [ ] Chris: To apply `covers: deploy: replicas: 2` + `version: 3.8` docker-compose changes?
    - Update https://github.com/internetarchive/openlibrary/blob/master/scripts/deployment/restart_servers.sh ; no longer need --scale manually!

**Comment by mekarpeles** [comment]
Sufficiently solved; remaining tasks to be outlined in #4423
