### ISSUE TITLE
Update all translations

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5767]
### Describe the problem that you'd like solved

Much untranslated copy has been added to Open Library recently.  Our translations have not been updated to reflect the new changes.

### Proposal & Constraints

All of our translations should be updated with the new copy.

- [x] @dcapillae Update Spanish translation (`/openlibrary/i18n/es/messages.po`)
- [ ] Update Czech translation (`/openlibrary/i18n/cs/messages.po`)
- [x] Update German translation (`/openlibrary/i18n/de/messages.po`)
- [x] @lephemere Update French translation (`/openlibrary/i18n/fr/messages.po`)
- [x] @milotype Update Croatian translation (`/openlibrary/i18n/hr/messages.po`)
- [ ] Update Japanese translation (`/openlibrary/i18n/ja/messages.po`)
- [ ] Update Polish translation (`/openlibrary/i18n/pl/messages.po`)

### Additional context

`.po` file needs to be updated with new copy before new translations can be made.  Instructions for updating `.po` files can be found here: https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n#updating-an-existing-language

**Comment by lephemere** [comment]
Hi, I'm working on the french translation.
