### ISSUE TITLE
Remove client-side availability checking availability.js, switch to server-side

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5803]
This old JS file has been replaced in most places, but still needs to be removed from lists pages and https://openlibrary.org/stats/readinglog .

- [ ] Change lists pages to use LoanStatus
- [ ] Change https://openlibrary.org/stats/readinglog to use loan status
- [ ] Confirm availability.js isn't used by carousel "loadMore" rendering
- [ ] Delete availability.js

### Stakeholders
@mekarpeles
