### ISSUE TITLE
Improve Open Library's HTTP Observatory score

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5807]
### Describe the problem that you'd like solved

Open Library is failing its HTTP Observatory scan, which is used to determine areas in which our HTTP traffic can be more secure.  Results can be found here: https://observatory.mozilla.org/analyze/openlibrary.org

### Proposal & Constraints

We can pass our tests by ensuring that the following items are properly implemented:

- [ ] Implement Content Security Policy (CSP) header
- [ ] Implement HTTP Strict Transport Security header
- [ ] Implement X-Content-Type-Options header
- [ ] Implement X-Frame-Options (XFO) header
- [ ] Implement X-XSS-Protection header

### Additional context

More information about each unimplemented header can be found at the Observatory results page.

**Comment by b2pacific** [comment]
@jimchamp I would like to work on this issue. Can you assign it to me?

**Comment by b2pacific** [comment]
@jimchamp
