### ISSUE TITLE
BookTrails.us / TheBestBookOn MVP

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5830]
See also: https://docs.google.com/document/u/1/d/1Ddeg-fWWZ0iCFzVtZR0yGY_vCPttIUrd4tCIWwvYj6g/edit

Outstanding tasks required for The Best Book On MVP:
- [ ] Implement new data models for recommendations and book graph
- [ ] Seed DB with Open Syllabus data
- [ ] Ensure that SQLAlchemy Queue Pool limit errors have been resolved
- [ ] Decorate recommendations with Open Library's book tag data (optional for MVP)

### Stakeholders
@mekarpeles
