### ISSUE TITLE
Trusted Book Providers blog post

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5837]
- [x] @mekarpeles First draft
- [x] @cdrini Second draft
- [x] @cdrini Get proofread by IA folks
- [x] @cdrini Publish! https://blog.openlibrary.org/2021/12/20/introducing-trusted-book-providers/
- [x] @mek Advertise on Twitter
- [x] @cdrini Sync with Chris Freeland to include in email newsletter

**Comment by mekarpeles** [comment]
https://twitter.com/mekarpeles/status/1473060001207914496
