### ISSUE TITLE
Improve the state of Python linting

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5843]
Python linting is currently a problem. Everyone is _constantly_ being hit with linting issues, creating new commits to fix linting issues, either wasting manual time to fix issues or using automatic commands that make changes to loads of unrelated places. And it makes our git history a mess, and diffs/PRs hard to read.

I think the end goal we want is: Easy way to automatically apply linting _before_ a commit happens.

A subtask of #4776

Steps to get there:

- [x] Make our current lint-diff less aggressive while we improve the flow
    - @cclauss : change lint-diff to `flake8 --select=E9,F63,F7,F82` ; only catch syntax errors and undefined
    - [x] #5842
    - [x] #5844
- [x] #5836 Black the entire codebase
    - [x] `/tests` #5338
    - [x] `/scripts` #5841
    - [x] Integration tests #5850
    - [x] #5859
    - [x] #5864
    - [x] `/openlibrary` #5855
- [x] @RayBB Update gitpod to use pre-commit hooks #5851
- [x] #5847 
- [x] #5849
- [x] #5870
- [x] Cause any/all lint issues to fail GitHub CI #5848
- [x] Investigate: Do we want to auto-fix in GitHub CI?  Or pre-commit-ci.com?
- [ ] Update setup docs to make enabling pre-commit hooks a part of the flow
- [ ] Update docs with instructions on how to auto-lint-on-save for most popular editors
    - [ ] vscode
    - [ ] pycharm
- [ ] Profit?

### Stakeholders
@cclauss @RayBB @jimman2003

**Comment by cclauss** [comment]
Closing because these tools are now all in place but need to be documented... #6227
