### ISSUE TITLE
Automate steps to move solr from solrbuilder server to production server

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5877]
This process is annoying and finnicky; getting automated would save a good chunk of time and reduce risk.

- [x] Run steps manually (done in #5493 )
- [x] Write out as bash, and run each step-by-step (done in #5502)
    - [ ] Open draft PR 
- [ ] Try running the entire script! Do as part of #5827
