### ISSUE TITLE
Retire ol-www1 for ol-www0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6001]
Fixes: #4252

- [x] Update DNS for openlibrary to point to new server
- [x] Remove www1 docs in Deployment Guide (no longer needed!)
- [x] Update to ol-www0 in olsystem, nagios, etc.
    - [x] #7781
    - [x] internetarchive/olsystem#170
    - [x] Opened a pull request on our Nagios server -- https://git.archive.org/ia/nagios/-/merge_requests/16 (merged)
- [x] Confirm there are no files in /1/ we want to backup -- copied `sitemaps` from `ol-www1` --> `ol-www0`
- [x] Take `ol-www1` offline (but don't delete) -- literally, turn the vm off (ganeti)
- [x] Monitor for a week -- Until **26 April 2023**...
- [x] Remove `ol-www1`
    - [x] Merge https://git.archive.org/ia/nagios/-/merge_requests/17 (merged)
    - [x] Request decommission of the `ol-www1` hardware
