### ISSUE TITLE
Book Page Usability

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6097]
This is an epic for tracking issues in support of our Q1 book page usability improvements.  New issues will be added as decisions are made regarding this project.

### Tasks
- [x] Add "Lists" link to navbar (#6096)
- [x] Remove redundant edition description (#6107)
- [ ] Navbar additions and improvements (#6170)
- [x] Capture analytics on subject link clicks (#6106)
- [x] Make table of contents collapsible (#6171)
- [x] Make work descriptions collapsible (#6172)

### To discuss
- [ ] Replace preview button with link (issue pending)
- [ ] Improve table of contents formatting (issue pending) -- community issue

More good first issues + decisions here (please wait for me to create issues for these)
https://docs.google.com/document/d/1buJASy3MbxQPYstoUGW_tAwC7UYTKfcejUm8xXsfAIc/edit#heading=h.xlw8k5lwk383
