### ISSUE TITLE
Book page navbar improvements

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6170]
### Describe the problem that you'd like solved

The navbar found on our book pages has a number of issues:
1. It is not prominently displayed on the page.
2. It overflows on mobile views.
3. It is missing a link to the related works carousels.

### Proposal & Constraints

The following requirements must be met in order to close this issue:

- [x] Navbar should be placed below the title component. More specifically, it should appear between the `.readers-stats` component and the `.edition-omniline` component.
- [x] #6436
- [x] #6431 
- [x] Order of navbar links should be updated: `Overview | View X Editions | This Edition | Reviews | Lists | Related Books`
- [x] "Overview" link should bring patrons to the top of the page.

**Comment by jimchamp** [comment]
Closing, as this looks to be complete.
