### ISSUE TITLE
Search: Editions in Solr

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6377]
Epic to track getting editions into solr. This would impact a lot of already open issues, but is kind of enough of a technically challenging piece that I want somewhere to keep notes separately from the more user-facing goals.

### Pieces
- Reindexing code - the code needed to convert OL data into the data format needed in solr
    - [x] #6119 
- Search UI code - the code needed to select and display the matching edition
    - [x] #6476

### Gameplan
- [x] Create proof of concept that can run locally
    - See #6119 
    - Works and lets you search for editions! A number of things are broken though; namely it's not selecting the most available edition when multiple editions match the user's query.
- [x] Do a full re-index with the new editions-enabled data dump code on ol-solr1
    - Available for download here: https://archive.org/details/ol-solrbuilder-2022-04-01
- [x] Fix: Solr updater not handling updating of editions
    - [x] #6393
- [x] Run solr-next-updater with editions indexing code against ol-solr1
- [x] Test performance
    - We're adding a LOT more records into solr; test it doesn't have a huge impact on performance
    - [x] Add some more solr metrics to statsd
    - [x] Increase ram to 10g to match prod + enable haproxy
    - [x] Connect ol-solr1 to testing.openlibrary.org
    - [x] Connecting ol-web1 to ol-solr1 for a bit
    - [x] Connecting ol-web1 + ol-web2 to ol-solr1 for a bit
    - [x] Monitor statsd, also sentry
    - [x] Switch web heads back to solr0
- [x] Fix blocking issues
- [x] Place editions display code on testing.openlibrary.org and leave both on there for longer
- [x] Connect testing to new solr with new edition rendering search UI code
- [x] Fix any issues
- [x] Do another full re-index
- [x] Deploy solr with editions, but not UI changes
- [x] Patch deploy Search query/UI changes and monitor performance
- [x] Fix any issues
    - [x] space before ` : ` in search causes error https://sentry.archive.org/organizations/ia-ux/issues/47462
    - [x] parse errors in `title=` field cause errors
    - [x] API should not return editions by default -- perf issue if many works fetched!
    - [x] Works without editions aren't matching (eg https://openlibrary.org/search?q=%22international+law+of+economic+migration%22&mode=everything should show https://openlibrary.org/works/OL8938640W/The_international_law_of_economic_migration as one of the results
    - [x] Searches for isbns with solr editions disabled doesn't work
return https://openlibrary.org/works/OL27967042W/A_Charmed_Life?edition=ia%3Aunavidamagicalae0000brid )
- [x] Merge Search query/UI changes -- disabled by default due to perf issues
- [x] #7253
    - [x] DRY up code so I can get editions in all the places

### Know issues
- [x] solr-updater not handling removal of editions; Maybe delete work/editions before updating record?
     - This is a problem because solr requires that nested documents have unique `key`s, but doesn't enforce it. So I believe I got some errors about this a while back.
     - #6393
- [x] #6392
- [x] Add `has_fulltext` property to `update_edition.py` that calls `get_ebook_info`
- [x] #6564
    - Not choosing most available edition when multiple editions match
    - [x] #6563
    - [x] #6559
- [x] Need to be able to prefer user's language, otherwise queries like "Harry potter" will return things in whatever language!
    - [x] #5997
    - [x] When no language specified, boost the user's language
- [x] Need to be able to filter works based on editions matches! E.g. `publisher:librivox language:fre` should have fewer results than the current site!
    - Devil is in the details on this one though... Hard to get right in the general case without either searching at the edition (which doesn't have a lot of data); which might mean copying eg subjects data to the edition records (which is a LOT of new/dupe data...). Maybe some solr magic somewhere to exclude results if the subquery fails...?
- [x] Carousels are broken
- [x] Carousels on testing/staging show wrong availability? Not sure if related
- [x] Author field not working (eg https://testing.openlibrary.org/search?author=robert+holdstock )
- [x] Non prefixed queries containing author names will never match an edition because author terms aren't stored on solr editions
    - Make non-prefixed pieces non-mandatory
- [x] Display work title in search card for librarians
- [x] Escape question marks
- [x] Fix spaces after search field not working https://testing.openlibrary.org/search?q=title%3A+%22three+body+problem%22&mode=everything
- [x] `title:foo` does not correctly select a matching edition if the matching text is the in the subtitle
    - Fix in future PR; this will require a full reindex.
- [x] Lang facet not causing filters to apply
- [x] Title field searches 

### Side quests / sub-pieces
- [x] #6378
- [x] #6465
    - No longer needed with modern solr which output JSON, and quite a headache with nested documents
    - [x] #6466
- [x] #6379
    - [x] #6591
- [x] #6421
    - Implement better retry logic for solr POST requests ; getting lots of failures during "catchup" phase
- [x] #6425
- Reduce facets visible on search page for performance
     - [x] Re-order so the more useful facets are higher
     - [x] Add GA (for future; not blocking on this)
     - This has a pretty drastic impact on page perf, especially with the new more complicated queries

<a name="goals"></a>
### Goals

- [x] #448 , #2064 Search results should show the best matching edition title/cover
     - e.g. Searching for `language:fre` should show the french edition of each item as opposed to currently https://openlibrary.org/search?q=language%3Afre
- [x] #6041 
- [x] #6226

### Future Work
- #7252
- #7267
- #7247
- #7270
- #6836
- #7268
- #7269
- #7271
- #6712
- #7272
- -title:foo bar should be parsed as -title:(foo bar), not -title:(foo) bar
- #7273
    - Searching for eg -language:eng will exclude all works that have any English edition! Not what we want usually
- #7274
- #7275
- #7278
- Re-think wording of ebook_access enum (requires full reindex)
- #7277
- #7276

**Comment by cdrini** [comment]
Ok, getting ready for first test! All the issues have been fixed. This will have no UI changes, just test performance with solr going from 38M documents to 74M. I'll also be starting up `solr-next-updater` with the editions indexing code, so we'll also be testing that running.

Starting now by pulling down #6119 onto ol-home0 's solr-next-updater container:

```sh
cd /opt/openlibrary
export COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml"
export HOSTNAME="$HOSTNAME"

# Create a new base image with the updated code
docker build -t olbase:solr-next-updater - <<'EOF'
    FROM 'openlibrary/olbase:latest'

    # 'Add' let's us break the cache only if the diff has changed! How cool?
    ADD "https://github.com/internetarchive/openlibrary/pull/6119.diff" 6119.diff
    RUN curl -L 'https://github.com/internetarchive/openlibrary/pull/6119.diff' | git apply

    # Confirm the right stuff has indeed changed
    # Fix git being broken for some reason -_-
    RUN export HEAD="$(cat .git/refs/heads/master)" && \
        git remote rm origin && \
        git remote rm cclauss && \
        git remote add origin "https://github.com/internetarchive/openlibrary" && \
        git fetch origin $HEAD && \
        git diff --compact-summary $HEAD
EOF

# Set solr state file date
docker-compose run --rm solr-next-updater bash -c "
    echo '2022-03-29:0' > /solr-updater-data/solr-next-update.offset
"
docker-compose run --rm solr-next-updater bash -c 'head /solr-updater-data/* && echo'

# Start it up!
OLIMAGE='olbase:solr-next-updater' docker-compose up -d solr-next-updater

# Check logs
docker-compose logs --tail=100 -f solr-next-updater

# Check how caught up we are
curl "ol-home:7000/openlibrary.org/log/$(docker exec openlibrary_solr-next-updater_1 cat /solr-updater-data/solr-next-update.offset)?limit=1"
```

Useful commands:

```sh
# Stop it
docker stop openlibrary_solr-next-updater_1

# Make a change to the code for a bit without having the thing running
sudo sed -i 's:docker/ol-solr-updater-start.sh:tail -f:' docker-compose.production.yml
OLIMAGE='olbase:solr-next-updater' docker-compose up -d solr-next-updater
docker-compose exec solr-next-updater bash
### changes...
# inside the container run ./docker/ol-docker-start.sh
git checkout -- docker-compose.production.yml
```

Monitor solr from your machine with `ssh -L 18984:ol-solr1:8984 ...`, and monitor perf at https://wwwb-grafana0.us.archive.org/d/000000174/ol-solr0?orgId=1&from=now-3h&to=now&refresh=1m&var-fqhostname=ol-solr1_us_archive_org&var-resolution=30m .

Just kicked off solr-updater; waiting for it to catch up now. So far looks good!

**Comment by cdrini** [comment]
Scratch that; left it catch up. Will check to see where it is tomorrow

**Comment by cdrini** [comment]
Ok, did some counts:

<html><body>
<google-sheets-html-origin><style type="text/css"></style>

Class | Query | solr-prod | solr-next | Diff
-- | -- | -- | -- | --
authors | type:author | 9,175,045 | 9,517,789 | 342,744
editions | type:edition | 0 | 34,742,669 | 34,742,669
orphans | type:work AND key:*M | 2,253,354 | 2,234,867 | -18,487
subjects | type:subject | 3,026,213 | 3,055,549 | 29,336
total | `*:*` | 38,387,729 | 74,562,069 | 36,174,340
works | type:work AND key:*W | 23,933,112 | 25,011,189 | 1,078,077


</body>
</html>

The new solr looks better than the current on all counts, so definitely good enough for testing. Note we will probably not be using this solr for production anyways, but will do another full reindex later which will be the final guy.

Above ~generated by `deno run --allow-net` of :

```ts
const solrs = [
    { name: 'solr-prod', host: 'localhost:28984' },
    { name: 'solr-next', host: 'localhost:18984'}
];

const queries = [
    { name: 'works', q: 'type:work AND key:*W' },
    { name: 'orphans', q: 'type:work AND key:*M' },
    { name: 'authors', q: 'type:author' },
    { name: 'subjects', q: 'type:subject' },
    { name: 'editions', q: 'type:edition' },
    { name: 'total', q: '*:*' },
];

async function get_solr_count(solr: string, query: string) {
    const work_count = await fetch(`http://${solr}/solr/openlibrary/select?` + new URLSearchParams({
        q: query,
        rows: '0',
        wt: 'json',
    }).toString()).then(res => res.json());
    return work_count.response.numFound;
}

for (const solr of solrs) {
    for (const query of queries) {
        console.log([
            solr.name,
            query.name,
            query.q,
            await get_solr_count(solr.host, query.q)
        ].join('\t'));
    }
}
```

**Comment by cdrini** [comment]
Connecting testing now...

**Comment by cdrini** [comment]
Seems like it's doing fine on testing; added some perf logging to get a better idea of error rate and duration. Will connect prod on Monday to test its perf!

**Comment by cdrini** [comment]
Connected to ol-web1 now and monitoring

**Comment by cdrini** [comment]
Looking good so far! Not because we're currently attached to two solrs, there will be slight discrepancies in results when search pages are refreshed.

Will leave like this for ~30min to make sure the cache gets nice and warm on ol-solr1, then switch the webhead as well to see how it handles full traffic.

**Comment by cdrini** [comment]
Ok, perf looked good throughout the day! Taking offline for now since ol-solr1 doesn't have an auto-restarter enabled like ol-solr0 does. Next up: Some fixes, then test the the UI/API methods!

**Comment by cdrini** [comment]
Status update: The first stab at the UI/API code is ready for testing next week 😊 #6476 (last commit). Blocked until some prep refactors go through.

**Comment by cdrini** [comment]
Ok, all the changes requiring a full solr reindex should now be complete. Taking off testing.openlibrary.org and kicking off a full reindex to run over the weekend.

**Comment by cdrini** [comment]
Ah, I forgot I need a fresh data dump ; let me kick that off and then start he solr full reindex on Monday

**Comment by cdrini** [comment]
Ok next full reindex completed earlier today. Let's get some stats and see how it looks.

But first: Let's prepare the solr container on our staging solr server:

```sh
cd /opt/openlibrary/openlibrary/scripts/solr_builder

# Stop what we don't need to give solr more resources
docker-compose stop db adminer
docker stop jenkins

# Restart solr/solr haproxy with the config in the docker-compose.yml
docker-compose up -d --no-deps solr solr_haproxy
```

Note the changes to the docker-compose.yml:

```diff
diff --git a/scripts/solr_builder/docker-compose.yml b/scripts/solr_builder/docker-compose.yml
index fb6a61ed7..fff495d79 100644
--- a/scripts/solr_builder/docker-compose.yml
+++ b/scripts/solr_builder/docker-compose.yml
@@ -24,21 +24,37 @@ services:

   solr:
     image: solr:8.10.1
-    restart: on-failure
+    restart: unless-stopped
     environment:
       # This is optimized for bulk loading, but should be shortened for production
       # and we should set autoSoftCommit to a value that makes sense for our query usage (5-15 sec?)
-      - SOLR_OPTS=-Dsolr.autoCommit.maxTime=3600000
-      - SOLR_JAVA_MEM=-Xms3g -Xmx3g
-    ports:
-      - 8983:8983
+      #- SOLR_OPTS=-Dsolr.autoCommit.maxTime=3600000
+      #- SOLR_JAVA_MEM=-Xms3g -Xmx3g
+      - SOLR_JAVA_MEM=-Xms10g -Xmx10g
+    expose:
+      - 8983
     volumes:
       - solr-data:/var/solr/data
-      - ../../conf/solr:/opt/solr/server/solr/configsets/olconfig:ro
+        #- ../../conf/solr:/opt/solr/server/solr/configsets/olconfig:ro
     networks:
       - solr-access
     command: solr-precreate openlibrary /opt/solr/server/solr/configsets/olconfig

+  solr_haproxy:
+    image: haproxy:2.3.5
+    restart: unless-stopped
+    networks:
+      - solr-access
+    volumes:
+      - ../../conf/solr/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
+    ports:
+            - 8984:8984
+    logging:
+      options:
+        max-size: "512m"
+        max-file: "4"
+
+
   # We need ability to use openlibrary code
```


Then we can connect to it (eg `ssh -L 18984:ol-solr1:8984 ...`) Then run the deno stuff above.

And the stats

<html><body>
<google-sheets-html-origin><style type="text/css"></style>

Class | Query | solr-next | solr-prod
-- | -- | -- | --
authors | type:author | 9,601,928 | 9,260,997
editions | type:edition | 35,110,753 | 0
orphans | type:work AND key:*M | 2,226,646 | 2,245,082
subjects | type:subject | 3,073,534 | 3,026,213
total | *:* | 75,263,206 | 38,723,760
works | type:work AND key:*W | 25,250,340 | 24,191,464


</body>
</html>

**Comment by cdrini** [comment]
Updates to get solr-next running:

```sh
docker build -t olbase:solr-next-updater - <<'EOF'
    FROM 'openlibrary/olbase:latest'

    # Fix git being broken for some reason -_- + Fetch master
    RUN git remote rm origin && \
        git remote add origin "https://github.com/internetarchive/openlibrary" && \
        git fetch origin master && \
        git reset --hard origin/master

    # 'Add' let's us break the cache only if the diff has changed! How cool?
    ADD "https://github.com/internetarchive/openlibrary/pull/6119.diff" 6119.diff
    RUN curl -L 'https://github.com/internetarchive/openlibrary/pull/6119.diff' | git apply

    # Confirm the right stuff has indeed changed
    RUN git diff --compact-summary master
EOF
```

# Set solr state file date
docker-compose run --rm solr-next-updater bash -c "
    echo '2022-06-06:0' > /solr-updater-data/solr-next-update.offset
"
docker-compose run --rm solr-next-updater bash -c 'head /solr-updater-data/* && echo'

# Start it up!
OLIMAGE='olbase:solr-next-updater' docker-compose up -d solr-next-updater

# Check logs
docker-compose logs --tail=100 -f solr-next-updater

# Check how caught up we are
curl "ol-home:7000/openlibrary.org/log/$(docker exec openlibrary_solr-next-updater_1 cat /solr-updater-data/solr-next-update.offset)?limit=1"

**Comment by cdrini** [comment]
This has been on production over the weekend! Things look good! A few issues found/added
Scripts testing

```sh
# Add the code
docker exec -it openlibrary_web_1 bash -c '
    curl 'https://patch-diff.githubusercontent.com/raw/internetarchive/openlibrary/pull/6476.diff' | git apply
    pip install -r requirements.txt
'
docker restart openlibrary_web_1

# Open a tunnel to confirm web1 working
ssh -L 18080:ol-web1:8080 -qAy PATH_TO_SERVER

# Remove the code
docker rm openlibrary_web_1
ssh -A ol-home0 '/opt/openlibrary/scripts/deployment/restart_servers.sh ol-web1'
```


Monitoring:
- ol-solr0 utilage: https://wwwb-grafana0.us.archive.org/d/000000174/ol-solr0?orgId=1&refresh=1m&var-fqhostname=ol-solr0_us_archive_org&var-resolution=30m&from=now-6h&to=now
- ol-web1 utilage: https://wwwb-grafana0.us.archive.org/d/000000174/ol-solr0?orgId=1&refresh=1m&var-fqhostname=ol-web1_us_archive_org&var-resolution=30m&from=now-6h&to=now
- Sentry: https://sentry.archive.org/organizations/ia-ux/issues/?project=7
- Haproxy: https://openlibrary.org/admin?stats

**Comment by cdrini** [comment]
It is a little slower, but not a ton slower. I think it might be good enough for merging though and we can make perf improvements to the facet system :+1: 

![image](https://user-images.githubusercontent.com/6251786/191088223-89dadab5-fab6-4b12-96c1-6b57ccd40e80.png)

**Comment by mekarpeles** [comment]
Are there any sub-issues from #2728 which may be useful to update given the work we've done in this thread?

(that issue is from 2019 so it themed like we may want to just cherry-pick relevant pieces and pull them here or into a new issue)
