### ISSUE TITLE
Add Google Analytics Tracking to Main Site Nav Bar Items

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6492]
Add google analytics tracking to the components in the top menu bar
- [ ] `Browse` button `<summary>` tag, e.g. `TopMenu|Browse`
- [ ] `More` button `<summary>` tag, e.g. `TopMenu|More`
- [ ]  The avatar image `<summary>` tag within the `account-component`, e.g. `TopMenu|Account`

![openlibrary org_account_loans](https://user-images.githubusercontent.com/978325/165361489-87e6b7f5-0a8f-4f3a-ab71-9b7557cfab63.png)

### Stakeholders

@cdrini
