### ISSUE TITLE
Usability Improvements to Work Merge Interface

### ISSUE THREAD

**Issue by mheiman** [internetarchive/openlibrary#6556]
Now that work merging is available on production (yay!) I'm working on some tweaks to improve the lives of those of us who use it a lot.

This is my initial list, but I'd welcome any additions or refinements.

### Work Selection

[ FIXED - PENDING DEPLOY] When selecting works from a list, if you deselect a work the Merge button always deactivates, even if other works are still selected. The Javascript needs to be corrected to only deactivate the Merge button when fewer than two works are selected.

### Merge Interface

1. [x] The diff display for titles and other textfields (the strikethrough/color-coding effect) makes it difficult to easily scan titles and spot errors. The preview of the final work values at the end of the list is enough to work from, particularly if we make that a little more visually prominent. (Discussed in community meeting; toggle for diff display added)
2. [x] Some columns allow long, unbroken strings to explode the table, pushing important data off-screen. All table cells need appropriate overflow handing.
3. [x] The column order isn't optimal for librarian use. I'm open to suggestions, but my starting lineup would be something like: covers, key..., created..., first_publish_date, editions, other identifiers, and then the rest. 
4. [x] Sometimes "author_role" shows up instead of the author ID for a work
5. [x] The logic for sorting works (and choosing the work that supplies default values) is simplistically reliant on the record creation date. It often chooses a work with one edition when the next one on the list, with the same creation date, has multiple editions and should really be the primary record. I'd like to update that sorting logic to prioritize the earliest record that also has the most editions/edits. (Discussed in community meeting; conclusion: Retain the ordering by date.)
6. [x] #6558

### Other Enhancements

1. [x] This is a bigger task, but making the merge interface smart enough to handle orphaned editions would be huge — orphans are currently a big time sink. Technically, it's not that complicated — if the work selection interface allowed them to be selected, they could be added to the merge interface (with no option to make them the primary record), and the merging routine could assign them to the new merged work after the merge is done. It's just a deeper reworking than the interface tweaks above.

### Stakeholders
@mheiman @seabelis @cdrini @mekarpeles

**Comment by seabelis** [comment]
Agree to all except 4. Would prefer to keep the oldest record, lowest ID.

**Comment by mheiman** [comment]
Thanks! What's your thinking around that? I've been told that the point of choosing the oldest record was to try to keep the edit history as clean as possible, so it seems odd to pick a record with no edits as the primary, and merge into it a record created the same date that has a lengthy edit history.

**Comment by dcapillae** [comment]
Merging works does not work correctly when any of the works to be merged has more than 50 editions and is not the main record. I don't know if it is related to the interface in this case, but I think it would be convenient to correct this malfunction.

About keeping the oldest record, that has been the rule so far. It makes sense, although it also makes sense to use the record that has more edits and larger history, since it is probably the one that more people have used and contains better information about the work. If it were possible to choose the most complete record while retaining the oldest id and its creation date it might be a compromise solution.

**Comment by cdrini** [comment]
^ I created an issue for the 50 editions problem and added it to the list!

**Comment by mheiman** [comment]
There's now an update to the Merge UI available on testing.openlibrary.org that addresses most of these issues -- I think everything but the default sort order and the 50 editions problem.

Please give it a try and leave any comments or suggestions here. I'm sure there are still some things that need tweaking.

The updated UI _will_ merge orphaned editions along with works, but the blue bar selection tool doesn't currently let you add them to a merge -- that's a more complicated problem. But you can add edition ids to the URL query string and see how that works.

**Comment by mheiman** [comment]
All of the associated tasks are complete, so I'm going to close this issue. Further enhancements can be requested in new issues.
