### ISSUE TITLE
Book Sponsorship Program: Empower OpenLibrary patrons to fund missing books

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#659]
It would be amazing if Open Library could become the World's library, in the sense that readers had the power to fund digitization of the books they wished were available. Therefore Let’s add a “Sponsor this Book” button to OpenLibrary.org and enable our international audience to contribute towards building a true Open Library.

## Fundraising
Prior to formalizing a Book Sponsorship Program feature, we tried to crowd-source funding for a pallet of books: http://blog.openlibrary.org/2018/10/27/raising-crypto-for-the-greater-good/

## Subtasks
This Epic task will be considered done when the following sub-tasks are completed and/or merged into the `master-sponsorship` branch:
- [x] Add **Sponsor this eBook** button (when no ebook available) to `Books Page`,  `Search Results Page`, `Works Editions table` [#2162](https://github.com/internetarchive/openlibrary/issues/2162)
- [x] Designing and implementing of **Modal** (which pops up when the user clicks the **Sponsor this Book** button) [#2164](https://github.com/internetarchive/openlibrary/issues/2164)
- [x] Redirecting the user to archive.org for payment (after checking out the details(like cost breakdown ...) on Modal and then clicking `Proceed`) [#2166](https://github.com/internetarchive/openlibrary/issues/2166)
- [x] Thank you page + email receipt  [#2167](https://github.com/internetarchive/openlibrary/issues/2167)
- [x] Create Database of Book Sponsorships on Open Library (Which @user has donated which books?) 
[#2163](https://github.com/internetarchive/openlibrary/issues/2163)
- [x] Instrument basic analytics tracking [#2165](https://github.com/internetarchive/openlibrary/issues/2165)
- [x] Making changes in Open Library account page (list what books you’ve sponsored) [#2168](https://github.com/internetarchive/openlibrary/issues/2168)
- [x] View My Sponsored Books page [#2178](https://github.com/internetarchive/openlibrary/issues/2178)
- [x] Leaderboard of book sponsorships (/sponsors) [#2169](https://github.com/internetarchive/openlibrary/issues/2169)
- [x] Adding a `Sponsor Me` carousel on the Homepage. [#2170](https://github.com/internetarchive/openlibrary/issues/2170)

**Comment by LeadSongDog** [comment]
The whole IA Bookdrive process has always been rather strangely underpowered. Most of the world cannot readily take physical volumes to San Francisco, so there's a substantial shipping cost barrier to donation. I'd happily take many volumes from my personal collection to another city (when I'm going there) if I knew they'd be scanned and put online. But putting up a stack of shipping money, along with the stack of volumes, without any assurance that they'll be put online is a huge deterrent to action. More distributed collection points would reduce that. We could aim to have one drop box in every city over 1 million people. A "yes, we'll scan it" confirmation in advance of donation would also give donors more confidence their donation will be valued. This could have the ancillary benefit of getting prospective donors to engage as OL editors: to confirm their particular edition is needed for scanning they would first be looking it up.
 
For volumes already online, but with a long loan wait list, would it be sufficient to donate just the covers and titlepages then discard the text block? That would, I suspect, shrink costs and storage space while sufficiently supporting purchase provenance for allowing multiple simultaneous e-loans.

**Comment by mekarpeles** [comment]
@LeadSongDog there are a lot of policy considerations that go into play when deciding which books are eligible for the lending program. I think what makes most sense if for IA to provide a list of whitelisted options of books and then to allow the world to donate funds (not books) towards the acquisition and digitization of these items.

Yes, there are many books which readers have, and services like bookmooch which are great and handling repurposing of people's used books. But in general, it's more cost effective to raise funds for 1000 books at a time and to purchase them (used or new) from a distributor which can reduce shipping costs via economy of scale.

I know many people would like to donate their physical books. The question is, what mechanisms has the easiest logistics at scale. Fundraising results in a centralized scenario with economies of scale whereas there's a lot of logistic overhead of a physical bookdrive where shipping has to be coordinated from n-users.

With respect to "verifying" and "destroying" your book -- it's not about what I or we view as acceptable, so much as what other players in the space feel. In many respects, we do our best to adhere to standard practices of how libraries operate. It's a very interesting idea :)

**Comment by mekarpeles** [comment]
Another option is, once a quarter we can aggregate the top ~100 - 250 books from https://openlibrary.org/stats/readinglog "Want to Read" and do a donation campaign for funds.

**Comment by LeadSongDog** [comment]
Is there a public cost model for the ship/catalog/scan/ocr/store actions? From the outside, it's not obvious how much a scan costs vice the print book to be scanned. It might better inform these discussions.  We should be deeply unhappy with an acquisition model that has an intrinsic geographic bias to one location. It is, at minimum, disrespectful to the participants at other scanning centers. It also introduces huge cultural biases.

**Comment by mekarpeles** [comment]
re: scanning centers, we're no where near this this stage in the process and I'm not in charge of any scanning centers. If/when we get to this stage, I'll make sure these opinions are received.

I think as of 2017 a $10 book with ~300 pages costs ~$75 to store forever (buy/ship/catalog/scan/ocr/storage etc) but someone else other than I should comment.

**Comment by LeadSongDog** [comment]
The Book Drive page at IA still shows $0.10 per page for scanning. 

A forty-foot ISO container will move thirty tonnes in 67 cubic metres by sea between pretty well any two modern seaports in the world for under $3000 on a slow schedule, perhaps a few hundred more from nearby inland locations to the port, so freight for the whole book will cost less than scanning one page. (https://www.movehub.com/advice/international-container-shipping-costs) Ignore that cost. 

Acquiring the container to use for incremental permanent storage space, near end-of-life, is a similar cost.  Ignore that too. Every week there are small bookstores that close somewhere. Sad, but we could help make that less sad.  For many, the inventory is available nearly free. (examples this week: http://nbc4i.com/2018/02/02/acorn-bookshop-in-grandview-going-out-of-business/ http://www.cbc.ca/news/canada/ottawa/carleton-place-book-gallery-closing-1.4526019 http://jewishnews.timesofisrael.com/josephs-bookstore-to-close-after-25-busy-and-fruitful-years/ ) 

There really should be a prepared answer of "Yes, please, and here's how...!" ready when these opportunities come up.

**Comment by mekarpeles** [comment]
Scott B. writes us with the idea:
> Everywhere there is a waiting list on the site, solicit donations to acquire more copies of that book, and then use those donations to buy used copies.

**Comment by tabshaikh** [comment]
Hi all, I have created a rough draft for Book drive initiative, a lot of points needs to be discussed so I would like all the members to give their feedback on it. @mekarpeles @hornc @jdlrobson @tfmorris @cdrini @LeadSongDog.  https://docs.google.com/document/d/1Ym9RRNB5_k7I7z6ZehKKn0TISYgF1yofE-rtw6NtMWM/edit?usp=sharing (Please send me the permission request and i would be happy to accept it:)

**Comment by tabshaikh** [comment]
wiki link of the book drive initiative https://github.com/internetarchive/openlibrary/wiki/Book-Drive

**Comment by tabshaikh** [comment]
Hi, @LeadSongDog @mekarpeles @jdlrobson @hornc I am trying to make a timeline for books sponsorship program which includes the components and approx. the time it would take to implement them, would love your feedback on this if any of this would take more time.

1. Roles & Permissions for “Book Sponsor” - Done 
2. Database of Book Sponsorships on Open Library (Which user has donated which books?)
Design database schema sql
Write models (see: Reading Log & User Follows examples) - 4 Days
3. Implement Analytics (for A/B testing) - Would like some suggestions of the community on this? 
4. Design “Sponsor this Book” button
Open Library Search results Page
Open Library Works’ Editions table
Open Library Editions (books) Page  - 2 days 
5. Modal - Researching about modal design and implementing - 1 day 
6. Archive.org Book Donation Page
7. Book lookup
Implement Parser for input (determine if isbn, amazon url, etc)
Policy Check (??) + check Sponsors list
8. Payment Processing - Time to implement payment processing 1 week using stripe as on archive’s donation page
9. Thank you  page Email Receipt  For both 2 days
10. Open Library account page (list what books you’ve sponsored) - 2 days
11. Leader-board or book sponsorships (/sponsors)? - 4 days for basic 
12. Homepage “Sponsor Me” carousel - 2 days 
13. Simple A/B testing campaign - Time taken for this to be decided.

**Comment by mekarpeles** [comment]
I notice `Archive.org Book Donation Page` doesn't have a time associated with it. Maybe @bfalling @pezvi @iisa can offer an estimate based on the https://archive.org/~mek/donate/sponsor-a-book/index.php concept

**Comment by LeadSongDog** [comment]
@tabshaikh 
On the fundraising side, I see three ways users will want to participate: "I want to read this"; "I loved this and want others to read it"; or "I just want to help expand the library". The above components seem mostly fitted to the first of these three. If the fund-select-acquire-scan-mount pipeline takes too long then the waiting sponsor, thinking like a buyer, may become unhappy with any amount of delay in a world of overnight free deliveries.  The second and third, in contrast, fit better to a truly selfless donation, have no implicit delivery schedule, and might legitimately qualify as charitable. I think that is a better place to focus effort initially. The second fits nicely into a book review interaction. The second and third both fit in a general fundraiser interaction. The first would naturally fit where a user's attempt to borrow has been frustrated by nonavailability of (or long wait for) an electronic format in the library. 
Of course, none of this is really about a book drive, it's about a book funding drive. If that's the true intent, the naming should be amended to keep things honest. 

My earlier comments were directed towards a more traditional concept of a book drive, where physical books are donated, in this case for scanning.

**Comment by LeadSongDog** [comment]
Looking at the IA site for info on the scanning centers/centres, I'm left with the impression that they don't really want people to know much about it. Most of the information is years old. They're proud of the Scribe systems, but to get the details on where the scanning centres are, or how to get involved, one is expected to cold email one of eight (hopefully still-involved) people. There`s nothing about how to establish a new location. My city is currently planning a new central library and archive, that logically would be a great place to site a scanning centre. There should be a clean briefing package that shows why they should include it, what it takes to do so, the costs and benefits. Something that architects and politicians can understand.

**Comment by mekarpeles** [comment]
@tabshaikh let's create a branch called `master-sposorship` and we can incrementally merge our changes into this branch (while in development)

**Comment by mekarpeles** [comment]
Considering this Epic closed. Opening a followup issue which details remaining steps
