### ISSUE TITLE
Improve Main Site Navigation

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6681]
The hypothesis is that the Main Site Navigation is not serving our patrons as well as we'd like it to. Google analytics shows us that many patrons who use the website want to check their books page (loans, holds, reading log, etc).

Currently, on both desktop and mobile we offer the options `Browse`, `More`, and an account menu / hamburger menu.

**Desktop**
![openlibrary org_](https://user-images.githubusercontent.com/978325/175342045-717204a1-239c-4cca-b61f-ed94f32f6058.png)

**Mobile**
![openlibrary org_ (1)](https://user-images.githubusercontent.com/978325/175342157-002b4816-e117-4995-8aa8-291aebaf6614.png)

## Problem(s)

1. On desktop and mobile, the account/hamburger menu options are different. We'd like the desktop version to be consistent by using the mobile version.
2. The `More` button is not descriptive and doesn't directly solve a patron's problems. Its options are already included in the hamburger / account menu and so the proposal is to remove this option.
3. The action we believe (both based on analytics and based on decisions by goodreads and overdrive) that patrons are looking for is a link to their books / library, e.g. `My Books` or `My Library`. This should be the most prominent option on the main site nav menu, even before browse.

![www goodreads com_ (5)](https://user-images.githubusercontent.com/978325/175344647-3cfbaeea-f55d-4be0-b7d7-c6b7d9033d0e.png)

e.g.
![openlibrary org_ (2)](https://user-images.githubusercontent.com/978325/175343849-5a2192a4-dc02-43f6-a034-1e320ac3c7e2.png)

## TODOs 

- [x] To be sure these are the changes we want to make, we need to first wire up our navigation with analytics -- to the options in the header menu and the hamburger menus
- [x] Options from `More` which are missing from the hamburger should be moved to the hamburger so `More` may be removed
- [x] Add hamburger menu when logged out (desktop / mobile), the same as when you’re logged in w/o logged in options

**Comment by mekarpeles** [comment]
* Discussion around Sign-up an Sign-in options on mobile

**Comment by mekarpeles** [comment]
Effort to be continued by Dana F, this preparatory issue has served its goal and the first steps are on production
