### ISSUE TITLE
Librarian Merge Queue Redesign

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6816]
### Describe the problem that you'd like solved

EDIT: The designs have changed slightly, see figma.

We'd think we'd like to head in the direction of a Merge Queue Dashboard which looks like this:
https://www.figma.com/file/kOQdKg11suMVZrDSAXTYLc/Merge-Queue?node-id=0%3A1

![www figma com_file_kOQdKg11suMVZrDSAXTYLc_Merge-Queue_node-id=0%3A1](https://user-images.githubusercontent.com/978325/191992020-e77c5c68-5846-4306-996a-9e9d9beb138b.png)

Some of this redesign work has already been implemented in this draft: https://github.com/internetarchive/openlibrary/pull/6736

Creating a project board (?) for Librarian Merge Queue and creating issues for the following

## Remaining

1. [ ] Adding `sort` label / link which swaps the sort order from `desc` to `asc`
    * remember sort across requests / pages
    * defaults to `desc` 
2. [ ] Merge Queue: Add UI dropdown to filter by `submitter`
     * remembers submitter across requests / pages
3. [ ] Merge Queue: Add UI dropdown to filter by `reviewer`
    * remembers reviewer across requests / pages
4. [ ] Hide Librarian Merge Queue comments by default in MR cards
    * Have a button which shows # of comments
    * clicking btn hides/shows div
    * Show the _latest_ comment below the title in the MR card (as is pictured in mock up)
5. [ ] Update UI to look more like the above picture

## Completed

- [x] #6556 
- [x] #6927
- [x] Add `mrid` visibly to rows (somewhere) **P2**
- [x] #6812
- [x] #6811 
- [x] #6833
- [x] #6883
- [x] #6915

**Punted**
- [ ] #6996 
- [ ] #6882 - seems too challenging to get ID from infobase internals

### Stakeholders

@seabelis @dcapillae

**Comment by Eds-Dbug** [comment]
Hey I want to work on the UI for this!

**Comment by Eds-Dbug** [comment]
Main page template done!

**Comment by jimchamp** [comment]
This was inadvertently closed due to a `Closes` statement in one of the linked PRs.  Reopening and assigning myself to integrate the existing code into `master`.
