### ISSUE TITLE
October Logistics Checklist

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6823]
### Describe the problem that you'd like solved

- [x] Flights/transit + lodging for staff (October)
- [x] Prepare [Community 2023 Planning](https://docs.google.com/document/d/1-N_Tyqa7Uex24lxDwO-PiQs1y3pjYAXSpYtwzAi2OH0/edit#) doc
- [x] Creating our [Slides](https://docs.google.com/presentation/d/1qsmRa8ZvMDApL55ryxkz-75M6LXSFJ-sq7uE2FcZqV4/edit#slide=id.p) for community presentation
- [x] Board Meeting slides + Board Report (move to Nov?)

**Comment by mekarpeles** [comment]
new issue required for Nov 28 board report + slides
