### ISSUE TITLE
Fill milestone for 2022-12 (and 11)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7051]
### Describe the problem that you'd like solved

- [x] Search box camera icon → returnTo single scan
- [x] BookServer – Testing.openlibrary.org
- [x] Add sentry + slack monitoring @cclauss 
- [x] October Community Celebration #6823 
- [x] Reading Log Search
  - Issue: #5080
  - PR: #7052
- [x] Promise Item survey - https://github.com/scottbarnes/promise-items/issues/1
- [x] Fix affiliate service (amz imports, add sentry) @cclauss 
- [x] My Books Landing + Main Site Nav 
  - #6857 
  - #7021
- [x] Yearly Reading Goals (needs team design session)
  -  see #6662
- [x] Solr stuff (completely landed) 
  - #7017
  - #6895 
  - #6377 

## Punting for 2023

- [ ] Bulk Availability API (token/scope)
  - https://git.archive.org/ia/petabox/-/merge_requests/3302
- [ ] Barcode scanner + mini blog post (ask comms)
