### ISSUE TITLE
Update List APIs

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7530]
### Describe the problem that you'd like solved

* [x] Our current documentation is likely out of date for Lists: https://openlibrary.org/dev/docs/api/lists. We should make sure the data + recipes are correct
* [x]  The List API should include a mechanism for deleting a list (or at minimum emptying/"archiving" -- which would mean just having a json filed called "archived": true that gets hidden by the UI.
    * POST https://openlibrary.org/people/{account}/lists/OL{id}L/delete.json
* [x] The List API should have a "create" function which accepts but does **not require** a seed (i.e. initial book)
* [ ] The https://github.com/internetarchive/openlibrary-client should be extended to manage Lists (e.g. add to list)
* [x] #7589

**Comment by JaydenTeoh** [comment]
@mekarpeles I would love to help

**Comment by JaydenTeoh** [comment]
@mekarpeles There is already a "Delete this list" button implemented under the list page. As for the create list function, I tested sending an API request with no seed and it worked, I will proceed to implement a button under the list tab to allow readers to make the same request and create a list without needing a seed
