### ISSUE TITLE
Confirm new ol-www0 IP anonymization working + getting forwarded to `client_id`

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7566]
Subtask of #6000

Connect to the new ol-www0 by:

1. Find that server's ip (Run `ping ol-www0` inside the prod cluster)
2. Update your local machine's etc/hosts file with `THE_IP x-openlibrary.org`
3. Update the nginx conf on ol-www0 (`docker/web_nginx.conf`) to have `server_name x-openlibrary.org`
4. Restart nginx on ol-www0 `docker restart openlibrary_web_nginx_1`
5. Confirm alive and well `docker logs --tail=10 -f openlibrary_web_nginx_1`
6. Confirm logs being recorded `tail -f /1/var/log/nginx/access.log`
7. Go to x-openlibrary.org in your browser
8. [x] Confirm the IP in the logs is not the same as your own.
9. Enable a VPN and try visiting x-openlibrary.org
10. [x] Confirm the IP has changed, but is still not the same as the actual IP

- [x] Confirm with @traceypooh that the seed used for the IP anonymization on ol-www0 is correct.

**Comment by cdrini** [comment]
Could use the debug page which displays http headers https://openlibrary.org/search?mode=everything&q=Rowan%20Williams%2C%20Looking%20East%20in%20Winter%2C%20chapter%201%3A%20%27Theologizing%20the%20Life%20of%20the%20Spirit%3A%20The%20Word%20of%20the%20Philokalia%27.&debug=true . But change it to x-openlibrary.org to get there via www0 (assuming above etc/hosts changes).
