### ISSUE TITLE
Confirm ipstats are being processed from new www

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7602]
Subtask of #6000

ipstats is run from cron on ol-www1 (the old ol-www):

```
0 * * * * [...] $SCRIPTS/ipstats.py  /olsystem/etc/openlibrary.yml
59 23 * * * [...] $SCRIPTS/ipstats.py  /olsystem/etc/openlibrary.yml
```

https://github.com/internetarchive/olsystem/blob/35dab0b979fd574d6304a0c40451044b9988c76e/etc/cron.d/openlibrary.allnodes#L27-L29

This script reads from `/var/log/nginx/`, counts the number of unique IPs, and then saves that number to infogami/database using `web.ctx.site.store` under the key `counts-%Y-%m-%d` with `type: admin-stats`. Note the object is pre-existing, this just add the `visitors` field.

https://github.com/internetarchive/openlibrary/blob/8aa71c7c545fa082560bfba7b31cc84319650730/scripts/ipstats.py#L89

But where is this read?

This is read by the https://openlibrary.org/stats, but never used! This is only ready by the visitors graph on the home page... https://github.com/internetarchive/openlibrary/blob/da2069e16ee75e6c8950f801f5656edf389b6bde/openlibrary/templates/home/stats.html#L46

### Steps
- [ ] Add the above cron steps to the `www_nginx` crontab environment param
- [ ] Run the command manually from the new www `web_nginx` container. Do a `web.ctx.store.site.get('counts-2023-03-XX')` and confirm the numbers are very small (compare against the previous day). Note this _will_override production data, but we can just run it from the old www to replace with the correct counts.
- [ ] Visit the new site using etc/hosts override. Update `ipstats.py` line 68 to check for `x-openlibrary.org`. Visit the site.
- [ ] Configure the cron to run soon. Confirm it ran, and that the counts were updated.
- The counts will be auto-updated by the _real_ cron, so no need to fix it.
- [ ] Remove the cron file from the new www server so it isn't constantly clashing with the actual www ipstats cron.

**Comment by cdrini** [comment]
Closed in favour of #7622
