### ISSUE TITLE
Bulk Search & List Creator

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7653]
This issue calls for a new feature called the **Bulk Search** that lets a patron submit blocks of plaintext to see if books can be found inside. For instance:

1. Patrick Collison has a website https://patrickcollison.com/bookshelf which references books:

```
[How Judges Think](http://amazon.com/dp/0674028201)
[Aftermath](http://amazon.com/dp/0830642838)
[The Outbreak of the Peloponnesian War](http://amazon.com/dp/0801405017)
[The Rise and Fall of American Growth](http://amazon.com/dp/0691147728): The U.S. Standard of Living since the Civil War (The Princeton Economic History of the Western World)
```   

2. The **Book Extractor** will parse the text and see if it can identify book titles, isbns, urls, author names, or other useful book information.
3. The tool then performs a search on Open Library using this data to find matching books. 
4. The patron then selects one or more matching Open Library books (choosing a desired edition, if relevant) and adds these books to one of their Open Library lists or reading log (e.g. Want to Read).    

Related to list improvements #7390 and twitter borrowbot #3255

Demo by @cdrini:
https://codepen.io/cdrini/full/WNbjqRY

## Tasks

* [ ] Move demo into a page on Open Library, e.g. https://openlibrary.org/search/bulk
* [ ] Formalize code using e.g. vue3
* [ ] Add ability to pull text / find matches directly from url
* [ ] Prototype a widget or chrome extension which lets a patron check for books on any webpage they're on

**Comment by mekarpeles** [comment]
@DebbieSan @cdrini  :)

**Comment by tfmorris** [comment]
The technical terms for this (so people can find this issue) are Named Entity Recognition (for candidate identification) and Named Entity Linking (for resolving to specific OL item).

Presumably this will only be done for a small set of languages to start with. How do users lobby for their favorite language(s) to be included in that set?

**Comment by JaydenTeoh** [comment]
I am working on implementing NER for full text search in my gsoc proposal as well, perhaps we could collaborate on this issue! @cdrini @DebbieSan

**Comment by DebbieSan** [comment]
@tfmorris thank you for this. I'm not sure how implementation would go but I was thinking of starting with the 10 languages currently available in Open Library. However,I'm not sure how doable that is. It is definitely something essential to think about and find a solution.

**Comment by lakshya-dhariwal** [comment]
How about a bookmarklet or a iframe for the POC of "check for books on any webpage"

**Comment by Achorn** [comment]
comment for assignee

**Comment by benbdeitch** [comment]
This seems like a slightly daunting task, but I'd be thrilled to take it on! Could you assign it to me?

**Comment by benbdeitch** [comment]
This seems like a somewhat daunting set of tasks, but I'd be thrilled to take it on. Couldyou assign me to it?

**Comment by benbdeitch** [comment]
Hello! Could you assign me to this project, for my fellowship? I'd love to get this up and rolling.
