### ISSUE TITLE
Persona Research: Understanding Learners & Educators on Open Library

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7833]
See: https://docs.google.com/document/d/1Te8RdQ7SmQXjB-X41r5wrfZ3dk2MWVWBNf3rlh419BA/edit?pli=1#heading=h.7nyjj1a4x28e

* [x] 1. Outline the **process** & compose research goals / questions
* [x] 2. Develop a **screener**  
* [x] 3. Conduct **interviews** and debrief documents
* [x] 4. Perform a **synthesis** of/across results (analysis, internal report)
* [x] 5. Design **persona** artifacts + blog post (public report)
