### ISSUE TITLE
Canonical Tags: Subjects to become 1st class objects in metamodel

### ISSUE THREAD

**Issue by JaydenTeoh** [internetarchive/openlibrary#7904]
Epic to supplant #2819  w/ actionable subtasks
In 2023 our intention is to start the Canonical Tags project whose project kickoff & proposal is outlined here: https://docs.google.com/document/d/1zrZAXgk2GEZRWb0D8tsrgaPzX4KdXHVt1s6ZQ4wUHLI/edit#

### Roadmap
- [x] Scaffolding Tags <OL...T> Infogami type and get it into production (already started in #7766)
- [x] Enhance a subject page to fetch/use auxiliary Tag data ('Cooking' page)
- [x] #7905 
- [x] #7648
- [ ] #7906 to add to our [schemata](https://github.com/internetarchive/openlibrary-client/tree/master/olclient/schemata)
- [ ] #65 
- [x] #8279
### Stakeholders

@mekarpeles will be the Mentor guiding this Epic project
I will be working on the implementation
