### ISSUE TITLE
2021 Q3/4 Internationalization: Making OpenLibrary Multilingual

### ISSUE THREAD

**Issue by justcomplaining** [internetarchive/openlibrary#791]
From @justcomplaining: It seems like the potential of the project for international users is greatly limited by the missing front end translation. I would gladly volunteer to help with German, if needed.

---

(below this point edited by @mekarpeles)

## Goal

From @brad2014 in #2190:

This is an epic that covers sub-issues related to both
* moving the server onto a translation maintenance pipeline (Weblate? Pootle? Zanata?)
* refactoring the user interface so that foreign language users see the UI in their language
* creating and maintaining UI translations

The UI will be polylingual, presenting label elements in the user language and content elements in the content language. (With exceptions: e.g. if a data field of a work is its ISO-639 language, that datum would be presented in the user's language. FR would be presented as French or Français or Französich, etc).

## How to Contribute

Adding a new language: https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n#adding-a-new-language

## Language coverage:
- [x] #1855 + #2997 adds & updates Spanish
- [x] #3033 Polish translations
- [x] #2818 + #3711 German translations
- [x] #874 French translations
- [x] #887 Telugu translations (partial)
- [ ] #1040 Nepali translations (help wanted)
- [ ] #3729 German translation updates (review needed)

## Open Issues
- [ ] #2607
- [x] #865
- [ ] #872
- [ ] #151 is tangentially related

## Related issues:
- [x] #2190 (closed as duplicate: Internationalizing the openlibrary UI) 
- [x] #871 deprecate old functions
- [x] #973 audit of missing i18n pages
- [x] #988 add i18n to /stats/readinglog page
- [x] #2353 improving i18n front-end guide

And #2417, #1146, #4042, #3907, #3834, #3834, #3811, #3725, #3723, #3557, #3511, #3354, #3351, #3034, #3173, #3171, #3169, #3067

**Comment by mekarpeles** [comment]
Please! We'd love the help. We do have have i18n internationaliztion / localization files in place but I'm not sure if they are correctly being used.

See: https://openlibrary.org/i18n and https://github.com/internetarchive/openlibrary/tree/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/plugins/openlibrary/i18n

**Comment by LeadSongDog** [comment]
They definitely are not. There's no place to for the user to make a language choice ever since the login moved from OL to IA.

**Comment by justcomplaining** [comment]
Since the last commit to that part of the repo was 2009 I guess it doesn't make much sense to try to work with these files, right? I'll just wait until multiple languages are supported again and then I am ready to help. :)

**Comment by LeadSongDog** [comment]
@justcomplaining Please don't abandon hope, the login problem is a recent development.  I'm sure it's possible to find a solution.

**Comment by mekarpeles** [comment]
There's a lot of code that was last touched in 2009 -- the project was dormant for several years due to lack of developers.

I fully support @LeadSongDog's comment; our core team is very small and we only have to much time to push important issues forward. Internationalization is an important one, so if you have the bandwidth, I hope you'll give it a shot! We're here to help you.

**Comment by hornc** [comment]
Thanks @LeadSongDog for the link.  WIP PR #801  was prompted by this issue and other recent efforts and questions around i18n.

I'd love to get things in a state where other volunteers can proceed with translations and see them in effect on the site!  I think there might be some initial work required to get the msg strings in good order,  but I have at least updated and fixed a few issues with the python Babel string extraction etc, so at least the process can be run now, and the messages can be updated.

**Comment by tfmorris** [comment]
@justcomplaining Now that @hornc has finished work on #801 and it has been merged, do you have what you need to work on a German translation or do you need more guidance in the form of a README or Wiki page?

**Comment by hornc** [comment]
@LeadSongDog and others, OL currently will honour [browser language settings](https://www.w3.org/International/questions/qa-lang-priorities) to enable i18n, so there _is_ a mechanism for users to choose language (I only discovered this was working recently).

Currently there is a partial Telegu translation live, and once #801 is pushed to production Czech, translated by @Clonewayx (thank you _very_ much for your work which has kick-started this!) will be visible the same way.  Now we need more languages, and reviews to ensure all the important messages are covered by i18n.

There are a small number of translations in other languages here for a minimal set of messages here: https://github.com/internetarchive/openlibrary/tree/master/openlibrary/plugins/openlibrary/i18n
In the deprecated strings. format

es Spanish
hi Hindi
it Italian
kn Kannada
mr Marathi

These need to be checked and moved to the new format (if the messages are still in use) and then removed from the repo, along with the associated code for the deprecated i18n method.

I'll raise an issue for this.

**Comment by salman-bhai** [comment]
I'd like to help in contributing to the Telugu part this weekend!

**Comment by justcomplaining** [comment]
@tfmorris I will take a look sometime soon and get back to you should I have any questions. :)

**Comment by salman-bhai** [comment]
I think we can close this and make #871 as the main Issue as it describes the problem rather perfectly! I propose we change the title of #871 to have it as a base Issue for Internationalization. 
The wiki for internationalization can be found [here](https://github.com/internetarchive/openlibrary/wiki/Contributing-to-Internationalization-(i18n))

**Comment by salman-bhai** [comment]
@mekarpeles @hornc what do you think about making #871 as it is slightly more detailed regarding Internationalization

**Comment by justcomplaining** [comment]
I think there is more to this issue than migrating translation methods, e.g. frontend selection of language.

**Comment by salman-bhai** [comment]
Frontend selection language as in ?

**Comment by LeadSongDog** [comment]
@salman-bhai I think what @justcomplaining is referring to is that there is no longer a way for users to specifiy their language preference. Most other wikis have extensive preference setting options such as https://en.wikipedia.org/wiki/Special:Preferences, but not so https://openlibrary.org/account which has very little. Particularly, it has no language setting. Even worse, some of the preferences are on another site entirely (archive.org).  I'm told that it is possible to change browser settings in such a way that openlibrary will operate in another language, but I've yet to see how. In any case, it should be a one or two click toggle, not an arcane "do this then that then the other thing then log out and reboot while standing on your left heel and reciting the CC-BY-NC-3.0 license backwards from memory" sort of instruction.

**Comment by nemobis** [comment]
Thanks for working on this. It would be great to enlist the help of the translatewiki.net community and software to get more translations (with translation memory and many other features):
https://translatewiki.net/wiki/Translating:New_project

**Comment by hornc** [comment]
Thanks for the link to translatewiki @nemobis , it looks promising and just like the crowd sourced method we have been wanting to implement. I will look into what it will take to add Open Library as a project

**Comment by brad2014** [comment]
I'm consolidating internationalization development under epic #2190.

**Comment by guyjeangilles** [comment]
This is the older issue so I'm making it the canonical i18n issue per [@tfmorris' comment](https://github.com/internetarchive/openlibrary/issues/2190#issuecomment-557952294)

Related: #871 , #1855 , #1040, #865, #872 , #988 , #973 , #2353, #2417, #1146 , #2607 . #151 is tangentially related

**Comment by mekarpeles** [comment]
Related issues:
#2190, #871 , #1855 , #1040, #865, #872 , #988 , #973 , #2353, #2417, #1146 , #2607 . #151 is tangentially related

**Comment by lephemere** [comment]
Regarding internationalization, I quickly went through OL main pages and identified the ones which could greatly improve non-english speaking user experience.

- [Subjects](https://openlibrary.org/subjects) => Editable page. See #4677.
- [Authors](https://openlibrary.org/authors) => Not i18n friendly (templates/authors/index.html).
- [Help](https://openlibrary.org/help) => Editable page.
- [How can we help?](https://openlibrary.org/contact) => Partly i18n friendly (templates/support.html).
- [FAQ](https://openlibrary.org/help/faq) => Editable page.
- [Sponsorship](https://openlibrary.org/sponsorship) => Editable page.
- [Troubleshooting](https://openlibrary.org/help/faq/troubleshooting) => Editable page.

**Comment by contributorpw** [comment]
@lephemere 

* Around the Library (bottom of main content of the start page)
* Footer (it is verbose)

<details>
<summary>Details</summary>

![1614488702614](https://user-images.githubusercontent.com/5027939/109408562-eee7ea00-799b-11eb-8678-e48ceb933a3a.png)

</details>

**Comment by lephemere** [comment]
@contributorpw
I've checked the templates associated to these parts and they are all i18n friendly.
We need to update the i18n message template and translate for each language.

**Comment by lephemere** [comment]
Some thoughts on i18n:
- Could be interesting to have an overview of translation coverage for each available language (translated_msgstr/all_msgstr)
- Do we have some stats on page default display language from OL users web browser?

**Comment by cdrini** [comment]
This overlaps with #5134 😬 Need to untangle at some point.

**Comment by cdrini** [comment]
Closing as the milestone has passed. The sub-tasks are independent enough and can stand on their own.
