### ISSUE TITLE
Record Merging

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#805]
Merging works is complex. Moving editions from one work to another is much easier. For now, perhaps a manual work merging process is sufficient. The following new interface is proposed:

The proposal is adding a new endpoint to works, e.g. https://openlibrary.org/works/OL27448W/The_Lord_of_the_Rings, called `/merge?olids=work_1,work_2,...work_n`. This would make `OL27448W` the `primary` work (to which `secondary` works others will be redirected). An `olid` can be a `work` (in which case it will be merged/redirected) or an `edition` which will get moved from its current work to the `primary`.

i.e. `https://openlibrary.org/works/OL27448W/The_Lord_of_the_Rings/merge?works=work_1,work_2,...work_n`

The resulting UI will be similar to the /edit interface but minimally designed. It will cover the `work` schema outlined in https://github.com/internetarchive/openlibrary-client/blob/master/olclient/schemata/work.schema.json

The UI will show something like (enumerating all fields in the work schema):

*Master Title:* (OL27448W) [ The Lord of the Rings _ ] # Editable Master Title
Work 1 title: Lord of the Rings 
Work 2 title: The Lord of the Rings
...
Work n title: lord of the rings

# Upon Merge Checklist

- [x] Move all editions to the `primary` work
- [x] Redirect all secondary works to `primary`
- [x] Update all `olids` (work, edition) and write-back to archive.org

**Comment by LeadSongDog** [comment]
Also need to merge the work records themselves. They may have different author records listed, subjects, classifications, descriptions, etc. Merged works should at minimum consolidate these, but ideally should facilitate deduplication and selection of best-choices such as first-edition titles.

**Comment by LeadSongDog** [comment]
Non-admins can't create hard redirects. If we create soft redirects such as a work description of:
 See https://openlibrary.org/works/OL27448W/The_Lord_of_the_Rings
an automation-assisted admin could later convert those soft redirects to hard ones.

**Comment by mekarpeles** [comment]
See also related/dupe: #118 #119

**Comment by hornc** [comment]
WIP branch here: https://github.com/internetarchive/openlibrary/tree/805/feature/v1-work-merge-workflow

**Comment by LeadSongDog** [comment]
@cdrini @mekarpeles 
The interim merge workflow has some obscure hiccups: The old work title, if edited is saved to the old work record but has no effect apparent when viewing the edition (because it now shows the newly-linked work record instead). The edition count for the old work record is decremented but it remains on solr even when decremented to zero. At that point, if the old work record is linked to an author record different from the new work record, it is difficult to find and correct., especially for translations.

Accordingly the work flow should go: 
1. change the old work to link the correct author record and save it.
2. change the old work title to the canonical title and save it again
3. change the edition record to link to the canonical work record and save that
4. only then, correct details on the edition record such as translated_from title and language

**Comment by LeadSongDog** [comment]
@cdrini  @mekarpeles 
Each of the editions previously under https://openlibrary.org/authors/OL2655525A/David_Knox has been attributed to a different work, by a different David Knox, yet that author record still incorrectly shows six works and eleven naked editions. The eleven (when clicked through) correctly show works by https://openlibrary.org/authors/OL217970A/David_Knox and the six (when clicked through) correctly show no editions. Hence, if correctly indexed none of the seventeen would appear under OL2655525A

**Comment by guyjeangilles** [comment]
@mekarpeles @hornc @salman-bhai What's the status of this? it loos like a temporary PR was merged but it was buggy

**Comment by awebdeveloper** [comment]
I see  duplicate copies of may books (search for books of Malcom Gladwell or "think and grow rich "or "the subtle art of not giving a fuck"). bumping this thread again

**Comment by mekarpeles** [comment]
This issue should be resolved, other than https://github.com/internetarchive/openlibrary/issues/2114
