### ISSUE TITLE
2023-09 Milestone Planning

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8166]
* [x] #8177
* [ ] Tracking issue for Persona Research: Learners (checklist)
    * [ ] #8180
    * [ ] Finalize budget for BWB coupons with BZ
    * [ ] Setup calendly
    * [x] Acquire a shared zoom via Caitlin
    * [ ] Transfer Abbey's google docs to internet archive
    * [ ] Decide whether to use google drive or private IA items for storage (preference towards google if space available)  
* [x] Canonical tags breakdown doc
* [x] Revise **Covers** issue with clear plan & checklist
* [ ] v2 search API
    * Search w/ editions + author img (w/ docs: https://openlibrary.org/dev/docs/api/search) @cdrini
