### ISSUE TITLE
OpenStax Trusted Book Provider

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8544]
- Titles in catalogue: [~60](https://openstax.org/about)
- Works in Open Library: [~62](https://openlibrary.org/search?q=id_openstax%3A*&mode=everything)
- [x] Tidy up the records
     - [x] #6152
     - [x] Remove accidental `openstax_id` field
- [x] Add proper openstax ID to every record
- [x] #6071 Display read button when provider ID present
- [x] #6071 Custom download options
- [x] #5577 Import missing records
- [ ] Set up automatic import pipeline
