### ISSUE TITLE
Librarian Merge Queue

### ISSUE THREAD

**Issue by Eds-Dbug** [internetarchive/openlibrary#8880]
## Purpose: 
The purpose of this document is give stakeholders context about what the Librarian Merge Queue is, why it exists, what challenges get in the way for librarians who use it, and what opportunities exist to improve the experience.

## Description, Patron Story

**What is the design change?**
Multiple UI/UX improvements for Librarians and Open Library Personnel on the Merge Queue page and Merge Link pages. 

**Why is this design change necessary?**
To improve the user experience for Librarian Merge Queue and Merge Links which will potentially add to productivity and more user friendly environment.

**Who is it for?**
Librarians and anyone who uses the Merge Queue.

Problems:
- [ ] 1. No Previews: There's no way to preview a merge without claiming it
- [ ] 2. Facets: When a submitter or reviewer is selected as a facet, it appears with a green check, but there is no hover state indicating that if you click, the selected option will be deselected.
- [ ] 3. Dashboard: There's no way to see a summary of how many people are contributing to the queue -- e.g. how many requests submitted per person and how many requests approved per super librarian
- [ ] 4. Merge type: It's difficult to know whether a merge request is for an edition or an author (and we do know this based on the url for the merge request).
- [x] 5. Merge btn loads before the rest of the page loads resulting in potential misclicks from which accidental merges occur. 

## Related Sub Issues
#8655 CLOSED

## Feedback

**Thoughts/reactions/feelings**
Suggestions from @onnotasler: 

1.) First proposed change is to ensure that the "merge" in the in Merge Link pages button doesn't load before the rest of the page loads to avoid misclicks which will result in accidental merges.
(SOLVED)

The proposed changes thus far do not seem to affect the overall visuals of the Merge Queue or Merge Link pages respectively.

**Comment by Realmbird** [comment]
Can I accept this but, I can I ask some questions to make sure I understand the problem

**Comment by mheiman** [comment]
Merging editions is probably out of scope as a Merge Queue improvement — there's a whole issue about that (#2114) because it involves creating new merging routines.

The current interface does support merging orphaned editions with works, though it's an undocumented feature.

**Comment by Realmbird** [comment]
Where can I view the interface

**Comment by Eds-Dbug** [comment]
Since Merging Editions is out of scope I will remove it from the list

**Comment by jimchamp** [comment]
@Realmbird, [here](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md#picking-good-first-issues) is how you can find a good first issue for Open Library.

**Comment by Realmbird** [comment]
ok thanks do I just wait for next first issue?
