### ISSUE TITLE
New onboarding page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9161]
We want to create a new page for folks to learn about Open Library after registering, or at any time!

- [ ] Design the onboarding experience we want
- [ ] Internal survey to collect potential features to showcase
- [ ] Land on the exact features/copy we want to showcase
- [ ] Implement the designs
- [ ] Add links in various places / during the registration flow

**Comment by mostafahassan04** [comment]
Hey @cdrini 

I am interested in this project. Could I get a more detailed description of the subtasks?
