### ISSUE TITLE
Improve Search Results Experience

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9232]
* [ ] #1001 - Fallback to FTS if 0 results found (no dead ends)
* [ ] #8884 - Show sneak-peak of "Search Inside" results as card on regular search page
* [ ] #8891 - Unify design of No Results found 
* [ ] #6923 and #8873 - More tolerant fuzzy search
* [ ] #2152 - Minor redesign of search results page to be mobile-first
* [ ] #8829 - Consolidating & redesigning sort options

**Comment by lokesh** [comment]
Adding the following Search UX issues to this epic:

- [ ] #12030 — Title search requires phrase match of all words
- [ ] #8972 — Show selected search facets even when there are no results
- [ ] #9932 — Make search sort option sticky by type
- [ ] #8299 — Author drop-down on edit form does not prioritise the most likely match
