### ISSUE TITLE
Supporting the Follow Feature

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9281]
### Problem

This epic is a followup to #8607

- [ ] #8828
- [ ] #9229
- [ ] Add Follow counts to /stats page, see #6839
- [ ] Fix caching of get_avatar_url
  - https://github.com/internetarchive/openlibrary/pull/8607/files#r1496013460
- [ ] Paginate Followers & Following pages

**Comment by Realmbird** [comment]
@mekarpeles Not sure how epic issues work but, can I try contributing to this

**Comment by RayBB** [comment]
@mekarpeles I'm a little confused by what it means to be the lead on this epic but not the lead on the sub tickets, which haven't moved in a while. Should we close this?
