### ISSUE TITLE
Web books

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9582]
### Problem

An epic for tracking work on [web books](https://openlibrary.org/trusted-book-providers).
- [ ] implement an initial draft of web books support that allows admins to add a web book, see the read button on the book page and in search, allows a patron to click the read link, opens the book in a new tab, and displays a toast message about visiting an external site. Issue #9419 / PR #6585.
- [ ] Add analytics to all the Trusted Book Provider/Direct book provider read buttons
- [ ] Switch to the new read button endpoint to get `statsd` tracking
- [ ] Audit existing direct book providers in http://openlibrary.org/query.json?type=/type/edition&providers.access=read&*&limit=100
- [ ] Write guidelines for what we want to be included (put somewhere nice + link to from edit page + post in slack + also ping Onno)
- [ ] Make it possible to search for direct book providers that aren't format: web (which is currently the only way)
- [ ] Support download options on the book page for web books. Issue: #9581.
- [ ] Make web books work in carousels (i.e. when a web books appears in a carousel, it should display the "read" button).

### Stakeholders

@cdrini 
@mekarpeles 
<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
Can this draft now be closed https://github.com/internetarchive/openlibrary/pull/8558 since #6585 has been merged? Or are they unrelated?

cc: @scottbarnes + @cdrini
