### ISSUE TITLE
Bulk Search V2

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9619]
- [ ] Switch to gpt-4o-mini and confirm all works well (it's cheaper!)
- [ ] Replace `extractionOptions.use_gpt` with e.g. `AbstractExtractionAlgorithm`, and have two extraction aglorithms, a `RegexExtraction` and `AIExtraction`. But future PR!
- [ ] Create new endpoint, `/account/lists/add`, so that the "Create a list" button creates a list for the user instead of a global list, which is currently admin only
- [ ] Fix create list has wrong link until matches finally finished
- [ ] Add support for tabular input
- [ ] Get confirmation / implement BulkSearch V2 designs
- [ ] Add links to bulk search from search dropdown, search toolbar

Nice to haves:
- [ ] Copy config pattern from LibraryExplorer so we can e.g. test from local but hit the production search endpoint via url parameters.

## Stakeholders

@benbdeitch
