### ISSUE TITLE
Encapsulate subject page components as macros

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#9785]
### Proposal

A number of sections on our `/subjects` pages are hard-coded in the page's template.  If these were macros instead, we could leverage our new `CacheableMacro` to cache these components.

### Justification

This change will make it easier to cache slow-loading components of the subjects page, specifically when we migrate the string-based subject to a subject Tag.  As a part of this process, we can wrap every macro found in the subject page's body in a `CacheableMacro`, which should make subsequent page loads faster.

#### Requirements Checklist

* [ ] Create "Related Subjects" macro
* [ ] Create "Prolific Authors" macro
* [ ] Create "Publishing History" macro
* [ ] Replace `custom_carousel` template with equivalent carousel macro
* [ ] Update subject page template to use these macros

#### Related files

* [Subject page template](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/subjects.html)
* [CacheableMacro](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/CacheableMacro.html)

#### Stakeholders

* @mekarpeles 

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.
